### ISSUE TITLE
Callback code not being removed

### ISSUE THREAD

**Issue by flyfishMT** [authts/oidc-client-ts#1000]
The Code, State, etc query parameters are not being removed from the URL after callback.  This is replicated running the example app in react-oidc-context.  Is this to be expected and should be handled manually or should this be removed?

![image](https://user-images.githubusercontent.com/5473678/236526971-3f1e0c64-92c9-405c-adaf-c6d4f492bc84.png)

**Comment by storageddd** [comment]
Actual for me too
