### ISSUE TITLE
Timer leaks break token refresh in NextJS

### ISSUE THREAD

**Issue by zarganum** [authts/oidc-client-ts#1007]
Dear team, 

In a multi-page app when NextJS [Router Link](https://nextjs.org/docs/pages/api-reference/components/link) element is used for navigation between pages, each page click initializes (loads) the `UserManager` from context along with corresponding `UserManagerEvents`. Without SSR, no "real" page load-from-server happens by NextJS design (which is my case and default). As the user is still logged in, there are no calls of `AccessTokenEvents.unload()` to clean up the used (ancestor) timers, so the JS runtime keeps running with these timers.

As a result, _ancestor_ renewal **timers are leaked** and continue triggering the token refresh, together with the _newly initialized_ timers. Each user click spawns a new pair of timers ("expired" and "expiring" ones) that act in parallel with existing ones. As access token is the same, this gang of timers attempts to use the same refresh token to renew the same access token. My OAuth2 provider considers this concurrent refresh operation invalid and I totally agree with it:)
Because typical access token TTL is 1h, users might experience strange, delayed, randomly reproducible errors.

Do you agree the Singleton Timer would be more appropriate using the existing string identifier?
E.g.

before:
```
AccessTokenEvents.ts (used by UserManagerEvents):
    private readonly _expiringTimer = new Timer("Access token expiring");
    private readonly _expiredTimer = new Timer("Access token expired"); 
```
after:
```
    private readonly _expiringTimer = new Timer.getInstance("Access token expiring");
    private readonly _expiredTimer = new Timer.getInstance("Access token expired"); 
```
I would expect the timer persistence from this change and safety for NextJS and all other client-side-rendering frameworks.

many thanks

**Comment by pamapa** [comment]
How do you use the userManager? Its design assumed that you only one per IDP. In react applications that can be achieved via `React.createContext`. See e.g. https://github.com/authts/react-oidc-context

**Comment by zarganum** [comment]
> How do you use the userManager? Its design assumed that you only one per IDP. In React applications that can be achieved via a `React.createContext`. See e.g. https://github.com/authts/react-oidc-context

I issue `useAuth()` from `react-oidc-context` so `UserManager` is implicit.
Only single `AuthProvider` is used.

Does it answer?

many thanks

**Comment by zarganum** [comment]
After app redesign, the problem is no longer reproducible.
We believe it was the improper usage of contexts in CSR.
Apologies.
