### ISSUE TITLE
Make Response Mode Optional (Oracle IDCS)

### ISSUE THREAD

**Issue by dzirg44** [authts/oidc-client-ts#1010]
In Oracle IDCS (Identity Cloud Services) both options 
(according to https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html)

- Response Mode for the OAuth 2.0 code Response Type is the query encoding
- Response Mode for the OAuth 2.0 token Response Type is the fragment encoding

are invalid.
If I use 
`query => code` 
I have 
```sh
Oops... Client 111111 provided an invalid response mode: query.
```
in case 
`fragment => token`

```sh
Unhandled Rejection (Error): Only the Authorization Code flow (with PKCE) is supported
```

Only when I remove the default value 

https://github.com/authts/oidc-client-ts/blob/main/src/OidcClient.ts#L102

I can make it work.

In my opinion , if it is not a mistake caused by Oracle developers there are 2 ways to fix.
1 - simply delete the default value
2 - add 'none' option to response_mode

the fix I found out exploring 
https://auth0.com/docs/authenticate/login/oidc-conformant-authentication/oidc-adoption-auth-code-flow#code-exchange-request-authorization-code-flow-with-pkce

**Comment by pamapa** [comment]
I agree, when reading the spec (https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest):
- "response_mode
        OPTIONAL. Informs the Authorization Server of the mechanism to be used for returning parameters from the Authorization Endpoint. This use of this parameter is **NOT RECOMMENDED** when the Response Mode that would be requested is the default mode specified for the Response Type. "

Means when `response_type` is `code`, which is always the case in this library anyway, we should not set `response_mode` by default.

I will need to test this first on other real IDPs first...

**Comment by pamapa** [comment]
Should we fixed that in a major or minor version? I tend to do it in a minor, as it fixes a bug and the chance that existing IDPs still work seems high. Will add a release notice for that...

**Comment by dzirg44** [comment]
@pamapa the chance that it can break something is low, i agree, but if you don't specify it in your config it means that the response_mode will be query , and after the upgrade it will be absent and it can lead to changing the behavior for the app. I would like to see it in a minor version update, but if you don't want to struggle  with issues like "after the upgrade the auth is broken" - major is more suitable. And thank you for your work.

**Comment by pamapa** [comment]
@dzirg44 You are right lets do this on the planned 3.0.0, which comes later this year.
