### ISSUE TITLE
Can I use this oidc client for Azure AD?

### ISSUE THREAD

**Issue by vitjaz** [authts/oidc-client-ts#1021]
I use this client for Azure AD auth.
Get from Azure user with access_token after success login.
![image](https://github.com/authts/oidc-client-ts/assets/47814045/35fc7250-1b51-4de0-a3e0-b29e74ec3bbf)

Then I try to get this token on my backed and validate with `'validate-azure-ad-token'` npm package.
Have this error on backend:
`Validate token! Payload: Error: The access token could not be decoded`
![image](https://github.com/authts/oidc-client-ts/assets/47814045/2a7f88a6-3bfb-4cc1-b1f0-07d5be25548b)

I try to check this access_token from Azure and it's not valid JWT.

What I am doing wrong? I need use `msal` for frontend app instead of oidc? But why if both of them support OAuth 2.0.

**Comment by vitjaz** [comment]
@pamapa  and you have valid JWT token?
My way is to store the user in userStore.
Pinia store: 
```js
import { User } from 'oidc-client-ts'
import UserManagerAD from '~/auth/auth'

interface IState {
  userManager: UserManagerAD | null
  user: User | null
}

export const useUserManagerStore = defineStore('userManagerStore', {
  state: () =>
    ({
      userManager: null,
      user: null
    } as IState),
  actions: {
    async getUser() {
      const user = await this.userManager.getUser()
      this.user = user
    }
  }
})

```

And then I'm use `access_token` it in my fetch hook in Nuxt 3 fe app:
```js
import { useLazyFetch } from 'nuxt/app'
import { useUserManagerStore } from '~/stores/userManagerStore'

type useFetchType = typeof useLazyFetch

export const useAPILazyFetch: useFetchType = (path, options = {}) => {
  const config = useRuntimeConfig()
  const userManagerStore = useUserManagerStore()
  options.baseURL = config.public.baseURL
  options.headers = [
    ['Authorization', 'Bearer ' + (userManagerStore.user?.access_token || '')]
  ]
  return useLazyFetch(path, options)
}
```

So in my store after auth I have object of user (hide info, show structure):
```json
{
    "id_token": "...",
    "session_state": "....",
    "access_token": "PAQABAAIAAAD....9l72s8gAA",
    "refresh_token": "...",
    "token_type": "Bearer",
    "scope": "openid",
    "profile": {
       // my profile info
    },
    "expires_at": 1684945584
}
```

This access_token not valid 
![image](https://github.com/authts/oidc-client-ts/assets/47814045/3352322c-f62e-43bc-8cb7-6b2cf6cc4ead)

So I don't understand what's wrong with my access_token.

Maybe it's ok for Azure AD token? If yes - what library on backend you use for token validation?

**Comment by Badisi** [comment]
The issue you are facing has nothing to do with this library.

As per the specs `access token` do not have a defined format (unlike `id token` which should be JWTs).
It is up to the identity provider to choose the format of the access tokens (they could be JWT but also opaque tokens that could not be decrypted).

You should read this Azure documentation that talk about this:
https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens

Also I'm not familiar with AzureAD but sometimes identity providers offers you some options to choose the access token format.

**Comment by vitjaz** [comment]
@pamapa @Badisi  I found solution! I change my authority adress by adding /v2.0.

```js
const manager = new UserManager({
  authority:
    'https://login.microsoftonline.com/tenant_id/v2.0',    // <--- here we NEED /v2.0
  client_id: '....',
  redirect_uri: hostUrl + '/ad/callback',
  scope: 'User.Read'
})
```

And now I have valid JWT access_token. But for now I have trouble with my callback page. It don't redirect user to main page after auth.

Code:
```js
onMounted(() => {
  userManagerStore.userManager
    .signInRedirectCallback()     // <-- this method throw error
    .then(() => {
      const redirectUrl = window.localStorage.getItem('contactsADRedirectUrl')
      window.location.href = redirectUrl || '/'
    })
    .catch((err) => console.error(err))
})
```
Error:
![image](https://github.com/authts/oidc-client-ts/assets/47814045/549b11bc-116b-4a5e-ba41-cb9ac9dd8c1d)

**Comment by pamapa** [comment]
You must trace the exact location inside this library where the error is thrown and post it here...

**Comment by vitjaz** [comment]
Okey, for now I change Azure settings and add correct scope. This is valid variant:
```js 

const manager = new UserManager({
  authority:
    'https://login.microsoftonline.com/tenant_id/v2.0',
  client_id: 'my_client id',
  redirect_uri: hostUrl + '/ad/callback',
  scope: 'api://my_client_id/Custom.Read openid' <-- VERY IMPORTANT FOR AZURE. IF YOU MISS  THIS OR PASS INVALID VALUE - YOU WILL GOT AN ERROR OR INVALID JWT
})
```

`Custom.Read` - custom scope from my Azure. You need to setup your own.
Good guide - https://www.youtube.com/watch?v=59YwW8FrLm8.
Also good note - https://stackoverflow.com/questions/75535497/azure-oauth2-cant-validate-access-token
And for now auth process work correctly. And my token is VALID JWT!
![image](https://github.com/authts/oidc-client-ts/assets/47814045/453ddeea-fe7f-428f-ba3a-35be3608cd5b)

Very important after each test clean your localStorage and sessionStorage. 

@pamapa Show me plz which lib for access_token validation you use on the backend.

**Comment by pamapa** [comment]
I am using .Net 6 with only build-in frameworks within the official core libraries. For Azure AD i use [AddMicrosoftIdentityWebApi](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-web-api-call-api-app-configuration?tabs=aspnetcore). For PingID i use extended version of [AddJwtBearer](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-6.0)

**Comment by vitjaz** [comment]
So, thanks guys. I think we can close this issue.
Result:
- Azure AD + oidc working nice.
- For that you need correct scope and another credentials.
