### ISSUE TITLE
Recommended way to add login_hint parameter to authorize request URLs?

### ISSUE THREAD

**Issue by cbrenberg** [authts/oidc-client-ts#1022]
Hi - After digging through the docs for a while and coming up short, I thought I'd just ask you directly. 

What's the best/recommended way to append the optional `login_hint` query parameter to the authorize URL on signin attempts made via the UserManager class?

I'm hoping to be able to pass a user's email address as the login_hint to prepopulate the username field on our login page.

Thanks in advance for any guidance from maintainers or the community!

**Comment by pamapa** [comment]
You can pass `login_hint`  as an extra parameter into `signinRedirect` and other sigin functions. You will need at least v2.2.2 of this library...

**Comment by cbrenberg** [comment]
Thanks so much! That was just what we needed!
