### ISSUE TITLE
Should Automatic Silent Renewal be followed by non-Silent renewal 1 minute later

### ISSUE THREAD

**Issue by derekmcloughlin** [authts/oidc-client-ts#1030]
Hi, 

We're using oidc-client-ts with a Ping Federate SSO provider. The server's access token last 30 mins and we have automatic silent renewal switched on with the default `accessTokenExpiringNotificationTimeInSeconds` of 60 seconds.

We have the following scenario:

1. User logs in.
2. After 29 mins the automatic silent renewal takes place (see the log attached @ 09:40:04.385 line 101).
3. The user interacts with the page for 60 seconds
4. Once the 60 seconds are up, they're logged out and logged in again, but not silently (we display a splash screen for a few seconds).

It seems that despite the automatic silent renewal, once the timer is up for the original token the non-silent renewal takes place regardless.

My question is this: should we be seeing the non-silent renewal after the automatic silent renewal?

The log file for the session is attached. (I've changed the tokens to have values like ACCESS_TOKEN_1 etc. to make it easier to read).

Any help or pointers would be greatly appreciated.
[scenario1_clean.txt](https://github.com/authts/oidc-client-ts/files/11634605/scenario1_clean.txt)

**Comment by derekmcloughlin** [comment]
Just pinging. Can anyone point me in the right direction?

**Comment by Badisi** [comment]
The behavior you are describing can clearly be seen in your log.

1. Token is expiring and signin silent begins (`Line 101`)
    > 09:40:04.385 oidc-client-ts.js:103 [UserManager] signinSilent: begin

2. From there, everything went well and tokens are renewed

3. Then a signin redirect suddenly occurs (`Line 163`)
    > 09:41:04.458 oidc-client-ts.js:103 [UserManager] signinRedirect: begin

---

But the `signinRedirect()` method is only exposed as a public API and is never called anywhere else in the library.
So the fact that it is suddenly called in the log means YOUR code is calling it somewhere.
I think you should be investing from there.

**Comment by derekmcloughlin** [comment]
Thanks for the direction. I was able to find the culprit in our own code.
