### ISSUE TITLE
SignIn with new tab instead of popup

### ISSUE THREAD

**Issue by deanmaster** [authts/oidc-client-ts#1048]
Hello everyone,

Currently i'm configuring and use function 
`uaaInternalUserManager.signinPopup` for login processes. My project can't allow to do redirect login or replace the current application running. The login process has to be done in a new either tab or windows.

The problem with popup is you as end user has to click on enable popup feature on the browser in order to enter your credentials in IDP's login form. 

Does someone know how to configure the `SigninPopupArgs` so that it can open a new tab or new window instead of popup ?

Thanks,
Tuan Do

**Comment by pamapa** [comment]
You could create the new tab within your code, in that new tab you call e.g. `signinRedirect`. You will need to change the storage of the access token from session to local within your oidc configuration...

**Comment by deanmaster** [comment]
hmm I read that idea from some other isues which you suggested as well. The problem is i want to keep session storage for  more security reason than local storage. Local Storage store information longer than user need.

But thank you

**Comment by deanmaster** [comment]
actually it does not matter since the function works perfectly in case the
browser knows it's user interaction. The popup is only blocked in case it's
called directly via code without any user interactions. So I can just call
login function via a onclick then the popup is shown without any problem.
