### ISSUE TITLE
Difference in docs and JS Docs for UserManagerSettings.stateStore

### ISSUE THREAD

**Issue by MFredX** [authts/oidc-client-ts#1051]
In the library's docs on UserManagerSettings's stateStore field (found in https://authts.github.io/oidc-client-ts/interfaces/UserManagerSettings.html#stateStore), there is a difference in the JS Doc found in UserManagerSettings.ts and in the doc.

Docs mention that 

> Storage object used to persist interaction state (default: window.localStorage, InMemoryWebStorage iff no window). 

JSDoc mentions

> Storage object used to persist User for currently authenticated user (default: window.sessionStorage, InMemoryWebStorage iff no window)

The JSDoc appears to be more accurate as the default is actually sessionStorage.

**Comment by pamapa** [comment]
They do not describe the same property. `stateStore` (OidcClientSettings.ts) vs `userStore`  (UserManagerSettings).

**Comment by MFredX** [comment]
My bad, thanks for the clarification
