### ISSUE TITLE
Minimum required typescript version?

### ISSUE THREAD

**Issue by Rideen** [authts/oidc-client-ts#1056]
Hi everyone,

what is the minimum required typescript version for the project? 

I cannot get my Angular 8 project to build at all (typescript@3.4.3), I keep getting odd errors from oidc-client-ts files.

**Comment by pamapa** [comment]
See https://github.com/authts/oidc-client-ts/blob/main/tsconfig.json -> "target": "ES2019". For me using typescript v4.8.4, which works. Typescript v3.7 should work already, i am not sure if any lower version than this will work too.

**Comment by Rideen** [comment]
Thanks pamapa!

I can confirm it works with 4.3.5.
