### ISSUE TITLE
oidc-client-ts with apple provider

### ISSUE THREAD

**Issue by philipmvp** [authts/oidc-client-ts#1060]
Does oidc-client-ts support login with apple? I have configured to use it with Apple but I get CORS error while invoking token endpoint.

**Comment by pamapa** [comment]
OAuth and OIDC are standard independent of your OS. The browser however must have support for some features. I see no reason why Apples webkit should not be functional.

CORS error usually mean a configuration error on the server side of your application. You typically must configure your application uri and redirect uri to an allow list...

**Comment by philipmvp** [comment]
Sorry, I wrote it wrongly. My question is whether oidc-client-ts supports login to Apple Identity provider.  I got the CORS error when the oidc-client-ts invoked the token end point.

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
