### ISSUE TITLE
Is there a way to force renew token?

### ISSUE THREAD

**Issue by vocko** [authts/oidc-client-ts#1073]
I'm looking for a way to force the client to renew the token (ie. after user gets new claims but he has to wait until the token refreshes to come into an effect). I do not need to revoke the token but I want to force the client to get a new access token asap.

Is there a way to achieve this?

**Comment by pamapa** [comment]
Using `startSilentRenew` should do the trick.

**Comment by vocko** [comment]
Hello @pamapa thank you for your quick answer.

I was looking into the code, isn't it doing anything when the `_isStarted` is already set to `true`?

Or is the stop method (that resets it) being called when a new access token arrives?

**Comment by pamapa** [comment]
`SilentRenewService` is designed to handle properly renewing token, when needed. When you want to reuse this service, you will have to extend the code to make it work what you need. As there is no way to force it yet. I thought maybe using directly `startSilentRenew` may work for our case. In any case you will need to debug into the code...

**Comment by Badisi** [comment]
Why not simply use [UserManager.signinSilent()](https://authts.github.io/oidc-client-ts/classes/UserManager.html#signinSilent) ?

**Comment by misl-smlz** [comment]
> Why not simply use [UserManager.signinSilent()](https://authts.github.io/oidc-client-ts/classes/UserManager.html#signinSilent) which renew all the tokens ?

Just for the record: This only works for valid (not expired) tokens. We do a [UserManager.removeUser()](https://authts.github.io/oidc-client-ts/classes/UserManager.html#removeUser) and a [UserManager.signinSilent()](https://authts.github.io/oidc-client-ts/classes/UserManager.html#signinSilent).
