### ISSUE TITLE
Does this library support introspection endpoint?

### ISSUE THREAD

**Issue by Sameer259310** [authts/oidc-client-ts#1084]
Most of the OIDC providers support introspection_endpoint to manage users session.
It seems like, this library is supporting check_session_iframe endpoint, and not introspection endpoint.
will it work with OIDC providers that are not supporting check_session_iframe endpoint for session management? (In my case, its Salesforce IDP)

**Comment by pamapa** [comment]
This library does not support `introspection_endpoint`. You will need to extend it to do so, you should be able to extend the classes (MetadataService, OidcClient) on your side.

**Comment by Sameer259310** [comment]
As per my understanding from your response, we have to manually introspect token endpoint using these classes.
By doing so, will we able to manage user session and token expiry or we have to write custom logic for that too?

**Comment by pamapa** [comment]
Yes, you will need to write code to do so. Would be nice if you could share that code here...

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
