### ISSUE TITLE
SSR applications support

### ISSUE THREAD

**Issue by rkorzhoff** [authts/oidc-client-ts#1098]
This lib is awesome, but... Any plans? I'd like to use this library in my Nuxt 3 app, but there are reasons like a strict WebStorage usage (for workaround i'm using my own implementation), window calls that make it hard

**Comment by pamapa** [comment]
see #256

**Comment by some-user123** [comment]
@rkorzhoff Can you share your solution for Nuxt 3? Finally managed to use `OidcClient` to sign in incl. callback. But it really feels like fiddling around...

**Comment by idc77** [comment]
For complete SSR I like https://next-auth.js.org/
It's not for SPA though, only SSR.

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
