### ISSUE TITLE
The 'credentials' field on 'RequestInitializerDict' is not implemented. 

### ISSUE THREAD

**Issue by randomairborne** [authts/oidc-client-ts#1100]
Hi! I'm trying to use this library on Cloudflare Workers, which does not implement fetch credentials. Is there a way to disable these? I've tried setting `fetchRequestCredentials: null` on `OidcClientSettings`, but it still throws the error.
issue-ref: https://github.com/cloudflare/workers-sdk/issues/2514

**Comment by randomairborne** [comment]
I have realized this is more of a bug in workers- I was wondering if this is something you actually wanted to fix, or if you'd rather wait for CF.

**Comment by pamapa** [comment]
i wont do anything yet :-)

**Comment by randomairborne** [comment]
https://github.com/cloudflare/workerd/issues/902 is the issue on the cloudflare repo. Thanks for your response.

**Comment by randomairborne** [comment]
is this actually fixed, or is it wontfix?

**Comment by pamapa** [comment]
this can not be fixed in this library as you said its an issue here https://github.com/cloudflare/workerd/issues/902, thus no need to track it here

**Comment by randomairborne** [comment]
alright- do you mind using the "not planned" close feature instead? It's a little clearer.

**Comment by pamapa** [comment]
I rather set the invalid label, as the bug you describe is not in this repo. E.g. `RequestInitializerDict` does not exist here.
