### ISSUE TITLE
ID_Token Validation 

### ISSUE THREAD

**Issue by neran21** [authts/oidc-client-ts#1113]
I don't know if this is an actual issue but asking for clarification. In the ResponseValidator is the id_token being validated used OIDC's ID Token Validation. I saw in the code history that the logic was there before.
https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

**Comment by neran21** [comment]
I saw the specs on that but in regards to Authorization Flow, there is mentions about ID Token Validation
![image](https://github.com/authts/oidc-client-ts/assets/10640084/38851cfb-0b1c-4cac-b2eb-1bc65a984cf3)
![image](https://github.com/authts/oidc-client-ts/assets/10640084/28a9060f-73a2-4b59-ad1e-949223382080)

Would this step need to be included in the code changes? Im sorta new to OIDC but I wanted to implement this library but was told that token validation was required which I wanted to get confirmation on.

**Comment by pamapa** [comment]
Ah i see the miss understand on my side. I was talking about cryptographic validation.
When the token is transferred securely over the wire and can not be altered by a "man in the middle attack", there is no need to cryptographic validate the token, you anyway need to trust the IDP.

This library does validate some fields, see
https://github.com/authts/oidc-client-ts/blob/1a36b87ded414e86985d44ce4b8f49ef3f4f6d45/src/ResponseValidator.ts#L189-L216

**Comment by neran21** [comment]
Thank you. My last question would be for the id token validation should there be additional checks for the  response? I know that somewhere in the code the signing keys are stored but it looks like it isnt used anywhere. Or would that be something that I would need to add in addition in my own code?

**Comment by pamapa** [comment]
> ..the signing keys are stored..
As mentioned above signing keys were used for cryptographic validation. That has been removed for good and you do not need to do it your self. BTW the cryptographic validation was never done any way for the code flow, but only for the implicit flow, which has been removed as well...

**Comment by neran21** [comment]
Ok. Thank you for the clarification.
