### ISSUE TITLE
Refocus popup window

### ISSUE THREAD

**Issue by Soren-Knudsen** [authts/oidc-client-ts#1114]
**Question**: Is it possible to refocus a signinPopup window without reloading the window's content? I am currently using the signinPopup as follows:

```js
const result = await manager.signinPopup({
  popupWindowTarget: 'CustomWindowName',
  popupWindowFeatures: {
    width: 400,
    height: 588
  }
});
```

By adding the`popupWindowTarget` option, I can refocus the window, but the content reloads each time. Are there any other options to refocus the window without reloading the content?

**Comment by pamapa** [comment]
You have to look into the source code. See [src/navigators/PopupWindow.ts](https://github.com/authts/oidc-client-ts/blob/1a36b87ded414e86985d44ce4b8f49ef3f4f6d45/src/navigators/PopupNavigator.ts)

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
