### ISSUE TITLE
Configure "client_secret" without exposing it

### ISSUE THREAD

**Issue by johnnypea** [authts/oidc-client-ts#1121]
How can one configure "client_secret" without exposing it to the browser?

As I understand I need a "window" to call `signinRedirect` and `signinCallback` methods.

Thank you.

**Comment by pamapa** [comment]
when you run this library within the browser its not possible to hide/not expose the client_secret, thus do not use that, use the code flow with PKCE!

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
