### ISSUE TITLE
Custom header in /token endpoint

### ISSUE THREAD

**Issue by henriquefockink** [authts/oidc-client-ts#1126]
Hi! My IDP request a custom header in the /token (POST) endpoint, containing the "client_id:client_secret" encoded in base64 like this: "Authorization": "Basic ZGV2ZWRvci1wc=".

How could I achieve this?

**Comment by pamapa** [comment]
should be doable with settings `client_authentication = "client_secret_basic"`

**Comment by henriquefockink** [comment]
It worked! Thank's!
