### ISSUE TITLE
Support for es5

### ISSUE THREAD

**Issue by ashish701ranjan** [authts/oidc-client-ts#1127]
Hi team,

I am looking to use the package as es5 to make it work in IE.
Would it be possible to release a build that has es5 bundles in it?

Mine is an angular 12 project and I am having difficulties in making an es5 version of OIDC, I have asked a relevant question here:
https://stackoverflow.com/questions/76918233/transpile-specific-packages-in-node-modules-to-es5/76918293#76918293

**Comment by pamapa** [comment]
This project has removed support for IE.
You would have to make a release for your own or maybe could can use enough polyfils. If you manage to make it run please let us now. Another solution might be that you compile your own version with target es5.

As an alternative the predecessor library [[IdentityModel/oidc-client-js](https://github.com/IdentityModel/oidc-client-js)](https://github.com/IdentityModel/oidc-client-js) might work in your case.
