### ISSUE TITLE
Adding support for custom navigators?

### ISSUE THREAD

**Issue by philjones88** [authts/oidc-client-ts#1147]
Would the maintainers be open to another PR focused at adding support for custom navigators? (Kinda did ok on the storage engine one, working well in a product with Electron!)

Scenario:

Building a React + Ionic + Capacitor app for iOS. It kinda works ok if you let it leave the app and redirect back.

Ideal solution is to use the Capacitor Browser plug-in to open it without leaving the app.

My idea:

Add 3 new settings to "UserManagerSettings". 

That either get defaulted to the existing if not defined like here:

https://github.com/authts/oidc-client-ts/blob/main/src/UserManagerSettings.ts#L187

Then alter here to use the values from "UserManagerSettings":

https://github.com/authts/oidc-client-ts/blob/main/src/UserManager.ts#L98

**Comment by Badisi** [comment]
For an integration with Capacitor, you can check my comment here: [#537 Integration with Capacitor](https://github.com/authts/oidc-client-ts/issues/537#issuecomment-1406247758).

You can also use the VanillaJS version of my [library](https://github.com/Badisi/auth-js) (which is a wrapper around **oidc-client-ts**) as a "ready to use" solution and integrate it in your React app. Or even better, make a PR to support React as it was done with [Angular](https://github.com/Badisi/auth-js/tree/main/projects/ngx-auth).

**Comment by philjones88** [comment]
We've already got wrappers around this Lib for RTK support.

I do think custom Navigators via the settings object is the cleanest approach and could be built in to extend other solutions other than capacitor?

**Comment by pamapa** [comment]
if the changes are not that invasive i am open for that. The idea is that this library can also be used as a SDK like library, which can be extended easily.

**Comment by philjones88** [comment]
I started down this route coding it up. Changes might be tougher. The Navigator classes have constructors that take in settings. That needs removing for some tests to pass. It spirals as the types say the params for the functions and optional but they are not.

Not 100% sure this change isn't going to be invasive. The Navigator classes and usages are very tightly coupled.

I will start again. I think I might go the route of splitting the typings of the Navigator and UserManager methods. They are shared and cause issues. But keep the functionality the same.

**Comment by philjones88** [comment]
I'm going to do a full build iOS of my app using custom Navigators (redirect and iframe, for silent renew) using @Badisi 's capacitor logic as a base for the custom navigators. I put the initial PR up for feedback on the approach rather than it to be fully ready to merge. As I may have missed something key in my understanding.

**Comment by philjones88** [comment]
Overriding `RedirectNavigator` with an implemenetation similar to @Badisi works (we use React so in onSuccess of his class I had to add additional logic).

@Badisi have you hit an issue with Capacitor Http and `JsonService` ? Capacitor Http doesn't seem to support `URLSearchParams` being passed as `body` here when used for `/connect/token` POST https://github.com/VQComms/oidc-client-ts/blob/main/src/JsonService.ts#L129

**Comment by Badisi** [comment]
This issue is related to Capacitor 5 which was released 4 months ago.
I had yet to test it but now that I did I'm also facing the same issue.

I have upvoted the issue #6792 and asked for clarification and high priority.

**Comment by Excel1** [comment]
How can i use the custom navigators? It is possible to use Capacitor Browser Plug-In now?

**Comment by Badisi** [comment]
> For an integration with Capacitor, you can check my comment here: [#537 Integration with Capacitor](https://github.com/authts/oidc-client-ts/issues/537#issuecomment-1406247758).
> 
> You can also use the VanillaJS version of my [library](https://github.com/Badisi/auth-js) (which is a wrapper around **oidc-client-ts**) as a "ready to use" solution and integrate it in your React app. Or even better, make a PR to support React as it was done with [Angular](https://github.com/Badisi/auth-js/tree/main/projects/ngx-auth).

@Excel1, I explained how this can be achieved in the second post of this thread...

**Comment by Excel1** [comment]
@Badisi thanks for help. I think it should be a good feature for oidc-client.ts since Apple forces by app publishment to use the safari api browser for redirection
