### ISSUE TITLE
creating UserManager seems to remove expired user from storage

### ISSUE THREAD

**Issue by floge07** [authts/oidc-client-ts#1151]
Calling new UserManager(settings) in the initialize phase of my vue app, seem to cause some cleanup job to run which removes the current user from the storage (if marked as expired)

Why is that bad?
The expired property on the User is true when the access_token is expired (as to my understanding),
but the User may still have a valid refresh_token.

I want to do signinSilent when initializing my app to restore the current auth state from the storage and try to renew the access_token/refresh_token pair before deciding to show a please login page.

**Comment by floge07** [comment]
Sorry again, I'm tired... Found it now. It was on our part...
Someone actually added some storage cleanup logic. I couldn't find it because it didn't reference anything from the AuthStore or the oidc-client-ts package... it just serialized every storage item to json and looked for a 'expires_at' field... 🙄

**Comment by pamapa** [comment]
thanks for reporting back!
