### ISSUE TITLE
UserManager.signinPopup closes with code, but returns an error instead

### ISSUE THREAD

**Issue by Kurolox** [authts/oidc-client-ts#1154]
I have a small django server with `django-oauth-toolkit`, and I've been trying to get this library working (among `react-oidc-context`, but it's not too relevant right now because I can reproduce the same issues using `UserManager` directly)

Here's a minimal code sample that showcases the behavior I'm getting.

```ts
  const userManager = new UserManager({
      authority: "http://localhost:8000/o/",
      client_id: "EXAMPLE_CLIENT_ID", // This is just obfuscated, the actual client ID of the OAuth application is here
      redirect_uri: "http://localhost:8000/jsoCallback",
  })

console.dir(await userManager.signinPopup())
```

This seems to initiate the OAuth flow properly and a popup with the login appears, but after logging in and authorizing the scopes, I can see the popup window URL change briefly to the redirect URL with the access token, then it closes. 

I'd expect the `User` instance to be logged, but instead I get an error that the popup was closed by the user (https://github.com/authts/oidc-client-ts/blob/d1c9354bf5289a878c262090ea5f7f31de697fb7/src/navigators/PopupWindow.ts#L41). I'm not sure if I'm doing anything wrong. The only think that I can think of is that the provided `redirect_uri` is not related to the current window href, which I could understand being an issue if I were using `signinRedirect`, but with the popup this shouldn't be an issue.

**Comment by Badisi** [comment]
When using `popup` mode, you should redirect to an html page containing the following:
```html
<body><script>window.opener.postMessage({ source: 'oidc-client', url: location.href }, location.origin);</script></body>
```

**Comment by Kurolox** [comment]
> When using `popup` mode, you should redirect to an html page containing the following:
> 
> ```
> <body><script>window.opener.postMessage({ source: 'oidc-client', url: location.href }, location.origin);</script></body>
> ```

Wow, that was fast!

Thanks for the input. Actually I realized that the reason the oauth popup was closing is because there was a script in the redirect URL html page closing the window...

I've removed that and added the `window.postMessage` script, and now it doesn't close automatically, but unfortunately nothing else happens either, so I assume that there's something wrong with the message. I'll try to dig a bit on the code on how the client handles the message, is there any other place with documentation about the `popup` mode? I couldn't find a lot by myself unfortunately.

Also, for reference, here's the HTML page that I'm redirecting to.

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Successfully logged in</title>

    </head>
    <body>
        <script type="text/javascript">
                window.opener.postMessage({ source: "oidc-client", url: location.href }, location.origin)
        </script>
    </body>
</html>

```

**Comment by Badisi** [comment]
Your app should load the `oidc-client-ts` which itself should load a popup.
Inside the popup, you should be presented with your IDP login page.
Then once logged-in, your IDP should redirect you to your redirect_page (still inside the popup).
Once on the redirect_page the script should post the current url to the parent window (ie. your app).
The lib is listening to this post ([here](https://github.com/authts/oidc-client-ts/blob/d1c9354bf5289a878c262090ea5f7f31de697fb7/src/navigators/AbstractChildWindow.ts#L62)), so it will receive the url, extract the info and close the popup.
Everything should be fast enough so you don't even see the redirect_page displayed in the popup (and as such you don't need a title or anything else than the script)
