### ISSUE TITLE
code examples

### ISSUE THREAD

**Issue by idc77** [authts/oidc-client-ts#1189]
Actual code examples, where one doesn't have to go to some third party "developer blog" would be nice.

**Comment by pamapa** [comment]
see https://github.com/authts/oidc-client-ts/tree/main/samples/Parcel and https://github.com/authts/sample-angular-oidc-client-ts.

**Comment by github-gael-soude** [comment]
I agree that the documentation lack of examples.
Some examples with React could be great :)

**Comment by pamapa** [comment]
for react see https://github.com/authts/react-oidc-context

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.
