### ISSUE TITLE
Invalid token specified: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by dopry** [authts/oidc-client-ts#1206]
I'm testing a service using the Resource Owner Password Credentials flow.  I pass the scope 'openid email profile' , but I don't get an id_token in the response. I don't believe this authorization server supports OIDC for this particular flow.  It just responds with bearer token. 

```
{
    "access_token": "opaque token, not JWT",
    "expires_in": 36000,
    "token_type": "Bearer",
    "scope": "openid profile email",
    "refresh_token": "opaque token, not JWT"
}
```

I was wondering if [this line](https://github.com/authts/oidc-client-ts/blob/f64cfb3d7dd43954c33b771727caa54c863bcec9/src/SigninResponse.ts#L77) should be 
```
return this.scope?.split(" ").includes(OidcScope) && !!this.id_token;
```
instead of 
```
return this.scope?.split(" ").includes(OidcScope) || !!this.id_token;
```

so if an id_token is not present it won't try to parse it at https://github.com/authts/oidc-client-ts/blob/f64cfb3d7dd43954c33b771727caa54c863bcec9/src/ResponseValidator.ts#L54

**Comment by pamapa** [comment]
You will need to fix the if: `if (response.isOpenId && !!response.id_token) {`, like is done e.g. here: https://github.com/authts/oidc-client-ts/blob/759079bc097048846963e9f2ca41bad9b1daf414/src/ResponseValidator.ts#L74

**Comment by dopry** [comment]
Will do.
