### ISSUE TITLE
UserProfile additional claims from IDP

### ISSUE THREAD

**Issue by OneCyrus** [authts/oidc-client-ts#125]
the returned token from our IdP includes some additional claims like client_id and name. the current implementation has a strict UserProfile interface which doesn't allow to access this data.

It would be great to access additional claims. May be we could have a generic way to access them through an extended UserProfile type.

**Comment by pamapa** [comment]
good point, feel free to provide a merge request.
claims which are in the OAuth/OIDC standard should be easy accessible...
