### ISSUE TITLE
Allow extraTokenParams in UserManager.signinSilent()

### ISSUE THREAD

**Issue by MathiasRossen** [authts/oidc-client-ts#1257]
I have a problem with not being able to put any extra params with signinSilent.

I have studied the code and it seems that most params are disregarded, when using refreshToken.

In our authorization flow I have to specify which context I am currently using, which is done by sending extra parameters with the refresh_token. For example if I want to change which organization I am currently representing, I will put in `{ organization_id: ... }` in which the authorization endpoint will return an id token with extra keys representing this: `{ ..., context: { organization_id: "123" } }`.

This was possible in the oidc-client-js library by calling `signinSilent({ organization_id: "123" })`.

I have forked this library and have made modifications to suit this need, and I am willing to make a pull request with these changes. 

EDIT: I have made a [pull request](https://github.com/authts/oidc-client-ts/pull/1258) for this issue

**Comment by pamapa** [comment]
Yes its possible, please provide a merge request based on the v2 branch (https://github.com/authts/oidc-client-ts/tree/release/v2) with this changes.
