### ISSUE TITLE
Question about monitorSession

### ISSUE THREAD

**Issue by eriCCsan** [authts/oidc-client-ts#1303]
Hi i experiment with this package and it works greate so far but i have just one question. I tun on monitorSession and it raised events. Which works correctly. But i want to catch this events. I've tried the usermanager but it still raised errors on my events.
This is my current test:
1. i log in 
2. token is stored
3. i delete the token by cleared to storage of my browser
4. monitorSession raised a event **but which event?**

This is my current error i can't work with 
```
Warning: Cannot update a component (`AuthProvider`) while rendering a different component (`ProtectedRoute`). To locate the bad
```

This use case of deleting storage is really important for me. i need do deal with it without having triggering errors into the browsers console. 
This is my small code example:

```
const oidcConfig = {
  authority: 'http://localhost:8080/realms/my_realm',
  client_id: 'frontend',
  redirect_uri: 'http://localhost:5173',
  userStore: new WebStorageStateStore({ store: window.localStorage }),
  monitorSession: true,
  automaticSilentRenew: true
}

const onSigninCallback = (_user: User | void): void => {
  window.history.replaceState({}, document.title, window.location.pathname)
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <AuthProvider {...oidcConfig} onSigninCallback={onSigninCallback}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </AuthProvider>
  </React.StrictMode>
)
```

```
const AppRouter = () => {
  return (
    <Routes>
      <Route path="/" element={<ProtectedRoute><Home /></ProtectedRoute>} />
      <Route path="/register" element={<ProtectedRoute><Registering /></ProtectedRoute>} />
    </Routes>
  )
}

export default AppRouter
```

```
const ProtectedRoute = ({ children }: any) => {
  const auth = useAuth()

  useEffect(() => {
    return auth.events.addUserSignedOut(() => {
      auth.signinRedirect()
    })
  }, [auth.events])

  if (!auth.isAuthenticated && !auth.isLoading) {
    auth.signinRedirect()
    return null
  }
  
  return children
}

export default ProtectedRoute
```

Thanks for any reply on this. :)

**Comment by pamapa** [comment]
The events the session monitor raises can be seen in the implementation code (`events._raiseUserSignedIn`, `events._raiseUserSignedOut` and `events._raiseUserSessionChanged`):
https://github.com/authts/oidc-client-ts/blob/94c3bdc5580ec02121dd47e5209a8dced54b2fca/src/SessionMonitor.ts#L139-L178

**Comment by eriCCsan** [comment]
Thanks a lot. I've implemented the events and they work. 
I also changed the position of my if-clause. Now it works without any warning.

```
import { useEffect } from 'react'
import { useAuth } from 'react-oidc-context'

const ProtectedRoute = ({ children }: any) => {
  const auth = useAuth()

  useEffect(() => {
    if (!auth.isAuthenticated && !auth.isLoading) {
      auth.signinRedirect()
    }

    return auth.events.addUserSignedOut(() => {
      auth.signinRedirect()
    })
  }, [auth.events])

  return children
}

export default ProtectedRoute
`
``

**Comment by eriCCsan** [comment]
so works like expected now thanks again

**Comment by pamapa** [comment]
About protected routes, i have implemented something **untested** here: https://github.com/authts/react-oidc-context/pull/1060. Would that work for you?

**Comment by eriCCsan** [comment]
> About protected routes, i have implemented something **untested** here: [authts/react-oidc-context#1060](https://github.com/authts/react-oidc-context/pull/1060). Would that work for you?

this looks very cool.  unfort. i cant test it now.

**Comment by eriCCsan** [comment]
@pamapa i have tested withAuthenticationRequired and it works very good. i just have have one more question regarding your feature.
I can see in the `SigninRedirectArgs` a `CreateSigninRequestArgs` and thats very intressting for me.
Because a user should get redirect via redirect_uri to the url he or she opens but was redirected due to missing login. I tried but wasn't able to solve this. How can i redirect the user back to the origin url/route and not the basic route.
I have tried many ways nothing solved my problems very well.
Thanks for any replay so far :)

i currently use this by wrapping my `AppRouter` 

```
export default withAuthenticationRequired(AppRouter, {
  OnRedirecting: () => <div>Redirecting to the login page...</div>
})
```

 As config in my`AuthProvider` i do this:
```
const oidcConfig = {
  authority: 'http://localhost:8081/realms/ttp',
  client_id: 'frontend',
  redirect_uri: 'http://localhost:5173',
  disablePKCE: false,
  userStore: new WebStorageStateStore({ store: window.localStorage }),
  monitorSession: true,
  monitorAnonymousSession: false,
  automaticSilentRenew: true,
  checkSessionIntervalInSeconds: 1,
  revokeTokensOnSignout: true,
}

...

const onSigninCallback = (_user: User | void): void => {
  window.history.replaceState({}, document.title, window.location.pathname)
}

...

<AuthProvider {...oidcConfig} onSigninCallback={onSigninCallback}>
...
</AuthProvider>
```

**Comment by pamapa** [comment]
To be able to route back to the original path (before the signin-in) after the sign-in i use the following pattern:
- start sign-in:
   ````ts
   setPreviousPath();
   await auth.clearStaleState();
   await auth.signinRedirect();
   ```
- after sigin-in in `onSigninCallback`:
  ```ts
  // go to previous location
  const prevPath = getPreviousPath();
  window.location.replace(prevPath);
  ```

setPreviousPath/getPreviousPath i use something like this by using `window.sessionStorage` to temporary store the original path (before the signin-in):
```ts
setPreviousPath(): void {
  const prevPath = window.location.pathname + window.location.search + window.location.hash;
  if (prevPath.startsWith(_config.redirectUrl)) {
    return;
  }
  window.sessionStorage.setItem(_config.previousPathStorageKey, prevPath);
}

getPreviousPath(): string {
  const prevPath = window.sessionStorage.getItem(_config.previousPathStorageKey);
  window.sessionStorage.removeItem(_config.previousPathStorageKey);
  return prevPath || _config.publicUrl || "/";
}
```

**Comment by eriCCsan** [comment]
Thank you very much for this solution. 
I think i will improve mine based on yours which looks currently this. I simply wrapped the router :) 
I close this. Thanks for the quick response! 
```
const oidcConfig = {
...
}

const onSigninCallback = (_user: User | void): void => {
  window.history.replaceState({}, document.title, window.location.pathname)
}

const WrappedRouter = (): JSX.Element => (
  <BrowserRouter>
    <AppRouter />
  </BrowserRouter>
)

const WrappedComponent = withAuthenticationRequired(WrappedRouter, {
  signinRedirectArgs: {
    redirect_uri: window.location.origin + window.location.pathname
  }
})

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <AuthProvider {...oidcConfig} onSigninCallback={onSigninCallback}>
      <WrappedComponent />
    </AuthProvider>
  </React.StrictMode>
)
```
