### ISSUE TITLE
Question: access token renewed event

### ISSUE THREAD

**Issue by GOVYANSONG** [authts/oidc-client-ts#1304]
I would like to know if there is an event raised when access token is renewed either silent renewal or manually triggered. thanks

**Comment by pamapa** [comment]
See https://github.com/authts/oidc-client-ts/blob/94c3bdc5580ec02121dd47e5209a8dced54b2fca/src/UserManagerEvents.ts#L62-L67

**Comment by GOVYANSONG** [comment]
@pamapa thanks for the info. I would never have thought to listen to User_Loaded event for access token renewed. cheers.
