### ISSUE TITLE
How to set client_authentication?

### ISSUE THREAD

**Issue by fpue** [authts/oidc-client-ts#1310]
According to the [docs](https://authts.github.io/oidc-client-ts/interfaces/UserManagerSettings.html#client_authentication) I can set the client_authentication value of either to 'client_secret_post' or 'client_secret_basic'

But if I set it in  
```typescript
const settings = { 
[...]
client_authentication: 'client_secret_basic'
[...]
}
this.userManager = new UserManager(settings);
```

The last line throws the following error: "Type 'string' is not assignable to type '"client_secret_basic" | "client_secret_post" | undefined'.ts(2345)" 

How do I fix this?

**Comment by pamapa** [comment]
I guess the problem is the type of settings, which you did not add. Does `const settings: UserManagerSettings = {...}` help?

**Comment by fpue** [comment]
That solved it, thank you for the fast response!
