### ISSUE TITLE
Question: redirect urls point to react routes instead of static html

### ISSUE THREAD

**Issue by GOVYANSONG** [authts/oidc-client-ts#1311]
I can follow the example with static html pages as redirect url. is it possible to redirect to react routes instead e.g. for redirect_uri, silent_redirect_uri and post_logout_redirect_uri. this way, all logic exists on client side and there is no server side configuration.

**Comment by GOVYANSONG** [comment]
Not sure I am on the right track. just checked doc for UserManager. the method signinredirectcallback and signoutredirectcallback can be used along with react router Navigate to target react route on client side. What about silent renew? is there a similar method or should I listen to user_loaded event etc.

**Comment by pamapa** [comment]
> I can follow the example with static html pages as redirect url. is it possible to redirect to react routes instead e.g. for redirect_uri, silent_redirect_uri and post_logout_redirect_uri. this way, all logic exists on client side and there is no server side configuration.

Yes the simple Angular sample is using static html pages for redirects, which is not as powerful as when using the same javascript application code. However you are free to decide, this library supports both. When using react please have a look at the other library, which already does this: https://github.com/authts/react-oidc-context
