### ISSUE TITLE
Eventing does not properly support async?

### ISSUE THREAD

**Issue by dgioulakis** [authts/oidc-client-ts#1312]
I noticed that I cannot rely on the eventing system to guarantee callbacks are executed to completion.

Event.ts

`export type Callback<EventType extends unknown[]> = (...ev: EventType) => (Promise<void> | void);`

It's odd that the callback type explicitly allows for `Promise<void>` return types but the `raise()` func makes no effort to check if the result is a Promise to await it.

```
public raise(...ev: EventType): void {
    this._logger.debug("raise:", ...ev);
    for (const cb of this._callbacks) {
        void cb(...ev);
    }
}
```

Why not change `raise()` to return a `Promise<void>`. I haven't looked deeply, but all places I've seen events being raised occur within an async-compatible call locations. Perhaps I need to dig further though.

In practice thus far, I've only found this to be problematic while executing a relying-party single logout flow (ie. /endsession). Before the OIDC library redirects to this endpoint, I'm trying to stop services/timers/event bindings and optionally provide our product teams the ability to run their own clean-up code or call whatever api's they need.

The library currently gets through a portion of the callbacks, but it's nondeterministic since nothing is waiting for completion of these callbacks - usually the redirect happens before the continuations have run.

**Comment by dgioulakis** [comment]
Starting looking through the codebase more. This would definitely be a large PR and would also have to add support for async setInterval. Not sure how beneficial this would be to others. For now I can build a workaround without relying on the event system.

**Comment by pamapa** [comment]
We have two options:

A: Make remove Promise, i added it first hand, because of SessionMonitor: `this._userManager.events.addUserLoaded(this._start)`, but that could be written differently. On the other hand its looks like others code also like to have a promise here. So lets keep this.

B: keep the Promise, i guess the raise called in `setInterval` is not your problem, but all the other calls of raise.
see #1313
