### ISSUE TITLE
Use npm distribution tags for upcoming releases

### ISSUE THREAD

**Issue by pschaub** [authts/oidc-client-ts#1316]
### Summary
I recently encountered some confusion with our project dependencies listed under `npm outdated`. The confusion stemmed from the inability to distinguish between stable and beta versions. To address this and improve clarity for developers, I propose the adoption of NPM distribution tags.

```sh
$ npm outdated
Package                           Current   Wanted        Latest 
oidc-client-ts                      2.4.0    2.4.0    3.0.0-rc.0
```

### Proposal
Implement the use of npm distribution tags, specifically tags like "latest" for stable releases and "beta" or "next" for pre-release versions.

### Why It's Needed
In enterprise environments, stability is paramount. Without clear distinction between stable and beta releases, there's a risk of inadvertently upgrading to a less stable version, potentially introducing bugs or compatibility issues.

Using npm distribution tags would ensure that commands like `npm update` or `npm outdated` reflect the intended usage of the package versions. Developers would easily identify the stability of each version and could avoid updating to a beta release in a production environment.

For more information on NPM distribution tags and their importance in release management, please refer to the official NPM documentation: [Managing Package Distribution Tags](https://docs.npmjs.com/cli/v8/commands/npm-dist-tag).

### Conclusion
Adopting this practice would greatly enhance the developer experience and maintain the integrity of stable projects.

**Comment by pamapa** [comment]
Good point, i have now manually set the latest version. The correct solution is the fix the gitlab workflow action. Depending on the github "latest" flag it should propagate this to the npm reqistery. No idea yet how to achieve that, if somebody knows lets me know...

**Comment by pamapa** [comment]
Probably something like https://github.com/orgs/community/discussions/26281#discussioncomment-3251177:

```
- if: "github.event.release.prerelease"
  run: npm publish --tag beta
- if: "!github.event.release.prerelease"
  run: npm publish --tag latest
```
