### ISSUE TITLE
Missing `realm_access` claim in UserProfile

### ISSUE THREAD

**Issue by alessiomatricardi** [authts/oidc-client-ts#1333]
Hi, I actually have a JWT in which is declared the claim `realm_access`, used by Keycloak to store the user role inside the realm
![Screenshot from 2024-01-08 15-08-06](https://github.com/authts/oidc-client-ts/assets/26736913/7957e331-0088-41e9-af40-d16fc9921187)

But, the declared type UserProfile doesn't seem to have this field.
As for now, I can get the list of roles as below:
![image](https://github.com/authts/oidc-client-ts/assets/26736913/23e45249-0348-4e29-88d0-39c01b2106af)

But not sure about this porkaround. Let me know if it's a bug or a desired behaviour.

**Comment by pamapa** [comment]
We only support standardized oidc claims. Others you can access like `profile["realm_access"]` or like you did it...

**Comment by alessiomatricardi** [comment]
> We only support standardized oidc claims. Others you can access like `profile["realm_access"]` or like you did it...

Thanks! Clearly my error, I thought was a standard one.
