### ISSUE TITLE
`UserManager.events().unload()` event is triggered too early on `UserManager.signoutRedirect()`

### ISSUE THREAD

**Issue by PSanetra** [authts/oidc-client-ts#1341]
We observed the `UserManager.events().unload()` event was fired too early, before the user was actually signed out. Our application reacted with a redirect to the login page to this event, but as there was the possibilty of a race condition between login redirect and actual signout, the signout might not yet have happened and therefore resulted in an unsuccessful signout.

The problematic code is located in `UserManager._signoutStart()`, which is called from `UserManager.signoutRedirect()`:

https://github.com/authts/oidc-client-ts/blob/4a8d6d922690077d4edbc86cfe1af363c7b9414c/src/UserManager.ts#L623-L624

I would expect this code instead to be located in `UserManager._signoutEnd()` where it should be guaranteed that the user was successfully signed out.

I will create a PR to fix this issue.

**Comment by pamapa** [comment]
I see your point, makes sense, thanks for taking care...

**Comment by PSanetra** [comment]
| Why do you react with a redirect to login page

As far I know I need to react to the user unload event as also other reasons like session timeout might lead to a user unload event. In all these cases I want to show the login page to the user as the actual application is only intended for users which are logged in.

**Comment by PSanetra** [comment]
@pamapa Actually our application does not depend directly on that event, but it depends on reacting to `AuthState.isAuthenticated`, which is returned from the `useAuth()` hook in the `react-oidc-context` which is also maintained by the `authts` organization:
https://github.com/authts/react-oidc-context/blob/4deb6591910ef9bed996ea4cf0faa37d579305f5/src/reducer.ts#L28-L33

How do you suggest to react to a change of the `isAuthenticated` state when the user is actually still authenticated?

**Comment by pamapa** [comment]
> How do you suggest to react to a change of the `isAuthenticated` state when the user is actually still authenticated?

Locally he is no longer as we have remove the user object locally, but on the IDP the user still has for a very short time a valid session. But that session is now useless, as the local tokens are gone.

Can you post the code of what you are doing in the !isAuthenticated  case?

**Comment by PSanetra** [comment]
@pamapa It looks like this:

```typescript
  const { isAuthenticated, isLoading } = useAuth();
  const login = () =>
    signinRedirect({
      scope: 'openid',
      redirect_uri: myRedirectUri
    });

  // automatically sign-in
  React.useEffect(() => {
    if (!isAuthenticated && !isLoading) {
      void login();
    }
  }, [isAuthenticated, isLoading]);
```
(I removed a little clutter, but this is generally the logic.)

The same code is also triggered when the user opens the page but is not yet logged in.

**Comment by pamapa** [comment]
Have you see https://github.com/authts/react-oidc-context?tab=readme-ov-file#automatic-sign-in, there is more to add...

**Comment by PSanetra** [comment]
Yes sorry. That activeNavigator was there in the actual code, but I removed it here as I thought it was not important for this case.

Regarding retry preventing: I am not sure why it would make a difference as the issue is that `signinRedirect()` is getting called too early, but the only thing `hasTriedSignin` does, is to prevent to calling `signingRedirect()` a second time after it has already been called. In my case the first time is already a problem.

**Comment by PSanetra** [comment]
fyi: For us using `react-oidc-context` the bug seems to be only reproducible when `signoutRedirect()` is called from a react `useEffect()` context. When `signoutRedirect()` is called from a click-event-handler, the bug does not seem to be reproducible. I think in the click-event-handler case the bug is just not triggered, because of some react internals. (Maybe rerenderings are generally deferred in click-event-handler contexts.)

**Comment by pamapa** [comment]
> yi: For us using `react-oidc-context` the bug seems to be only reproducible when `signoutRedirect()` is called from a react `useEffect()` context. When `signoutRedirect()` is called from a click-event-handler, the bug does not seem to be reproducible. I think in the click-event-handler case the bug is just not triggered, because of some react internals. (Maybe rerenderings are generally deferred in click-event-handler contexts.)

Good to hear, i just temporary added `automatically sign-in` to one of my apps and it works.
Also notice that you can defer in react operations with `queueMicrotask` or force immediate execution with `ReactDOM.flushSync`.
I will add a notice in `react-oidc-context`...
