### ISSUE TITLE
Id_token signature isn't validated.

### ISSUE THREAD

**Issue by pvancelette** [authts/oidc-client-ts#1355]
I'm using the authorization_code flow.  I've noticed that the jwks enpoint isn't called to get the keys to verify the id_token signature.  I see a mehtod in the MetadataService called getSigningKeys but it isn't called.  Am I missing something?

**Comment by pamapa** [comment]
That is by design, its simply not needed. In the past, when supporting the `implicit grant`, this step was needed to avoid potential man in the middle attacks. The `implicit grant` has been removed from this library (v2.0.0).

**Comment by pvancelette** [comment]
Ok good to know.  Thanks for the quick reply!
