### ISSUE TITLE
heap memory grows over iterations of silent signin

### ISSUE THREAD

**Issue by jeffschulzusc** [authts/oidc-client-ts#138]
if i repeatedly do silent sign-in, for example un-authenticated (result in login_required) (keep pressing renew button in angular app) ... then the **heap grows** and the source keeps adding silent-callback.html instances ...

see screen shots 

after investigation, it seems that if i make a change to I**FrameWindow.navigate** to **appendChild AFTER set the iframe.src**, then the GC can reclaim this heap and the silent-callback.html instances are removed ... however i can not explain why ... looking for help to 
understand what is happening here 

this **heap leak** needs to be fixed especially for spa sites

i made a fork with changes jeffschulzusc / oidc-client-ts

![Screen Shot 2021-10-15 at 9 03 02 AM](https://user-images.githubusercontent.com/91924637/137541873-c5439b76-3c78-43e3-b2bf-298336004b78.png)

![Screen Shot 2021-10-15 at 9 02 44 AM](https://user-images.githubusercontent.com/91924637/137541883-008bb4a3-3db9-43da-9766-b9e5ca2339ec.png)

**Comment by pamapa** [comment]
thanks for reporting, we will have a look at it. for others who want to see his changes see [here](https://github.com/jeffschulzusc/oidc-client-ts/commit/41e6c99e401c6eff424199e695454f1eab394ec6#diff-891ae6e72b63994c1355fc726cf3cfc98eaf573d589d56d150391f366a95edefL40).

**Comment by pamapa** [comment]
IFrameWindow.close() seems not to be called in the success case, only in the error case...

**Comment by jeffschulzusc** [comment]
i put fix for this on my fork:
https://github.com/jeffschulzusc/oidc-client-ts/pull/2

**Comment by brockallen** [comment]
> @brockallen any insights ? :)

Oh sorry -- missed this. No, sorry. No idea.

**Comment by pamapa** [comment]
angular sample code has now been move ouside. Also i have seen that the current sample still uses oidc-client and not oidc-client-ts. At first to be 100% sure we need to port it...
See relevant issue: https://github.com/authts/sample-angular-oidc-client-ts/issues/1

**Comment by jeffschulzusc** [comment]
the fix is in src/navigators/IFrameWindow ... 
could we make a fix branch and i can make the change and do PR or ? :)

**Comment by pamapa** [comment]
would be really cool if you could bring first the sample up to date. see https://github.com/authts/sample-angular-oidc-client-ts/issues/1. E.g. instead of signin-callback.html + silent-callback.html angular routing should be used + we need to switch from oidc-client-js to oidc-client-ts all over.

Like this, others can verify your fix in a clean environment....

**Comment by jeffschulzusc** [comment]
sounds good, will do

**Comment by kherock** [comment]
I've rewritten the `IFrameWindow` implementation over in #194 and it no longer resets `.src` after appending. It's now using `.contentWindow.location.replace` to navigate the iframe. Based on the findings above, I'm hopeful that this approach will also also resolve the leak.

**Comment by jeffschulzusc** [comment]
i will test this thanks

**Comment by jeffschulzusc** [comment]
im not sure what might be a solution if using _contentWindow.location.replace_ ... i will have another go at it

**Comment by kherock** [comment]
@pamapa When I take a heap snapshot it'll usually show 4 `HTMLIFrameElement`s on a fresh page load. When I take a second snapshot after running the sign in silent procedure, it'll allocate an additional 6 `HTMLIFrameElement`s. Every snapshot I take after that doesn't increase the number shown in the first two snapshots. I'm not really sure how to interpret that data.
 
However, I do have a potential workaround for all of the orphaned `signin-callback.html` screens showing in the sources panel - I've discovered that setting the `src` to `about:blank` and waiting a short while (10ms or so) before removing the iframe from DOM will consistently allow the page to unload its sources. I'll see if it's possible to do this with an event listener instead.
