### ISSUE TITLE
generate docu from source

### ISSUE THREAD

**Issue by pamapa** [authts/oidc-client-ts#15]
by using e.g. typedoc or https://docusaurus.io

initial docu can be taken from old wiki:
https://github.com/IdentityModel/oidc-client-js/wiki

**Comment by rvdkooy** [comment]
I noticed you started with setting up docusaurus, but what about api docs based on the source code? 
you want to combine that or use separate typedoc pages?

I could help with this if you want

R

**Comment by pamapa** [comment]
this is done
