### ISSUE TITLE
Typo in sample app config

### ISSUE THREAD

**Issue by lucaslb1** [authts/oidc-client-ts#1501]
In samples/Parcel/.proxyrc.js 
 it should be 
`
app.use(
        "/oidc/",
        createProxyMiddleware({
            target: "http://localhost:15000/",
        })
    );
`

not 
`
app.use(
        createProxyMiddleware("/oidc/", {
            target: "http://localhost:15000/",
        })
    );
`
as it currently is.
This is causing the error `[0] Error: [HPM] Missing "target" option. Example: {target: "http://www.example.org"}` to be thrown by http-proxy-middleware when trying to run the sample app.

To reproduce 
cd samples/Parcel
npm install
npm run start

Wasn't sure how to create a new branch for a pull request.

**Comment by pamapa** [comment]
thanks for reporting
