### ISSUE TITLE
Possibility of making the jwt signature verification configurable?

### ISSUE THREAD

**Issue by TomCaserta** [authts/oidc-client-ts#151]
By far the largest part of this library right now is `jsrsassign' but I don't think it really needs to be. The problem with jsrsassign is that it doesn't lend itself to treeshaking.

For example, angular oidc client is utilising:

https://www.npmjs.com/package/jsrsasign-reduced

Which contains only the methods needed to actually verify the token. It's still a large 140kb bundle but it's way better than the 200-300kb we have now. 

Auth0 went in a slightly different direction with https://www.npmjs.com/package/idtoken-verifier which only supports RS256 tokens however it is 14kb minified + gzipped which is a massive improvement.

I presume you can't really dictate that in this library as it needs to be somewhat generic so my suggestion is to effectively allow the `verify` method to be implemented by the library consumer and perhaps include the current functionality in a separate entry point so it can be tree-shaken if a user decides not to use it.

**Comment by pamapa** [comment]
Lets try to keep it simple and only support one crypto library. I am open to change `jsrsassign` with something smaller or something that supports treeshaking. The crypto library must be actively supported by multiple maintainers and used by a lot of other projects...

I guess we cannot use `idtoken-verifier`, as we can not control which algorithm the different authorities will use.

According to this site
https://www.npmtrends.com/crypto-js-vs-jsrsasign-vs-jsrsasign-reduced

`crypto-js` would be the winner, however its does not directly support JWT. On the other hand we do not need much, mainly parsing and validating if the signature is good.

**Comment by pamapa** [comment]
This library looks also promising:
https://www.npmjs.com/package/jose

Its getting used quite a lot nowadays
https://www.npmtrends.com/jose-vs-jsrsasign-vs-jsrsasign-reduced

**Comment by brockallen** [comment]
I'd argue that you should remove implicit flow support all together, as it's a deprecated flow in OAuth. This would then allow you to remove all JWT signature checks and it would allow for the library to be much smaller.

**Comment by pamapa** [comment]
@brockallen good to have you on board :-) I fully agree with you. Lets drop the implicit flow and keep the library lightweight and best practise. Specifically the upcoming OAuth2.1 will drop the implicit flow too (https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-04).
