### ISSUE TITLE
Feature request for OAuth2.1 client authentication methods

### ISSUE THREAD

**Issue by ch-lepp** [authts/oidc-client-ts#1533]
The OAuth2.1 spec does not require but strongly recommends asymmetric client authentication methods like "private_key_jwt" ([source](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-01#name-client-authentication)).
In your documentation for your OidcMetadata interface you even hint towards the support of "private_key_jwt" with the attributes [token_endpoint_auth_methods_supported](https://authts.github.io/oidc-client-ts/interfaces/OidcMetadata.html#token_endpoint_auth_methods_supported) and [token_endpoint_auth_signing_alg_values_supported](https://authts.github.io/oidc-client-ts/interfaces/OidcMetadata.html#token_endpoint_auth_signing_alg_values_supported).

But for the attribute [client_authentication](https://authts.github.io/oidc-client-ts/interfaces/OidcClientSettings.html#client_authentication) within the OidcClientSettings interface you only support "client_secret_basic"  and "client_secret_post" ([as can bee seen in the code aswell](https://github.com/authts/oidc-client-ts/blob/1cc595e52514a6f1b31559b1e197ab656c009be5/src/OidcClientSettings.ts#L163C44-L163C88)).

Could you please add support for the OAuth2.1 recommended client auth methods?

**Comment by dbfr3qs** [comment]
The OAuth 2.1 spec is not even in RFC yet and is still under active development. I would suggest we wait until the RFC is ratified.

**Comment by ch-lepp** [comment]
I see your point and I would usually agree.

I just have the problem, that we use Keycloak in our setup as IDP.
With version 24 Keycloak started support of OAuth2.1, which I'd like to use. Unfortunately, [Keycloak requires all OAuth2.1-Clients to use either "private_key_jwt" or "x509 certificate"](https://github.com/keycloak/keycloak/issues/30140).

And while OAuth2.1 is indeed still a draft, [the "private_key_jwt" auth method itself is part of the OIDC core spec](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication).

**Comment by dbfr3qs** [comment]
Okay, no problem - I see that you are correct that it is referenced in the OIDC core spec.

Given that `oidc-client-ts` supports public clients, it seems like a strange use case for web based applications. How would one securely supply the private key?

Say the key pair is registered when registering the client, the public key is stored at the IdP and the client is then expected to make use of the private key to sign the JWT to authenticate at the /token endpoint. Is that private key embedded into the application's javascript? The moment the private key enters the browser's execution environment, it's no longer a private key. 

I see in the linked KeyCloak issue that you are using a confidential client. Can I ask how you are using `oidc-client-ts` in this case?

**Comment by ch-lepp** [comment]
> Given that oidc-client-ts supports public clients, it seems like a strange use case for web based applications. How would one securely supply the private key?

The same problem already exists for the client secret, does it not?
The client secret also needs to be securely provided to the client...

At the moment, `oidc-client-ts` offers to [simply pass the client secret as an attribute of the OidcClientSettings](https://authts.github.io/oidc-client-ts/classes/OidcClientSettingsStore.html#client_secret).
I think the same should be possible for the private key.

However, it is currently possible to configure `oidc-client-ts` to use `client-secret-post` without providing the client secret as part of the OidcClientSettings aswell.
This way, the client secret can be provided in a more secure way, without adding it to the application's javascript.

E.g. the team I work for build an app that uses a ts frontend in front of a java spring-boot backend.
Our frontend send the token request not to the idp directly, but to our backend. Here the client secret is injected into the request before it is forwarded towards the idp.
We plan to use a similar approach for the signed jwt.

**Comment by dbfr3qs** [comment]
@pamapa what do you think? It's a no from me as this seems like a use case well outside of any of the specs or the current  [BCP](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps).

As an aside we should not support client secret. That looks like a holdover from the original port (which is years out of date at this point).

>Secrets that are statically included as part of an app distributed to multiple users should not be treated as confidential secrets, as one user may inspect their copy and learn the shared secret. For this reason, and those stated in Section 5.3.1 of [[RFC6819](https://www.rfc-editor.org/info/rfc6819)], it is NOT RECOMMENDED for authorization servers to require client authentication of browser-based applications using a shared secret, as this serves no value beyond client identification which is already provided by the client_id parameter.

**Comment by pamapa** [comment]
> what do you think? It's a no from me as this seems like a use case well outside of any of the specs or the current [BCP](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps).
> 
> As an aside we should not support client secret. That looks like a holdover from the original port (which is years out of date at this point).

I agree that it is very very bad to use client secrets in applications exposed to users (e.g. web applications or smartphone applications). But there exists also applications using nodejs and running servers (back-end application). They do not expose any code to users. for those it should be safe to use client secrets...

**Comment by dbfr3qs** [comment]
> > what do you think? It's a no from me as this seems like a use case well outside of any of the specs or the current [BCP](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps).
> > As an aside we should not support client secret. That looks like a holdover from the original port (which is years out of date at this point).
> 
> I agree that it is very very bad to use client secrets in applications exposed to users (e.g. web applications or smartphone applications). But there exists also applications using nodejs and running servers (back-end application). They do not expose any code to users. for those it should be safe to use client secrets...

Yes, but in that I case I would use a library like [opened-client](https://github.com/panva/node-openid-client) which is designed for that use case - not `oidc-client-ts`. Are you saying we can support this use case in `oidc-client-ts`?

**Comment by ch-lepp** [comment]
Please do not drop support for `client-secret-post` ^^

I actually found a solution for my usecase without changing your oidc-client-ts code.

I continue to use this library with the `client_authentication` settings unchanged (meaning they default to `client-secret-post` as they currently do).
When sending the token request, the oidc-client-ts only ever sends a `client_secret` param if an actual secret is provied in the `UserManagerSettings`.

I always left the secret empty in the `UserManagerSettings` because (as I described [here](https://github.com/authts/oidc-client-ts/issues/1533#issuecomment-2193955973)) the token request is first sent to our backend where the secret gets injected.

I now changed our backend code in a way, that it injects a signed JWT instead of a client secret into the token request.
And that works absolutely fine.

So this issue/feature-request can be closed.
Thanks a lot @dbfr3qs and @pamapa for having this discussion with me.
