### ISSUE TITLE
[question] Frequent token refreshes

### ISSUE THREAD

**Issue by splatch** [authts/oidc-client-ts#1542]
Hello,
Thank you very much for great library, it helped me to integrate oidc server with little effort.

As I succeeded getting user session (with react-oidc-context) now I am tracking remaining improvements. As for now, I've found that library with basic setup perform token refresh every second (or so), despite of 60s expiry window set by server.
User manager I have have just few parameters:
```js
const redirectUri = new URL(window.location.href);

const manager = new UserManager({
  authority: window.location.protocol + '//' + window.location.host +'/realms/master',
  redirect_uri: new URL('/callback', redirectUri).toString(),
  client_id: 'ui',
  userStore: new WebStorageStateStore(),
})
```

My server response is:
```json
"access_token":  "...",
"expires_in": 60,
"id_token":  "...",
"refresh_token":  "...",
"refresh_expires_in": 1800
```
The clock skew is unlikely to take place, because its all happening at localhost.

I've added two listeners to `UserManager`:
```js
const time = (val) => {
  if (val !== undefined) {
    return dayjs.unix(val).toISOString();
  }
  return dayjs().toISOString()
}

manager.events.addAccessTokenExpiring(() => {
  console.log(time() + ' token expiring')
})
manager.events.addUserLoaded((u) => {
  console.log(time() + ' user loaded, will expire at ' + time(u.expires_at))
})
```
Above listeners result in following console output:
```
main.jsx:69 2024-06-13T17:03:59.087Z user loaded, will expire at 2024-06-13T17:04:59.000Z
main.jsx:66 2024-06-13T17:03:59.087Z token expiring
main.jsx:69 2024-06-13T17:04:00.097Z user loaded, will expire at 2024-06-13T17:05:00.000Z
main.jsx:66 2024-06-13T17:04:00.097Z token expiring
```

I am not sure if I miss some basic setting or parameter to user manager?

**Comment by zach-betz-hln** [comment]
Hi @splatch - in your identity provider response, would also confirm the `exp` field of the `access_token`, just in case something is off with that.

**Comment by splatch** [comment]
@zach-betz-hln I've updated user loaded callback to:
```
manager.events.addUserLoaded((u) => {
  const accessToken = jwtDecode(u.access_token);
  console.log(time() + ' user loaded, will expire at ' + time(u.expires_at) + ' token expiry: ' + time(accessToken?.exp || 0) + ' current time: ' + new Date())
})
```
This prints following:
```
2024-06-14T20:25:41.191Z user loaded, will expire at 2024-06-14T20:26:41.000Z token expiry: 2024-06-14T20:26:41.000Z current time: Fri Jun 14 2024 22:25:41 GMT+0200 (Central European Summer Time)
2024-06-14T20:25:41.191Z token expiring
2024-06-14T20:25:42.240Z user loaded, will expire at 2024-06-14T20:26:42.000Z token expiry: 2024-06-14T20:26:42.000Z current time: Fri Jun 14 2024 22:25:42 GMT+0200 (Central European Summer Time)
2024-06-14T20:25:42.240Z token expiring
```

**Comment by zach-betz-hln** [comment]
Here's what I _think_ is happening:

- Your token is only valid for 60s
- Per the docs on [accessTokenExpiringNotificationTimeInSeconds](https://authts.github.io/oidc-client-ts/interfaces/UserManagerSettings.html#accessTokenExpiringNotificationTimeInSeconds) then this event is fired 60s _before_ the token expires
- So... this is why it immediately fires in your log output

To change this, would do one of the following:

- Increase the token expiration time via the identity provider server; or
- Decrease the `accessTokenExpiringNotificationTimeInSeconds` value

**Comment by splatch** [comment]
:+1: I've set `accessTokenExpiringNotificationTimeInSeconds` to 10, I see no instant requests any more:
```
2024-06-14T20:40:09.387Z user loaded, will expire at 2024-06-14T20:41:09.000Z token expiry: 2024-06-14T20:41:09.000Z current time: Fri Jun 14 2024 22:40:09 GMT+0200 (Central European Summer Time)
2024-06-14T20:40:09.391Z token expiring
2024-06-14T20:40:59.427Z user loaded, will expire at 2024-06-14T20:41:59.000Z token expiry: 2024-06-14T20:41:59.000Z current time: Fri Jun 14 2024 22:40:59 GMT+0200 (Central European Summer Time)
2024-06-14T20:40:59.429Z token expiring
```

Given that I test with insecure (public client) I think 60s for token is fine, its just renewing which was happening to early. Thank you very much for hint and solution!
