### ISSUE TITLE
Error:  No matching state found in storage

### ISSUE THREAD

**Issue by Ploppz** [authts/oidc-client-ts#1563]
"oidc-client-ts": "^2.4.0",
Using this in a React application. The authority is Azure AD. For now just trying to make this all work on localhost. The React app runs at 127.0.0.1:8081. In the Azure manifest there is
```
	"replyUrlsWithType": [
		{
			"url": "http://127.0.0.1:8081/#/oauth2/callback",
			"type": "Spa"
		},
		{
			"url": "http://127.0.0.1:8081/oauth2/callback",
			"type": "Spa"
		},
		{
			"url": "http://127.0.0.1:8081",
			"type": "Spa"
		},
```

When I log in, and it redirects, I get the error `No matching state found in storage`. However, all functionality works well, and the Authorization Bearer token gets validated in the backend. In the URL at the time of redirect and when I see the error (yet I also see that the user is logged in and the user's role), there are these query params:
`state=fcc3e428a1e74594810c2fe8106402e7&session_state=8d165024-0987-4988-8cc6-b781793efda6`
So we do get some state in the URL.
In the local storage, we have this

key: `oidc.user:https://login.microsoftonline.com/<tenant ID>/v2.0:<client ID>`
value (formatted):

```
{
  "id_token": "<redacted",
  "session_state": "8d165024-0987-4988-8cc6-b781793efda6",
  "access_token": "<redacted>",
  "refresh_token": "<redacted>",
  "token_type": "Bearer",
  "scope": "<client id>/User.Read <client id>/.default",
  "profile": {
// redacted, several keys
  },
  "expires_at": 1719584312
}
```

I don't know how it's trying to match the `state` received in the URL, to the local storage.
If it helps here is the React implementation https://gist.github.com/Ploppz/321722baef2ce89e1422bed49b6d1761

**Comment by pamapa** [comment]
There is something special in your code. See https://github.com/authts/oidc-client-ts/issues/1487#issuecomment-2095948986

**Comment by Ploppz** [comment]
Thanks.

I tried to add logging with
```
import { Log } from 'oidc-client-ts';

function App() {
  Log.setLogger(console);
```
but it logs nothing, is that expected? (when I sign in)

well I think I'll download the library and use a local version with added console.logs to figure out what state it's trying to read that's not there

**Comment by Ploppz** [comment]
Alright, solved my problem now. I can share a series of mistakes in the hopes it might help someone in the future. Useful context is that I'm using React.

1. if you run at `localhost:8080` and the redirect uri is set to `127.0.0.1:8080/oauth2/callback` (because of constraints on the URI format I think), then you must enter your UI through `127.0.0.1:8080`. (this I already knew, but it still lead to confusion sometimes)

2. I had this code in the callback page:
```
          window.history.replaceState(
            {},
            window.document.title,
            window.location.origin + window.location.pathname
          )
 ```
This also added complications leading to "No state found in response in some cases". Turns out this work is unnecessary to do as it's dealt with automatically.

3. `userManager.current.signinRedirectCallback()` was called twice which also directly leads to the error "No matching state found in storage". It was actually not straightforward to figure out a nice way to avoid this as it has to do with component state managing by React. The short version is: *just print whenever signinRedirectCallback is called, and you'll figure it out*

In my case, I had this routing component:
```jsx
function Routes() {
  let authenticated = useAuth("Admin");
  console.log("Authenticated = " + authenticated);

  if (authenticated) {
    return <>
      // other routes...
      <Route path="/oauth2/callback" exact component={AuthCallback} />
    </>
  } else {
    return <>
      <Route path="/oauth2/callback" exact component={AuthCallback} />
      <Route path="*" component={NotAuthenticatedPage} />
    </>;
  }
}
```
Where `useAuth` is my own abstraction around userManager. After signing in and being redirected, it turns out that `authenticated` will first be `false` for a while before it switches to `true`. This makes React first render one AuthCallback component, then unmount it and create a new one when the value of `authenticated` switches. In `AuthCallback` I have a `React.useEffect` that calls `userManager.current.signinRedirectCallback()` - which will happen only once.... per component lifecycle.
