### ISSUE TITLE
replace UrlUtils with native URL and URLSearchParams

### ISSUE THREAD

**Issue by pamapa** [authts/oidc-client-ts#157]
- also replace duplicated code `url = window.location.href` in `signinRedirectCallback(url = window.location.href)` and `signoutRedirectCallback(url = window.location.href)` with `url?: string`

**Comment by kherock** [comment]
I've begun working on this - I was wondering what we should do about the *SignInResponse functions which take `url` as a parameter. They can currently handle absolute URLs, relative URLs, or plain query strings.

Real-world usage should always pass an absolute URL, but all of our test cases use a string like `"state=state"`. My preference is that we require the full return URL to be passed in with v2.

**Comment by pamapa** [comment]
This is the last jigsaw part for 2.0.0, would be cool to have it next week...

**Comment by kherock** [comment]
I'm looking at cases where we default `url = window.location.href` and I'm not sure if it's a good idea to make it optional for the public methods:

* `signinCallback`/`signoutCallback` need it to read the `state` param to determine which navigator to use
* `signinRedirectCallback`/`signinPopupCallback`/`signinSilentCallback` are all part of the public API, and these methods **require** a url to function when they call `OidcClient#readSigninResponseState`. I think the `SigninResponse`/`SignoutReponse` constructors are mistyped in that the `url` argument should be a required param. Attempting to pass an empty url in those places will inevitably lead to runtime errors.
