### ISSUE TITLE
redirect_uri: Issue with IDCS

### ISSUE THREAD

**Issue by cosmos-uk** [authts/oidc-client-ts#1602]
I'm new to oidc-client-ts and I'm facing an error while implementing Oracle Identity Cloud Service (IDCS) with it. The error message is: {"error": "invalid_redirect_uri", "error_description": "Client XXXXXX requested an invalid redirect URL: http://localhost:3000. ECID: XXXXXXXX"}. Can anyone help?

**Comment by pamapa** [comment]
Typically you must register the redirect URI on the IdP side...

**Comment by cosmos-uk** [comment]
> Typically you must register the redirect URI on the IdP side...

I realized the issue: the `redirect_uri` is being encoded when making the request, but Oracle is not decoding it.
