### ISSUE TITLE
Add event addSilentRenewSuccess when signinSilent is called and successful.

### ISSUE THREAD

**Issue by phlegx** [authts/oidc-client-ts#1711]
Hi!

The `UserManager` events include the event `addSilentRenewError`. Can an event `addSilentRenewSuccess` also be added, to get a callback if `signinSilent` function is executed successfully from `SilentRenewService`?

Maybe here: [SilentRenewService.ts#L51](https://github.com/authts/oidc-client-ts/blob/6b51d8c6c30433e87f7faac6d96767d30b30029f/src/SilentRenewService.ts#L51)

**Comment by pamapa** [comment]
There already exists such an event. See `addUserLoaded` (Raised when a user session has been established (or re-established).)

**Comment by phlegx** [comment]
Thx!
