### ISSUE TITLE
Angular 'CommonJS or AMD dependencies can cause optimization bailouts' warnings

### ISSUE THREAD

**Issue by pbklink** [authts/oidc-client-ts#242]
When trying to compile an Angular 13 application with oidc-client-ts version 2.0.0-rc.2, the following compilation warnings occur:

*Warning: C:\Dev\sample-angular-oidc-client-ts\node_modules\oidc-client-ts\dist\esm\oidc-client-ts.js depends on 'crypto-js/enc-base64.js'. CommonJS or AMD dependencies can cause optimization bailouts.*

3 of these warnings occur:
* crypto-js/enc-base64.js
* crypto-js/enc-utf8.js
* crypto-js/sha256.js

These warnings do not occur if version 2.0.0-beta.3 is used.

I have tested this with 'sample-angular-oidc-client-ts'.

[https://github.com/angular/angular-cli/issues/18025](https://github.com/angular/angular-cli/issues/18025) indicates that these warnings can be removed by using the `allowedCommonJsDependencies` option in angular.json.  However I have not yet figured out what crypto-js entry points I should use.

Any help would be appreciated.

**Comment by pamapa** [comment]
something like that [Remove CommonJS or AMD dependencies optimization bailouts warnings for AWS Amplify using Angular v10](https://gist.github.com/gsans/8982c126c4fef668c094ff288f04241b) might help?

**Comment by pbklink** [comment]
@pamapa - thanks for that.  The above link showed that all I needed to do was add "crypto-js" to `allowedCommonJsDependencies`. Was looking too hard for a complicated solution. :smiley:

Have added this fix  authts/sample-angular-oidc-client-ts#4 .
