### ISSUE TITLE
issue with imports

### ISSUE THREAD

**Issue by chris-kruining** [authts/oidc-client-ts#248]
![bug](https://user-images.githubusercontent.com/5786905/145204428-27800632-8827-4c73-b079-0c1228f8f562.png)

I keep getting this error on a fresh install.
 loading the modules as `import { SHA256, EncBase64, EncUtf8 } from 'crypto-js';` seems to fix the issue.

is this a bug? or is my setup broken?

to clarify; I use es modules to load code

**Comment by chris-kruining** [comment]
hmm, maybe not, just seems to become a warning instead of an error...

**Comment by pamapa** [comment]
Are you using Angular? if so see the sample https://github.com/authts/sample-angular-oidc-client-ts

**Comment by chris-kruining** [comment]
I'm not using a framework, but I do use rollup and ts as my toolchain. as far as I can see this is an issue with crypto-js, because if I look into the files in node_modules they aren't es modules. could that possibly be the issue?

**Comment by pamapa** [comment]
@kherock what can we do here?

**Comment by pamapa** [comment]
Does importing the type definitions @types/crypto-js help?

**Comment by kherock** [comment]
@chris-kruining you're right in noticing that `crypto-js` doesn't provide es-modules, it only exports UMD/CJS. You'll need to include `@rollup/plugin-commonjs` in your rollup config in order to resolve those imports.
