### ISSUE TITLE
create angular helper library

### ISSUE THREAD

**Issue by pamapa** [authts/oidc-client-ts#253]
- lightweight
- service with all in it but not more
- redirect helper
- comes into separate repository under authts

**Comment by pamapa** [comment]
@pbklink interested?

**Comment by pbklink** [comment]
@pamapa,

I personally do not think an Angular helper library is helpful. I think there is enough behaviour encapsulated in `oidc-client-ts`.  If you put more into an angular helper library, then, in my opinion, you are starting to put application logic into the helper library and it starts doing 'magic' that the developer should really be aware of.  For example:

* all the routes (including the signin callback) should be in the router module,
* the signin component callback component should be with other components,
* an auth related service would really only wrap functions UserManager functions and it is probably better to use a session management service with wider scope,
* it is important for developers to know that their application will start twice and structure their startup process accordingly.

What I think would be really helpful for Angular developers is:
1. Rework the Angular sample application so it reflects how a typical Angular application would use `oidc-client-ts`.\
Currently it is structured as a test application where login is manually initiated and has no guards. It should be restructured to automatically login (probably using downloaded configuration) and use guards to ensure login cannot be bypassed.  It should include error handling - including the application level error handling suggestions which come out of #251 
2. A [medium](https://medium.com/) like article stepping you through creating an Angular application which uses `oidc-client-ts`.\
This would be based on the sample Angular application above.  Such an article would probably be easily found with internet searches when the appropriate search terms are used.  I find these articles extremely helpful when learning new techniques and am very thankful that the authors created them.

While I am not interested in creating an Angular helper library, I could rework the Angular sample application as per above and start working on an article if you think that would be helpful.

**Comment by pamapa** [comment]
@pbklink i agree with you. lets go that path.

**Comment by pamapa** [comment]
For the record: The Angular sample project can be found [here](https://github.com/authts/sample-angular-oidc-client-ts).
