### ISSUE TITLE
"Window navigation aborted" event raised in an infinite loop

### ISSUE THREAD

**Issue by Badisi** [authts/oidc-client-ts#274]
When performing a `signinPopup()` a "Window navigation aborted" event will be raised indefinitely.

<img width="1049" alt="Screen Shot 2021-12-16 at 19 23 06" src="https://user-images.githubusercontent.com/674862/146638625-bde5c297-f178-44f4-b0d4-7950050175e3.png">

The issue comes from [AbstractChildWindow.ts#L63](https://github.com/authts/oidc-client-ts/blob/72952f23e25ca4efe8c017662aaeb2ec228a8f39/src/navigators/AbstractChildWindow.ts#L63).

When disposing, the event is raised but it's also asking for disposal -> and here comes the loop.

<img width="1017" alt="Screen Shot 2021-12-18 at 12 01 20" src="https://user-images.githubusercontent.com/674862/146638726-42e3ff51-6628-4977-aa61-6d0b6a7c7da0.png">

**Comment by kherock** [comment]
I can't actually reproduce this, do you have any extra details on how you got those logs? The lines you've highlighted don't look like a loop to me. The `dispose()` you've highlighted at **2** doesn't run the function body shown at **3**, it only removes the handler (`addHandler` returns a destructor function that unregisters the function when called).

Additionally, your logs don't suggest a synchronous loop either. The log statements shouldn't be .5 seconds apart if that were the case.

**Comment by kherock** [comment]
The .5 second interval seems to suggest that the code here isn't working correctly

https://github.com/authts/oidc-client-ts/blob/7522cd57f5a423aa989c6f3e2a571a299261c94f/src/navigators/PopupWindow.ts#L45-L50

My best guess at what is happening is that the `dispose()` is removing the abort handler for clearing the interval. I haven't been able to reproduce this yet however.
