### ISSUE TITLE
profile is not updated after silent refresh

### ISSUE THREAD

**Issue by Badisi** [authts/oidc-client-ts#276]
Bringing back an old issue from `oidc-client-js` as it still exists: [#1034](https://github.com/IdentityModel/oidc-client-js/issues/1034).

### Issue

Create a page with two manual actions : `login` and `silent renew`.

1) Load the page and trigger a login
    ```ts
    await this.userManager.signinRedirect();
    ```
2) Open a new tab, go to your IDP and change the `First Name` of the user
3) Go back to the page and trigger a silent renew
    ```ts
    await this.userManager.signinSilent();
    ```
4) The request returned an updated `id_token` with `"given_name": "new name"`
5) But the `user.profile` is not refreshed

### Workaround

I'm currently using the following workaround :

```ts
interface IdToken {
    iss?: string;
    aud?: string | string[];
    azp?: string;
    iat?: number;
    nbf?: number;
    exp?: number;
    sub?: string;
    auth_time?: number;
};

const user = await this.userManager.signinSilent();
if (user?.id_token) {
    Object.assign(user.profile, jwtDecode<IdToken>(user.id_token));
    await this.userManager.storeUser(user);
}
```

**Comment by pamapa** [comment]
Such a feature can be added to the library, disabled by default.

I am not so sure your workaround however is good enough for general usage. When you look here https://github.com/authts/oidc-client-ts/blob/f901542c242f661a291e9ae3caa07b2354f32485/src/ResponseValidator.ts#L129 you can see that depending on `loadUserInfo` it fetches more "user info" data from the end point and merges this into the profile as well. Your code path removes data inside the profile. At least a merge would be needed. Also what is about the other data, which is not updated...

**Comment by kherock** [comment]
@pamapa the issue here is actually that ResponseValidator is never run for refresh token requests, the code you've pointed out isn't used on `.signinSilent()` when a refresh token is available. I've actually left a TODO for this when I was refactoring away more usages of `any`:

https://github.com/authts/oidc-client-ts/blob/f901542c242f661a291e9ae3caa07b2354f32485/src/UserManager.ts#L269-L270

@Badisi
