### ISSUE TITLE
expose the internal logger

### ISSUE THREAD

**Issue by Badisi** [authts/oidc-client-ts#278]
I have implemented my own storage class for mobile purpose:
```ts
class MobileStorage implements Storage {
    ...
}

const userManager = new UserManager({
    userStore: new WebStorageStateStore({
        store: (isNative) ? new MobileStorage() : new InMemoryWebStorage()
    })
});
```

I would like to benefits from the internal Logger like here: [InMemoryWebStorage.ts#L14](https://github.com/authts/oidc-client-ts/blob/72952f23e25ca4efe8c017662aaeb2ec228a8f39/src/InMemoryWebStorage.ts#L14) but as it is internal I don't have access to it.

Any chance to make it public somehow ?

**Comment by pamapa** [comment]
Why not! the case you mention is a legitimate use case and this library shall also act like a SDK. Can you make a MR and export Logger as well?
