### ISSUE TITLE
Reconsider updating the API extractor report in pre-commit hook

### ISSUE THREAD

**Issue by kherock** [authts/oidc-client-ts#288]
One of the perks of generating the API report is being able to view the commit history for it and identify exactly which commits impact the public API:

https://github.com/authts/oidc-client-ts/commits/main/docs/oidc-client-ts.api.md

I frequently forget to update this file while committing, and unless I rebase and regenerate the report for every commit (or the PR branch is squashed), those commits lose their association with the change in API. 

Rather than failing the build, I propose that we automatically update this file pre-commit and instead create a PR template with an initial checklist like this

```markdown
<!-- Closes/fixes #<issue> -->

Checklist
<!-- was the API report (docs/oidc-client-ts.api.md) updated by this PR? -->
- [ ] This PR makes changes to the public API
- [ ] I have linked the relevant issue numbers
```

This way, reviewers can still have clear indicator that the API report is updated, and contributors are still prompted to be mindful of introducing changes to the API.

**Comment by pamapa** [comment]
Makes all sense, lets try that and see how it works out...

**Comment by pbklink** [comment]
Why don't you just set up `reportFolder` in `api-extractor.json` to write the file directly into the `docs` folder?
