### ISSUE TITLE
Missing state on Login Redirect

### ISSUE THREAD

**Issue by vocko** [authts/oidc-client-ts#293]
I'm not sure whether this is a bug or I do something wrong, however, I would like to read the state that is preserved between the initial load, redirect to IS and redirect back. 

From the client and IS point of view, everything seems to be fine, the state is being sent all the way through and comes back as expected:

<i>https://<span></span>localhost:44302/connect/authorize?client_id=MyClient&redirect_uri=http://<span></span>localhost:3000/authentication/login-callback&response_type=code&scope=openid profile offline_access&state=**b5924d628ef74c9b8d599a76d7127cd4**&code_challenge=asX_clrphzIXLga3cj7z3gZofVFz-FXxcer25rVsz4k&code_challenge_method=S256&response_mode=query

https://<span></span>localhost:44302/Account/Login?ReturnUrl=/connect/authorize/callback?client_id=MyClient&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauthentication%2Flogin-callback&response_type=code&scope=openid%20profile%20offline_access&state=**b5924d628ef74c9b8d599a76d7127cd4**&code_challenge=asX_clrphzIXLga3cj7z3gZofVFz-FXxcer25rVsz4k&code_challenge_method=S256&response_mode=query

https://<span></span>localhost:44302/connect/authorize/callback?client_id=MyClient&redirect_uri=http://<span></span>localhost:3000/authentication/login-callback&response_type=code&scope=openid profile offline_access&state=**b5924d628ef74c9b8d599a76d7127cd4**&code_challenge=asX_clrphzIXLga3cj7z3gZofVFz-FXxcer25rVsz4k&code_challenge_method=S256&response_mode=query

http://<span></span>localhost:3000/authentication/login-callback?code=30B4D78B1A42018F8AD3C0579B72A876CFD60936D02998F029BBDBEE3570BED1&scope=openid profile offline_access&state=**b5924d628ef74c9b8d599a76d7127cd4**&session_state=L_rI2q6PV9a_Kljbx5mHL29ftlwEdNQn6k9ky8wak98.3DF5BF2643218A919507CC884F1F1A92</i>

However, if you then look into the storage (I'm using Session storage, but should not make any difference in this case), there is no state with the round-tripped id. I'm using reference tokens and thus I can't read values from tokens as an alternative solution.

Interesting enough, all this works well on sign out redirect. The state id is sent there and back and I can pick up the state from the storage after the final redirect. The issue is not new in `oidc-client-ts`, I've had the same problem with the `oidc-client-js`. 

I'm just wondering whether I do something wrong or whether this is an issue of the library.

**Comment by pamapa** [comment]
For understanding: The state in the URL is internally used to match against the state object stored in the sessionstorage/localstorage. This library lets you round trip your own custom state. You will **not** see this custom state in the URL. This custom state is internally stored within the state object stored in the sessionstorage/localstorage. You can access it via `User` in the success case or via `ErrorResponse` in failure.

We probably should write something about that functionality into the documentation...

**Comment by vocko** [comment]
Thanks Pamapa for a quick answer and for all the work on this library!

I do understand how the state is being stored, I got a bit confused by the difference between login and logout. As at logout the only information I can get is the state id. I do a little hack getting the item with key "oidc.state_id" from the session storage what works (I suppose because the library is not cleaning the state until next login).

I did try the same approach on login, but the state was always undefined (not sure why, did not track that far the internal code, but suppose it's being removed after successful login). However, your comment pointed me to the actual functionality - user.state and this works well for login (not for logout obviously, as there is no user if successful).

I will be on holiday for the next week or so, trying to be offline, but will play with it more once back. I did get it more or less working as I wanted on Friday though.

Thanks for your comment again and happy new year!

**Comment by jafaircl** [comment]
@pamapa is it possible to add the ability to append our own values to the url state parameter? I have a use case where I need to proxy a redirect url and need to return the original url from the oauth provider. Azure B2C won't return any query parameters other than "state" and there's no current way to set that manually that I'm aware of. I'm willing to submit a PR if you're open to merging it.

**Comment by Badisi** [comment]
There is currently no way I'm aware of to do that.

I've had to implement it myself like so:
1) Before login -> save the current url to session storage
https://github.com/Badisi/auth-js/blob/main/projects/auth-js/oidc/oidc-auth-manager.ts#L229
2) After login redirect -> read the previous value and redirect the user to it
https://github.com/Badisi/auth-js/blob/main/projects/auth-js/oidc/oidc-auth-manager.ts#L447

**Comment by jafaircl** [comment]
@Badisi the problem is that the redirect url and the url of the app itself won't be on the same domain. Our deployment pipeline generates a random url for each branch. Our oauth provider doesn't support wildcards and setting a new redirect url on the tenant for each deployment won't work for a few different reasons. So we need to have a static redirect url that is just a proxy for the final redirect url. The proxy would read the final url from the url state query parameter and forward the request to where it needs to be.

**Comment by Badisi** [comment]
@jafaircl, ok I better understand your use case now, thanks for the clarification.

Using the **state** url parameter in this scenario seems a legit solution and I see that its value can be easily passed down as an argument from the signin/signout methods to the creation of the [State](https://github.com/authts/oidc-client-ts/blob/f3a805aa00a021a8844498df8a3c8dd64c7c2f7b/src/State.ts#L24) object.
I will let @pamapa decide whether a PR can be accepted for that or not.

But for your information, the [`OAuth 2.0 RFC`](https://datatracker.ietf.org/doc/html/rfc6749#section-10.12) states that "The binding value used for CSRF protection **MUST** contain a **non-guessable** value". So you have to make sure that the state parameter value is **unique** and **opaque** to ensure that it can be used for defense against CSRF and phishing attacks.
The uniqueness means it has to be generated each time on the web client side, but to make it opaque and readable by your proxy... I don't really see how (especially without leaking a cipher key on the client side).

**Comment by jafaircl** [comment]
@Badisi fwiw I’ve seen other libraries handle this by setting the state param as the nonce and the additional state separated by some delimiter like a semicolon e.g. `state=nonce;mycustomstate`. This way you can still check your opaque, unique value and get your custom state through the auth flow

**Comment by Badisi** [comment]
@jafaircl, thanks for the input, I was not aware of this syntax.

I think this feature would definitely be a great nice to have.
@pamapa, your thoughts ?

**Comment by jafaircl** [comment]
[MSAL.js](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/active-directory/develop/msal-js-pass-custom-state-authentication-request.md) and [Angular OAuth OIDC](https://github.com/manfredsteyer/angular-oauth2-oidc) are the two I know of off the top of my head. I’m sure there are more.

**Comment by pamapa** [comment]
@jafaircl I shortly search for that feature but was not able to spot it e.g. in Angular OAuth OIDC, can you point me to the source code file?

**Comment by pamapa** [comment]
> I think this feature would definitely be a great nice to have.

I would accept such a merge request...

**Comment by jafaircl** [comment]
@pamapa here is the method that builds the login url in angular-oauth2-oidc: https://github.com/manfredsteyer/angular-oauth2-oidc/blob/3ba7303b5a6fdbae5ca214764c9191637cd00126/projects/lib/src/oauth-service.ts#L1482

And here it is for MSAL.js: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/31fb0a77a6bf9db77a41330fa09a76db4ff030c0/lib/msal-common/src/utils/ProtocolUtils.ts#L42C11-L42C11
