### ISSUE TITLE
The user profile is not updated on successful sign in silent

### ISSUE THREAD

**Issue by nikolas223** [authts/oidc-client-ts#296]
Hello, when some changes happen on user claims, for example, a username change, then I use signInSilent to refresh the token. The returned user contains the correct access token with changes reflected but the profile field is not updated. The cookie also is getting stored with this mismatch. If it's true, I think it is an easy fix. Thanks and good work with the library!

**Comment by pamapa** [comment]
This is a duplicate issue of #276 which has been recently fixed and will be part of the next rc release

**Comment by Badisi** [comment]
@pamapa, any ETA on that next rc release ? (so we can start testing all the new stuff and bug fixes 🙂)

**Comment by pamapa** [comment]
i would like to have #291 + #307 + #308 merged. All are almost done. Maybe end of next week. I am also looking forward to the next rc release 🙂
