### ISSUE TITLE
signingKeys appears to be unused?

### ISSUE THREAD

**Issue by matthetherington-pa** [authts/oidc-client-ts#314]
Hi,

Apologies if this turns out to be a non-issue but I was setting up a project locally and noticed that everything seems to work fine if I provide `metadata` as an option, but omit `signingKeys`. The `.well-known/openid-configuration` endpoint on the IDP that I'm using doesn't support CORS so they can't be coming from the jwks endpoint either.

I've had a look around the oidc-client-ts codebase and it looks like the `getSigningKeys` method on `MetadataService` isn't used, along with `resetSigningKeys`.

Am I correct with the above? And if so, should they be used?

oidc-client-js looks like it uses those methods - [OidcClient.processSigninResponse](https://github.com/IdentityModel/oidc-client-js/blob/dev/src/OidcClient.js#L129) calls [ResponseValidator.validateSigninResponse](https://github.com/IdentityModel/oidc-client-js/blob/dev/src/ResponseValidator.js#L32) which [leads to ](https://github.com/IdentityModel/oidc-client-js/blob/dev/src/ResponseValidator.js#L373) the response being validated from the keys retrieved from the JWKS endpoint, or the ones provided via config.

Thanks

**Comment by pamapa** [comment]
The `getSigningKeys` feature was used with the implicit flow, which has been removed. As we provide a SDK like library we left that functionality inside `MetadataService`, even so we do not longer need it...

With the code flow we are no longer required to validate the token, a simple decode (string to object) is enough....

**Comment by matthetherington** [comment]
Thanks for clarifying @pamapa
