### ISSUE TITLE
Release version 2.0.0

### ISSUE THREAD

**Issue by raman-nbg** [authts/oidc-client-ts#322]
Currently `oidc-client-ts` is only available as `beta` or `rc` versions. Is there already any ETA for the "stable" release? What is needed to for a stable release?

**Comment by pamapa** [comment]
We are very close to a 2.0.0 release. The milestone currently lists 2 open issues, both have an MR open. #251 needs some more work.

@kherock  I think it makes sense to make a 2.0.0 release soon, maybe in 1.Feb 22 or earlier? In the case #251 does not make it, we can finish it in a follow-up release (default would be false for minor release though)...

**Comment by pamapa** [comment]
The plan is that the next rc release will be 2.0..0 unless we find bugs...

**Comment by pamapa** [comment]
2.0.0-rc.5 is ready for testing...

**Comment by orjan** [comment]
I've tested to do a port from `oidc-client` earlier this week and it looks really promising.
We haven't migrated to `code + pkce` yet so the test wasn't that extensible, but I couldn't see anything wrong either.

One thing that might be worth adding the the migration guide is how we can migrate the configuration of the storage e.g. I had to look at the source to see how to change the configuration?
```
userStore: new Oidc.WebStorageStateStore({ store: window.sessionStorage }),
```

**Comment by pamapa** [comment]
Thanks for the feedback. Regarding `userStorage`, that has not changed despite the port to TypeScript. Can you post your previous code that worked with the old library? Were you using the `Global` class?

**Comment by orjan** [comment]
> Thanks for the feedback. Regarding `userStorage`, that has not changed despite the port to TypeScript. Can you post your previous code that worked with the old library? Were you using the `Global` class?

This is my current configuration for setting the storage, there might be another way to do it even in the old lib, but this is how it looks.

```
import Oidc from "oidc-client";

var oidcmgr = new Oidc.UserManager({
  // ...,
  userStore: new Oidc.WebStorageStateStore({ store: window.sessionStorage }),
});
```

**Comment by pamapa** [comment]
With this library you can still use:
```JavaScript
var oidcmgr = new UserManager({
  // ...,
  userStore: new WebStorageStateStore({ store: window.sessionStorage }),
});
```
I do not see a difference here...
