### ISSUE TITLE
scope in refresh tokens

### ISSUE THREAD

**Issue by kasperp** [authts/oidc-client-ts#364]
I'm using the `oidc-client-ts` with Azure AD, and I stumbled on an issue refresh tokens. 

From what I under from https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#refresh-the-access-token and https://docs.microsoft.com/en-us/answers/questions/192699/confusing-error-message-on-failed-refresh-token-re.html Azure AD requires the scope to be sent when refreshing the access token.

If change [OidcClient.ts#L168-L171](https://github.com/authts/oidc-client-ts/blob/main/src/OidcClient.ts#L168-L171) to include the scope as below this issue is resolved for me.

```ts
const result = await this._tokenClient.exchangeRefreshToken({
  refresh_token: state.refresh_token,
  scope: state.scope,
  timeoutInSeconds,
});
```

Would this be something that would make sense to add?

I'm new to OIDC, so please excuse any misunderstanding on my part.

Thanks for maintaining this library. It helped me quickly to get an OIDC flow implemented.

**Comment by kherock** [comment]
I think your suggestion makes sense, thanks for finding this. If you're able, I'd be happy to review a PR!

**Comment by kasperp** [comment]
great I'll make a PR with this suggested change. Thanks for the quick response
