### ISSUE TITLE
Is it possible to use oidc-client-ts in service worker?

### ISSUE THREAD

**Issue by kostia-lev** [authts/oidc-client-ts#398]
I would like to use oic-client-ts in service worker in chrome extension. 
Be these things throw errors(window is not existent in service worker):
async signinPopupCallback(url = window.location.href, keepOpen = false) {
How to fix such things?

**Comment by pamapa** [comment]
This library only supports SSR (without a `window`), but to actually authenticate a `window` is required. See https://github.com/authts/oidc-client-ts/issues/256#issuecomment-992080256.

**Comment by pamapa** [comment]
i am now closing this, if you do not agree please comment here...

**Comment by angelo-v** [comment]
I would like to see this working in service workers and chrome extensions using manifest v3 as well. Can you reopen the issue? Anything speaking against supporting this?

**Comment by Alino** [comment]
I am struggling with the auth in manifest v3 service worker since it was released. It would be really nice if this was supported.

We would also probably want to have a new cache option. To cache inside ```chrome.storage``` and not ```window.localStorage```

**Comment by angelo-v** [comment]
I am willing to work on this, but only if https://github.com/inrupt/solid-client-authn-js/issues/2202 gets resolved, otherwise it won't help my cause

**Comment by Alino** [comment]
For anyone wondering about MSAL, it has similar problems supporting the service worker and manifest v3
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3923

you can also have a look at my example repo and perhaps reuse some polyfills for window object even in OIDC lib.
https://github.com/Alino/MSAL_ChromiumExtensionSampleManifestV3
