### ISSUE TITLE
Navigate back to login (browser back button) and then login => No matching state found in storage

### ISSUE THREAD

**Issue by Frozenlock** [authts/oidc-client-ts#402]
Same problem as the original library https://github.com/IdentityModel/oidc-client-js/issues/940.

> The scenario is:
> 
> user lands on app page -> page checks user, if not logged in -> signinRedirect to Id server -> Id server redirects back to auth-callback -> auth-callback navigates to some page in app.
> 
> Now if user pressed back button which will take it back to the login (where the state (state which is sent to id server) wouldn't be written to local storage which is why siginRedirectCallback throws this error.

https://github.com/IdentityModel/oidc-client-js/issues/940#issuecomment-532657529

Should `oidc-client-ts` leave the state available for some time?

**Comment by Frozenlock** [comment]
I'm not sure how this is related to the current issue, but I'll try to explain in more details in case I'm missing something.

The problem here is that the stored state is removed immediately after the redirection from login. So if the user presses "back", then logs again, there is no more state available, even tho the redirect URL contains a state parameter. In other words, `oidc-client-ts` tries to load the stored state, but none is available because it removed it the first time the user logged in.

We do use `replaceState` once we get the "correct" SPA path from the stored state, but we reach never this point when the user presses back and logs again.

**Comment by pamapa** [comment]
I am unable to reproduce your use-case here with my application. I am using `react-oidc-context`. From which page does the user click back? When he clicks back on which page does he land?

not interrupt-able flow:
```
_signinEnd -> processSigninResponse(url) -> readSigninResponseState(url, true)

readSigninResponseState removes the state if all good
processSigninResponse returns a user profile, if all is good, which is stored inside _signinEnd
```

**Comment by Frozenlock** [comment]
User loads the SPA and is sent to Cognito login page (via `signinRedirect`):

`https://somesubdomain.amazoncognito.com/login?client_id=6rrlpafiu2flt0p0333hmo2g35&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2F&response_type=code&scope=openid&state=24a76892f262438c8e8c62ab26e76507&code_challenge=_rbWr1klF9KeVFXgjngMZsuJb9DGu-9Vz_YtJS8lT6E&code_challenge_method=S256&response_mode=query`

![image](https://user-images.githubusercontent.com/1152041/156436582-cdb023dc-ed0c-497d-8ce0-7a5541438540.png)


After pressing "Sign in", user is sent back to the SPA where `oidc-client-ts` handles the redirection with `signinRedirectCallback`.

`http://localhost:4000/?code=f6895292-c94f-4b81-b78d-720989f85679&state=24a76892f262438c8e8c62ab26e76507`

At this point the state in `localStorage` is removed.

The user presses "back" and returns to the login page:

`https://somesubdomain.amazoncognito.com/login?client_id=6rrlpafiu2flt0p0333hmo2g35&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2F&response_type=code&scope=openid&state=24a76892f262438c8e8c62ab26e76507&code_challenge=_rbWr1klF9KeVFXgjngMZsuJb9DGu-9Vz_YtJS8lT6E&code_challenge_method=S256&response_mode=query`

![image](https://user-images.githubusercontent.com/1152041/156436069-12594b35-cc79-4df8-a91f-cbd2e74f3851.png)

User signs in as same user (or different user, it doesn't matter) and is sent back to the SPA.

`http://localhost:4000/?code=859a6911-71d8-41b4-a7b5-da9d775bdc1d&state=24a76892f262438c8e8c62ab26e76507`

`signinRedirectCallback` is called again, but this time the state in the URL doesn't exist in the localStorage, as it was deleted after the first login.

This is the exception:

![image](https://user-images.githubusercontent.com/1152041/156436487-820cfe3f-2bb1-4940-9aed-75273121d76e.png)

**Comment by pamapa** [comment]
Thanks for the detailed explanation.

When i reproduce it and press "back" in that case i land on the authorization page without any auth query param: URL=https://xxx.com/as/GlLzt/resume/as/authorization.ping?zone=snx.

The error i get is:

![image](https://user-images.githubusercontent.com/10164638/156514354-63bd3952-5ce7-482b-bcc9-4d5cb3fb8a81.png)

In this scenario even if the state would be still present, it would not help.

**Comment by Frozenlock** [comment]
I'm probably missing something, but I don't understand why you're showing me your situation. Is it to argue that Cognito is somehow breaking OIDC by allowing the user to go "back" to the login page?

> When i reproduce it and press "back" in that case i land on the authorization page without any auth query param

That's quite odd; it would mean your browser history was tempered with. Perhaps you have the login page further back in your history. Or, alternatively, pressing "back" really brought you back to the login page, but the server responded with a redirection to the URL with the state stripped away from the params.

> If i press "forward" on that "Page Expired" page, i am still signed-in an can continue to work...

Yes, assuming you've used `history.replaceState`, forward button should bring you back with the redirection info removed.

But that's only tangentially related to the issue at hand: what should `oidc-client-ts` do with the stored state if the user might be redirected a second time from the login page?

**Comment by pamapa** [comment]
> but the server responded with a redirection to the URL with the state stripped away from the params.

I assume that happen in may case.

The current  `oidc-client-ts` implementation ex-changes the localStorage `state` against a `profile`, which makes it simple. I am afraid if we break that it will make things more complicated. Is only  `Cognito` affected?
Will using `history.replaceState` + forward button bring you too back?

@kherock Can you reproduce with your authentication service?

**Comment by kherock** [comment]
I'm not sure if there's much that can be done here. In my mind, navigating into the middle of an authentication flow is invalid and *should* generate an error. The spec doesn't seem to have strict prescription on how to treat this scenario, but it does suggesting associating an authentication session cookie with the `nonce` parameter provided by the client in order to prevent replay attacks. In case the auth server doesn't implement this restriction (as in @pamapa's screenshots), the UX I'd expect from the application side would be an error explaining that the sign in request is invalid with options to restart the sign in flow. We could make this simpler by providing a named error so that applications don't need to parse error message strings.
