### ISSUE TITLE
Allow passing an id_token_hint into signoutRedirect

### ISSUE THREAD

**Issue by jor-rit** [authts/oidc-client-ts#407]
`id_token_hint` is an optional (even 'recommended' in latest OIDC specs) parameter for logout calls.
But the typescript definitions don't allow passing this into the signoutRedirect call.

Certain OIDC providers require this parameter.

**Comment by pamapa** [comment]
You found a type error. `signoutRedirect` calls `_signoutStart`. The later supports `id_token_hint` in args.
