### ISSUE TITLE
Handling sign-out on different applications, different domains

### ISSUE THREAD

**Issue by kennyStarfisk** [authts/oidc-client-ts#409]
I'm struggling with a sign-out problem across two spa-applications on different domains. 

Using the monitorSession option on the usermanager is solution. When set to true I receive a notification on the secondary application that the user on the primary application is signed out, by which the secondary application can invoke removeUser. 

If I'm not mistaken this monitorSession relies on a cookie...?

When using Safari (which blocks "tracking"-cookies by default) the session throws the signout event when logging in, I believe this is because the cookie isn't set...? 

Anyone having experiences on this this?

**Comment by pamapa** [comment]
I have no experience with that kind of use case. The _different domains_ makes it very tricky, as modern browser have all kind of guards to not allow that due to security reasons...

**Comment by brockallen** [comment]
> Anyone having experiences on this this?

Yes: https://docs.duendesoftware.com/identityserver/v6/bff/overview/#react-to-changes-in-the-browser-security-models

**Comment by pamapa** [comment]
Modern browsers prevent "different domain" access, which is a good feature for security, there is not much we can do within this library.
