### ISSUE TITLE
Automatic silent renew deletes profile from stored state

### ISSUE THREAD

**Issue by markbrockhoff** [authts/oidc-client-ts#415]
Hello,

I noticed that the property `profile` of the object stored inside the session storage is overwritten when a silent renew is triggered. It looks like the response of the silent renew just overwrites the whole object.

State stored in session storage after signin with redirect callback:
![image](https://user-images.githubusercontent.com/95471369/157415979-9827e06d-c505-48ed-a0f4-5b139c256fbf.png)

State stored in session storage after first silent renew:
![image](https://user-images.githubusercontent.com/95471369/157415524-854f291b-9ac5-43e7-8bec-3050d8144d52.png)

I also enabled the option `loadUserInfo` of the UserManager, but the silent renew doesn't seem to respect it.
It would be great if the stored profile would remain in place even after the silentRenew.

**Comment by pamapa** [comment]
@kherock you recently improved the silent renew, can you have a look at this? I guess we must ensure to not override the profile with an empty one...

**Comment by pamapa** [comment]
@markbrockhoff You are using oidc-client-ts 2.0.0 or later?

**Comment by markbrockhoff** [comment]
> @markbrockhoff You are using oidc-client-ts 2.0.0 or later?

Yeah, I'm using version 2.0.1. Sorry, should have noted that in the issue.

**Comment by pamapa** [comment]
With the silent renew the function `_processClaims` is called in at the end via `_signinEnd`. `_processClaims` load the user profile via `_userInfoService.getClaims`. Why is the profile **not loaded** there? Can you enable the log level to Debug and post what you get?

**Comment by markbrockhoff** [comment]
Sure, but even with the log level set to Debug that's all I get:
![image](https://user-images.githubusercontent.com/95471369/157443090-b427a8db-bd8b-410c-a9ef-612c826d3719.png)

The renew is not even shown in there. I just noticed it by the network call and the change in the session storage. I set `accessTokenExpiringNotificationTimeInSeconds` to a pretty high level so that the silent renew happens every 20 seconds for testing. After the successful signinRedirectCallback the profile is set for those 20 seconds. After which the renewal request is sent out and successfull. But as described earlier the profile gets emptied by that.

**Comment by pamapa** [comment]
We need to know first where that empty profile comes from. Please send a Debug log of the silent renew workflow. You probably need to enable "Preserve log" in your browsers DevTool console ...

**Comment by markbrockhoff** [comment]
Even with preserve log enabled, there is not much more to see:
![image](https://user-images.githubusercontent.com/95471369/157446902-6ef5192d-3805-432c-bef7-fdcaefa38721.png)
Please ignore the warnings and the error the warnings are caused by vue-i18n during development and the error is intentional since I'm trying to execute the signinRedirectCallback before actually executing signinRedirect in case it already happened.

The logs still dont contain anything about the silent renew. I set them up by calling this before creating the UserManager:
```ts
Log.setLogger(console);
Log.setLevel(Log.DEBUG);
```

That should do the trick right? Or is there a even more verbose mode?

**Comment by pamapa** [comment]
Yes you setup the Debug logger correctly.
Keep in mind, that the silent renew is done via separate iframe window. Are you sure you are using the same oidc-client-ts + Log (Debug) configuration (aka loadUserInfo) there too?

**Comment by kherock** [comment]
Thanks for the logs, that explains why the profile wasn't being populated after refresh.

The `openid` scope isn't included in the refresh token request since it's not present in the scope returned with your profile after the initial sign in. We copy the scope from the profile since refresh token grants aren't allowed to increase the scope.

I can see in your original screenshot, before the profile is wiped, that the scope is `profile siam`. This is pretty weird behavior. Do you mind sharing what IDP server implementation you're using (Cognito, Keycloak, etc.)?

**Comment by markbrockhoff** [comment]
Actually the scope being `profile siam` is not unexpected, those are custom scopes provided by my IDP. I honestly don't know what exectly is used behind our IDP, but I'm pretty sure it complies to the OAuth2 specification. 
It looks like my IDP is not returning the "openid" scope in the response. This probably causes the check isOpenId() inside the SigninResponse to fail. Do you have any idea how to tackle this weird problem? Because renewing the token itself works fine, it's just the sideeffect that the profile gets deleted that is a bummer...

**Comment by kherock** [comment]
The `profile siam` is unexpected because it should be `openid profile siam`. We can work around this though this behavior isn't ideal on your IDP's part.

**Comment by kherock** [comment]
The reason that hacking `openid` back onto the scope in the response isn't ideal is given here: https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/

> The requested scope must not include additional scopes that were not issued in the original access token. Typically this will not be included in the request, and if omitted, the service should issue an access token with the same scope as was previously issued.

I think the better behavior here might be to simply discard the scope sent back from the IDP and just preserve the scope used in the original request?

**Comment by markbrockhoff** [comment]
Sorry for the late reply, but I debugged the problem even further:

It looks like my IDP uses `siam` as the default scope, basically replacing `openid`. This means, even if the openid scope is sent in the request, it won't be present in the response. So that problem is on my side.
To tackle it, it would be really helpfull, if it was possible to change the default scope used inside SigninResponses method `isOpenID()`.

A second problem I encountered during debugging was the check for the subs to be equal inside the function `_processClaims()` of the ResponseValidator (Line 170):
```ts
if (claims.sub !== response.profile.sub) {
    logger.throw(new Error("subject from UserInfo response does not match subject in ID Token"));
}
```

At least in my response for the refresh token, there is no profile provided and therefore `response.profile.sub` is undefined. It would be great if the setting `validateSubOnSilentRenew` of the UserManagerSettings was respected there. I'm not sure, but it might even be that the check in that place is redundant as the equality of the subs is also checked inside the function `signinSilent` of the UserManager.

I already tested what I just described by editing the method `_processClaims()` inside the installed npm package:

![Bildschirmfoto 2022-03-10 um 14 02 35](https://user-images.githubusercontent.com/95471369/157668815-63fb7d25-4646-42fb-acc8-8a6d601585fa.png)

I just commented out the check for `isOpenId()` as there is no `openid` scope in my renew token response and the check for the sub to be equal. I also added a few more logs for debugging but that`s it. With those simple changes I was able to get the automatic silent renew working for me.

Here is the important part of the log from my test:

![Bildschirmfoto 2022-03-10 um 14 06 09](https://user-images.githubusercontent.com/95471369/157669164-161cd6a1-32e1-47b8-a8c4-faaefdb7301c.png)

**Comment by pamapa** [comment]
Idea: We could remove:
```jsx
if (!response.isOpenId) {
  logger.debug("response is not OIDC, skipping claims processing");
  return;
}
```

and change if code to:
```jsx
if (response.isOpenId && claims.sub !== response.profile.sub) {
  logger.throw(new Error("subject from UserInfo response does not match subject in ID Token"));
}
```

**Comment by markbrockhoff** [comment]
Yeah, I just testet it, this would fix my problem.
