### ISSUE TITLE
post_logout_redirect_uri can not be overridden 

### ISSUE THREAD

**Issue by AndreiFiadosau** [authts/oidc-client-ts#435]
Previous oidc-client-js package allowed someone to set postLogout url like this

```
await userManager.signoutRedirect({
        id_token_hint: 'someIdToken',
        post_logout_redirect_uri: `some specific route for this particular logout`,
      });
```

Now its hardcoded to use initial `post_logout_redirect_uri` in UserManagerSettings
https://github.com/authts/oidc-client-ts/blob/c9fcaa0396148c2cae942b2e9a4ea1e6633a0bcc/src/UserManager.ts#L432

**Comment by pamapa** [comment]
i guess you can override the type error with an ts-ignore and already use that for now. So there is no rush for you. I will make a MR if that goes in maybe next week or the week after we will make another bugfix...

**Comment by AndreiFiadosau** [comment]
@pamapa yep you're right, this issue does not really block me, I've just tried to call signoutRedirect with this param and it works. Thank you.
