### ISSUE TITLE
Silent renew error

### ISSUE THREAD

**Issue by AestheticM** [authts/oidc-client-ts#441]
Hello,

I just have a problem with the automaticSilentRenew.
As I understand I don't have to do anything for it to work but after the silent renew has been made if I try to call an endpoint again I have a 401 error because the token used is still the expired one.
In auth I can see this error : `Invalid token specified: Cannot read properties of undefined (reading 'replace')`.

I'm pretty sur the silent renew is made but the token is not updated.

Can you help me understand where is the problem ?

Thanks in advance

**Comment by AestheticM** [comment]
It's 
```
validateRefreshResponse
  - _processClaims
```

**Comment by pamapa** [comment]
Does MR #445 fix your issue?

**Comment by AestheticM** [comment]
Yes thank you, it's working now !
