### ISSUE TITLE
Token renewal fails

### ISSUE THREAD

**Issue by mariusflorescu** [authts/oidc-client-ts#442]
hi there,

so using the `singinRedirect` method works, both authorize redirect and code request work as expected.

However, when the automatic renewal should take place, something weird happens. The code request is being made to `https://localhost:3000/?code=...`

![both requests](https://user-images.githubusercontent.com/73541683/159743093-828a4d22-bf2f-4c02-b853-a975b6d79665.png)

![Code request](https://user-images.githubusercontent.com/73541683/159742859-287fa3a7-28fa-411a-9f7c-72fb697d1549.png)

I'm using Auth0 and the config is at it follows:
```
export const oidConfig: AuthProviderProps = {
  authority: '....',
  client_id: '...',
  userStore: new WebStorageStateStore({
        store: new InMemoryWebStorage()
      }),
  stateStore: new WebStorageStateStore({
    store: window.sessionStorage
  }),
  staleStateAgeInSeconds: 60,
  extraQueryParams: { audience: '...' },
  redirect_uri: '...'
}
```

I believe that is something related to the IFrame because if I try to force it when the token expiration event is sent, the frame would time out.

**Comment by pamapa** [comment]
Does your application eventually wrongly redirect from `HTTP://localhost:3000` to `HTTPS://localhost:3000`?

**Comment by pamapa** [comment]
Without any detailed full log of Console with DEBUG level and network tab log, both with Preserve Log we have no chance to see your problem...

If you see the request out with *HTTP* inside as redirect param and the identity server comes back with **HTTPS**, the problem must be on the identity server side (configuration?). There is not much we can do unless we send any param wrongly or missing...

**Comment by mariusflorescu** [comment]
Setting `HTTPS=true` as env variable solved the problem for now.

**Comment by pamapa** [comment]
if you have more information please let us know, for now i close this issues, as we can not do anything here
