### ISSUE TITLE
Refresh id_token independently from access_token

### ISSUE THREAD

**Issue by sebastianrothe** [authts/oidc-client-ts#447]
Hey, thanks for the continuous support of the library.

We use OIDC with Gitlab to identify users from the frontend to the backend. There we use the id_token to get the mail address from the profile claim in the backend. With Keycloak everything works as expected, but we switched to Gitlab Auth and now, the id_token expires earlier(after 2m) than the refresh_token(after 2h).

Is there a way to handle both expirations differently and refresh them independently?

I know, there is a lot of discussions about id_token vs. access_token. But we need some claims from the token and with access_token the spec doesn't really enforce a format (could be a JWT or just a string).

**Comment by kherock** [comment]
ID tokens don't have any use after they're verified and decoded, so their expiration times shouldn't be relevant here. I'm not sure I understand your problem.

If you need to fetch current ID token claims, you can use the userinfo endpoint on your IDP with the access token. You can do this from the backend with an access token. We do this internally on the front end when populating the `profile` field after sign in.

**Comment by pamapa** [comment]
Have a look to [settings.loadUserInfo](https://github.com/authts/oidc-client-ts/blob/main/src/OidcClientSettings.ts#L76-L77) to get additional userinfo...

**Comment by sebastianrothe** [comment]
Thanks  for your answers. We thought we could get around calling the IDP everytime from the backend.

**Comment by sebastianrothe** [comment]
With the help of #453 and setting `accessTokenExpiringNotificationTimeInSeconds` to `(2h - 2m)`, we were able to refresh the tokens earlier.
