### ISSUE TITLE
ErrorTimeout from signinSilent after token was successfully retrieved

### ISSUE THREAD

**Issue by krsticjovana** [authts/oidc-client-ts#454]
Hello,

I am experiencing an issue with the signinSilent method is called. The token is retrieved successfully and it is stored in session storage

_tokenExpiring: ErrorTimeout from signinSilent: ErrorTimeout: IFrame timed out without a response

This is the error I am getting and because the timeout is set to retry the signinSilent in 5 seconds I have a lot of requests sent to the server.

https://github.com/IdentityModel/oidc-client-js/issues/1088 
I saw this issue was closed about oidc-client and I tried the last comment with the certificate but it still doesn't work

**Comment by pamapa** [comment]
I assume you are using latest version 2.0.2.

Which Identity server are you using, does it support silent renew via iframe? Some do not, see https://authts.github.io/oidc-client-ts/index.html#provider-specific-settings

**Comment by krsticjovana** [comment]
It's okay now. I have turned off the silent renew process. 

I have another question now. Is it possible to not send the code verifier in the request for the token. We have a custom Identity server which only supports one of the both, either code verifier or refresh token.

**Comment by pamapa** [comment]
The [PKCE](https://oauth.net/2/pkce/) flow is essential to this library, we are following the spec. Its already tricky enough with all optional or by some (Identity server) not supported parts. If you can make it work with your not standard Identity server, be happy, but do not expect support from us. Sorry...

**Comment by sebastianrothe** [comment]
Works with Keycloak, once I set a `silentRedirectUri` which is unrestricted page in my webapp and calling the [redirectCallback](https://github.com/authts/oidc-client-ts/blob/fc0d67897b8863a46c01ae5d229a700edb02239b/samples/Parcel/src/user-manager/sample-silent.js#L4) there.

**Comment by pamapa** [comment]
if you have more information please let us know, for now i close this issues, as we can not do anything here
