### ISSUE TITLE
redirect_uri can not be overridden

### ISSUE THREAD

**Issue by keropodium** [authts/oidc-client-ts#468]
Following the same fashion as: #436

I think we are missing the `redirect_uri` property in type `ExtraSigninRequestArgs` at `src/UserManager.ts`

**Comment by pamapa** [comment]
We can do so. What is your use-case? Why do you need it?

**Comment by keropodium** [comment]
> We can do so. What is your use-case? Why do you need it?

We are just migrating from old oidc-client.
Current implementation lets our user click on the login button from every page after any in-browser route change, so we are calling userManager.signinRedirect() on user demand and returning to the same url after login.

**Comment by pamapa** [comment]
Feel free to provide a MR for that...
