### ISSUE TITLE
After signinRedirect() how do I get auth token

### ISSUE THREAD

**Issue by Aoshua** [authts/oidc-client-ts#476]
Sorry, I think I'm just missing something about how to use this library. 

I am trying to implement Authorization Code grant with PKCE. After I call `manager.signinRedirect()` and enter the user's credentials, I am redirected to the correct URI with an auth code: 
```http://localhost:8080/auth?code=BBB95B2B83FDD167F584844D249799589F5451D0E4C6C7DBE19207422FE87A6A&scope=openid%20profile%20email&state=33fefd8fa31d4e32969a9d2b7eacae7a&session_state=hxL7x6parXK_EbAIYg0xYbKT_7rkdXjA_inKa_hPVqE.17CF5F8B787D2D997BB2AAD295C4FDB0```
Now which method do I call to make that final authorization token request or was this supposed to be handled behind the scenes by the `signinRedirect()` method?

**Comment by pamapa** [comment]
If you are redirected like above you have to call `userManager.signinCallback()`, which takes care of the authorization parameters...

**Comment by Aoshua** [comment]
Yes, this worked. Thanks for the clarification!
