### ISSUE TITLE
Which Method Calls the User Info endpoint?

### ISSUE THREAD

**Issue by Aoshua** [authts/oidc-client-ts#477]
Just another quick question here.
Which method calls the user info endpoint? I using `manager.getUser()`, which I see returns an object with the tokens, but it doesn't seem to call the user endpoint and store the claims returned by the identity provider.

**Comment by pamapa** [comment]
The library does it automatically for you. It will enrich the user profile if requested to do so during the authorization process. You can enable it via the setting `loadUserInfo`. See [documentation](https://authts.github.io/oidc-client-ts/interfaces/OidcClientSettings.html#loadUserInfo) and [code](https://github.com/authts/oidc-client-ts/blob/main/src/ResponseValidator.ts#L159-L166).

**Comment by Aoshua** [comment]
Great, thanks again!
