### ISSUE TITLE
Errors in Typings...

### ISSUE THREAD

**Issue by Gerrilicious** [authts/oidc-client-ts#480]
Hello,

first of all thank you all for your work on this package!

Unfortunately I don't get why I see the following errors in the console when using the package, any help would be greatly appreciated!

The Errors are only in the Definition file and are as follows: 

ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(7,24):
TS2420: Class 'AbstractChildWindow' incorrectly implements interface 'IWindow'.
  Type 'AbstractChildWindow' is missing the following properties from type 'IWindow': navigate, close
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(9,41):
TS2304: Cannot find name 'reason'.
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(10,42):
TS2348: Value of type 'SetConstructor' is not callable. Did you mean to include 'new'?
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(11,24):
TS2693: 'WindowProxy' only refers to a type, but is being used as a value here.
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(11,38):
TS2531: Object is possibly 'null'.
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(12,5):
TS2552: Cannot find name 'navigate'. Did you mean 'Navigator'?
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(12,14):
TS2304: Cannot find name 'params'.
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(12,22):
TS2693: 'NavigateParams' only refers to a type, but is being used as a value here.
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(12,39):
TS2348: Value of type 'PromiseConstructor' is not callable. Did you mean to include 'new'?
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(13,5):
TS2304: Cannot find name 'abstract'.
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(14,13):
TS2304: Cannot find name '_dispose'.
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(15,22):
TS2304: Cannot find name '_notifyParent'.
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(15,52):
TS2552: Cannot find name 'url'. Did you mean 'URL'?
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(15,57):
TS2693: 'string' only refers to a type, but is being used as a value here.
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(15,65):
TS2304: Cannot find name 'keepOpen'.
ERROR in C:/Projects/ReactOidcClientTs/node_modules/oidc-client-ts/dist/types/oidc-client-ts.d.ts(15,76):
TS2693: 'boolean' only refers to a type, but is being used as a value here.
Version: typescript 3.9.7

Thanks in advance.
Gerry

**Comment by pamapa** [comment]
I guess your typescript version is too old. We are using "typescript": "~4.5.4".
