### ISSUE TITLE
support overriding "prompt" on signinRedirect

### ISSUE THREAD

**Issue by justin-mellor** [authts/oidc-client-ts#536]
I have two calls to signinRedirect. One does not pass prompt, the other passes prompt=login so that I can force the external provider to show the login prompt. Looks like you can do this, but the SignInRedirectArgs don't currently support it. The old oidc-client allowed you to override pretty much everthing so I guess there are probably more things people will want to override going forward.

**Comment by pamapa** [comment]
Please provide a MR request. You can extend `ExtraSigninRequestArgs` and pick prompt too. As a temporary work around you can ignore the typescript error the prompt param should be passed down...
