### ISSUE TITLE
session_state is lost on silent refresh token renewal

### ISSUE THREAD

**Issue by shartte** [authts/oidc-client-ts#569]
I am trying to use the silent refresh feature with session state management, but run into the following issue:

I have very short access token lifetime (5min). When oidc-client-ts (successfully, I might add) refreshes the access token using the refresh token, it seems to clear the `session_state` field of User. This leads to session management not working when I reload the page, as now `session_state` is null.

Steps to reproduce:
- Set up a client with `monitorSession: true`, short access token lifetimes and refresh tokens
- Log in without any previous state
- Observe that the session mgmt iframe is loaded (via the debug log for example)
- Wait for silent refresh token renewal
- Reload the page
- Observe that no login attempt is made (since there is still a valid access token in sessionStorage)
- Observe that the session mgmt iframe is *not* loaded (since session_state is now null)
- This can also be verified by checking the content of sessionStorage

**Comment by pamapa** [comment]
The user profile gets updated in the refresh flow as well as during the initial signin. See https://github.com/authts/oidc-client-ts/blob/74a03ccb8ef998b1bdb5bc721c6b1352debe073a/src/ResponseValidator.ts#L85

Maybe you need something like we do for the `scope`? See https://github.com/authts/oidc-client-ts/blob/main/src/ResponseValidator.ts#L78-L79

**Comment by pamapa** [comment]
Does the MR #570 fix this for you?
