### ISSUE TITLE
Migrating from JS version, but fails with google authentication

### ISSUE THREAD

**Issue by WillooWisp** [authts/oidc-client-ts#571]
Hi,

I'm migrating to this ts version of the library from the js version, and I successfully manage to authenticate using the id_token from Azure AD, but trying to retrieve the id_token from Google fails.

I used to have id_token as response type with the js version, but that does not work here. But using code as response type together with openid included in scope, an ID token should issued from the token endpoint in addition to an access token. But now it complains about the "client_secret is missing", but that should not be needed from a web browser right? It was not needed earlier.

My configuration looks like this (I have tried explicit metadata endpoint urls as well, but no difference):

```
{
	authority: 'https://accounts.google.com',
	// metadata: {
	// 	authorization_endpoint: 'https://accounts.google.com/o/oauth2/auth',
	// 	token_endpoint: 'https://oauth2.googleapis.com/token'
	// },
	client_id: '<id>.apps.googleusercontent.com',
	redirect_uri: `${window.location.origin}/login/oidc/google`,
	silent_redirect_uri: `${window.location.origin}/login/oidc/google`,
	post_logout_redirect_uri: `${window.location.origin}/login`,
	response_type: 'code',
	scope: 'openid email profile'
}
```

This works against Azure AD without any client secret

```
{
	authority: 'https://login.microsoftonline.com/<tenantId>/v2.0',
	client_id: '<id>',
	redirect_uri: `${window.location.origin}/login/oidc/azure`,
	silent_redirect_uri: `${window.location.origin}/login/oidc/azure`,
	post_logout_redirect_uri: `${window.location.origin}/login`,
	response_type: 'code',
	scope: 'openid email profile'
}
```

What am I missing here?

**Comment by WillooWisp** [comment]
Maybe this answers my question, https://blog.please-open.it/auth_code/, since it seems Google is not allowing authorization code exchange with a public client.

Does that mean we are stuck with the js version and implicit flow, where id_token can be used as response type?

**Comment by Badisi** [comment]
The Google case was already discussed in  https://github.com/authts/oidc-client-ts/issues/152 and final answer from @pamapa was :
> The implicit flow is gone for good. If you need it stick with the predecessor library...

So basically if you want to use Google as an IDP, you either have to:
- use `oidc-client-js` with `implicit flow`
- use `oidc-client-ts` and specify a `client secret` (which I would not recommend)
