### ISSUE TITLE
Add getAccessToken() function to UserManager

### ISSUE THREAD

**Issue by ewoerner** [authts/oidc-client-ts#584]
(Written with react-oidc-context in mind, but the root cause is probably in oidc-client-ts.)

Currently, there is no "proper" way to get a valid access token with the `UserManager`.
* `(await UserManager.getUser()).access_token` may return an expired access token if `automaticSilentRenew === false`, or if the previous automatic silent renew failed due to a network condition.
* `(await UserManager.signinSilent()).access_token` returns a valid access token, but the price is that there is always an additional network request.

My suggestion would be to add an async function `UserManager.getAccessToken()`, which returns an access token that can be used in a network request:
1. If the access token is still fresh, return it.
2. If there is already a concurrent request to refresh the access token (e.g. from a previous `getAccessToken()` call, or from silent renewal), await for that request
3. If the access token is about to expire, refresh it, then return the refreshed access token.

**Comment by pamapa** [comment]
Current design: The access token is refreshed in advance, such that its storage is up-to-date in local or sessionStorage. In my applications i do directly access that token from localStorage by using something like this:
```js
import { User } from "oidc-client-ts"

function getUser(): User {
    const oidcStorage = localStorage.getItem(`oidc.user:<your authority>:<your client id>`)
    if (!oidcStorage) {
        return null;
    }

    return User.fromStorageString(oidcStorage);
}
...
const user = getUser();
const token = user?.access_token;

// in case the token is undefined, you have to take care somewhere else (e.g. App.tsx) in your application like:
const isAuthenticated = user ? !user.expired : false;
if (isAuthenticated) {
  // render something or redirect to login page
}
```
