### ISSUE TITLE
Looking for a zero-to-hero tutorial for how to utilise this framework

### ISSUE THREAD

**Issue by timothydilbert** [authts/oidc-client-ts#591]
Hi Guys,

Can anyone suggest a tutorial for a neebie on how to use `oidc-client-ts`? I understand OIDC, PKCE, etc. I've just never used `oidc-client-ts` before and I am looking for a tutorial that can get me started.

**Comment by pamapa** [comment]
Have a look and run the demo site (./samples/Parcel): oidc-client + user-manager.

Also see [Angular sample](https://github.com/authts/sample-angular-oidc-client-ts) or [react-oidc-context](https://github.com/authts/react-oidc-context).

1. setup your settings and setup your oidc provider configuration (authority + client-id + redirect-uri) see https://authts.github.io/oidc-client-ts/#required-settings 
2. trigger authz process: `mgr.signinRedirect()`
3. handle callback (setup via redirect-uri) by calling `mgr.signinCallback()`
4. verify user is in session storage
5. if not verify network traffic + enable console log see https://authts.github.io/oidc-client-ts/#logging

**Comment by Robinyo** [comment]
I wrote a series of posts about working with Keycloak, Angular and oidc-client-js that might be of help:
- https://robferguson.org/blog/2019/12/24/getting-started-with-keycloak/
- https://robferguson.org/blog/2019/12/29/angular-openid-connect-keycloak/
- https://robferguson.org/blog/2019/12/30/angular-oauth2-keycloak/
- https://robferguson.org/blog/2020/01/03/keycloak-flowable-and-openldap/

**Comment by timothydilbert** [comment]
These are excellent. Thanks, gents.
