### ISSUE TITLE
Metadata error after update from 2.0.4 to 2.0.5

### ISSUE THREAD

**Issue by Ic3xX** [authts/oidc-client-ts#597]
Hello,

since the last update from 2.0.4 to 2.0.5 i'm getting the following error in my react web application after calling signInRedirectCallback(). Reverting back to 2.0.4 seems to work fine.

Any idea's why it isn't working anymore?

```
oidc-client-ts.js:105 [MetadataService] _getMetadataProperty('userinfo_endpoint'): Error: Metadata does not contain property userinfo_endpoint
    at MetadataService._getMetadataProperty (oidc-client-ts.js:853:1)
    at async UserInfoService.getClaims (oidc-client-ts.js:1065:1)
    at async ResponseValidator._processClaims (oidc-client-ts.js:1370:1)
    at async ResponseValidator.validateSigninResponse (oidc-client-ts.js:1273:1)
    at async OidcClient.processSigninResponse (oidc-client-ts.js:1899:1)
    at async UserManager._signinEnd (oidc-client-ts.js:3160:1)
    at async UserManager.signinRedirectCallback (oidc-client-ts.js:2889:1)
```

**Comment by pamapa** [comment]
The type file has not changed much. Specifically `AbstractChildWindow` did not change at all, there are some addition else where, which do not explain why it should not work.
Diff: [diff_oidc-client-ts.d.ts.patch.zip](https://github.com/authts/oidc-client-ts/files/9008077/diff_oidc-client-ts.d.ts.patch.zip)

In the package.json `"types": "./dist/types/oidc-client-ts.d.ts",` was added to `"exports"` section, that might affect you.

Which version of TypeScript are you using? I am using `typescript@4.6.4` together with `oidc-client-ts@2.0.5` without problems.

**Comment by JulianBichl** [comment]
Thank you for your answer. I inspected the last commits and came to the result, that only in 2.0.5 the "types" was added to the export-section. But i'm using 2.0.4, and since yesterday i'm unable to use the oidc-client because of compliation error. I'm using version 3.9.3 :) Thank you for your help :)

**Comment by pamapa** [comment]
typedoc is only a dev dependency, so no problem.

Ideas to check:
- Sometimes `node_module` is damaged or some frameworks like react-script add cache data, which might get inaccurate. Remove your `node_module` and reinstall everything from scratch.
- Upgrade TypeScript to 4.6.4

The older 2.0.4 does not have the `"types": "./dist/types/oidc-client-ts.d.ts"`

**Comment by pamapa** [comment]
@Ic3xX Maybe you changed the `settings.loadUserInfo` to trigger this behavior. The error you get seems to be that your oidc server does not return metadata for `userinfo_endpoint`. You can verify this be enabling logging to debug. Its also possible to seed that metadata information, see `settings.metadataSeed`.

In any case you will need to provide more information.

**Comment by tomatualus** [comment]
Same error over here, when we rollback to 2.0.4, everything is fine.

**Comment by Ic3xX** [comment]
For me updating to 2.0.6 is working fine but also updating to 2.0.5 is now working. The code hasn't changed so far but maybe something has changed in our meta endpoint (azure).

**Comment by pamapa** [comment]
Nice to hear it works again for you
