### ISSUE TITLE
Typing issue: WebStorageStateStore.store should be an async store

### ISSUE THREAD

**Issue by Badisi** [authts/oidc-client-ts#609]
I'm trying to use my own custom store implementation where all the data has to be read/write in an async manner.

```ts
userStore: new WebStorageStateStore({
  store: new MyStore()
});
```

The issue I'm facing is that [WebStorageStateStore](https://github.com/authts/oidc-client-ts/blob/main/src/WebStorageStateStore.ts) uses async methods whereas [WebStorageStateStore.store](https://github.com/authts/oidc-client-ts/blob/main/src/WebStorageStateStore.ts#L13) uses sync ones as it is of type `Storage`.

**Solutions:**
1) I could make my own implementation of `WebStorageStateStore` but then I would loose or duplicate anything that this wrapper is doing -> so I don't really like that solution.
2) It seems that supporting an async store is already implemented as all the methods from `WebStorageStateStore` returns a `Promise.resolve` of the store's results (ex: [line 34](https://github.com/authts/oidc-client-ts/blob/main/src/WebStorageStateStore.ts#L34), [line 43](https://github.com/authts/oidc-client-ts/blob/main/src/WebStorageStateStore.ts#L43), ...).
-> so the ideal solution would be to replace the type of `WebStorageStateStore.store` and make it reflect an async `Storage` type instead

What do you think ?

**Comment by philjones88** [comment]
I'm too trying to think how best to handle this.

Scenario is I want to swap out the storage method for an async one so I can use oidc-client-ts in electron.

(I have to send and receive over IPC which is async)

**Comment by pamapa** [comment]
> What do you think ?

Makes sense. Would accept such a MR...

**Comment by philjones88** [comment]
@pamapa I had a go at swapping to async, I made an `AsyncStorage` interface to replace `Storage` and updated everything to `async`/`promise`. Is there an easy way to test this in my project? (The build/lint/test does pass)

**Comment by philjones88** [comment]
Ok managed to test it locally by using `file:/..` in my package.json and it works for me in Electron!

The web app uses IPC + Electron + Electron Store and I can see the data following to and from.

Also checking the JSON file electron-store creates I can see access tokens etc.

So I guess WOMM.

**Comment by philjones88** [comment]
@pamapa any chance of a relase soon? I want to ship our Electron app and currently i'm using a `file:/...` reference in my package.json. Thanks

**Comment by pamapa** [comment]
Will make a release next week. Monday should be doable.
