### ISSUE TITLE
Property 'currentUser' has no initializer and is not definitely assigned in the constructor.

### ISSUE THREAD

**Issue by wveinti-vtl** [authts/oidc-client-ts#617]
If somebody knows a solutions to this problem please help!
I tried using the exactly same packages as the example but nothing.

it breaks on this line 
currentUser: User;

on the app.component.ts

**Comment by pamapa** [comment]
This library does not contain `currentUser: User;`. You will need to provide much more context. First verify where the error occurs (in which code, yours, a library, which...)
