### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by brockallen** [authts/oidc-client-ts#62]
Hi all -- I see that you're working here on a successor to oidc-client. That's great!

Often people don't know the protocol well enough and miss nuances that was done in oidc-client, so I'm happy to answer any questions about why something might have been done a certain way.

Thanks.

**Comment by pamapa** [comment]
That support is offering is great, we really appreciate that! As you said there are many nuances. Our goal is to keep as much of the original API, design and features intact. We will post questions in this issue.

**Comment by pamapa** [comment]
The CordovaI feature looks broken. Do you know if somebody still needs that feature? I am thinking about removing this completely.

**Comment by pamapa** [comment]
What is the benefit for having an OidcClient **and** UserManager class? For the library it would be easier to have only one class...

**Comment by brockallen** [comment]
> The CordovaI feature looks broken. Do you know if somebody still needs that feature? I am thinking about removing this completely.

Yes, please remove it. AppAuth is the preferred way these days and is there is a reference implementation [here](https://github.com/openid/appAuth-JS) that people can use instead.

**Comment by brockallen** [comment]
> What is the benefit for having an OidcClient and UserManager class? For the library it would be easier to have only one class...

OidcClient is the protocol class, and UserManager adds session management on top. That was the intent for the separation.

**Comment by pamapa** [comment]
> 
> 
> > What is the benefit for having an OidcClient and UserManager class? For the library it would be easier to have only one class...
> 
> OidcClient is the protocol class, and UserManager adds session management on top. That was the intent for the separation.

I will make functions like createSigninRequest protected instead of public. Would mean if somebody wants to use it he must inherit from OidcClient like UserManager too, which makes sense. The exposed public API is cleaner though.

**Comment by brockallen** [comment]
> I will make functions like createSigninRequest protected instead of public. Would mean if somebody wants to use it he must inherit from OidcClient like UserManager too, which makes sense. The exposed public API is cleaner though.

The other thing you can do is just have the USerManager contain OidcClient instead. That way if someone is using OidcClient for raw protocol things, it's still usable.

**Comment by pamapa** [comment]
The SessionMonitor code `_start` looks for `user.session_state`. But not all authority servers return a user session_state. In those cases the SessionMonitor makes nothing. Also if it would do something the check interval of 2sec (default) seems very small.

I will disable monitorSession by default for now.

**Comment by elfico** [comment]
@pamapa great work here. I would love to contribute in any way. What work items can I pick and work on?

**Comment by pamapa** [comment]
@elfico Would be great if you find time for testing the 2.0.0-alpha2 or higher with your flow. Also reviewing the code regrading types would be nice. Additionally MonitorSession does not work when `user.session_state` is undefined and UserInfoService has a lot of duplicated code with ResponseValidator.

**Comment by selfrefactor** [comment]
I also want to move to this library, but I am using it with response type of `id_token`. Is that supported with this library, as it looks that only possible value is `code`?

**Comment by pamapa** [comment]
`response_type=code` + `scope=openid` should give back an `id_token`, which is supported.

**Comment by pamapa** [comment]
@brockallen i guess we should still support the `hybrid flow` aka `response_type=code id_token`?

**Comment by pamapa** [comment]
@brockallen v2.0.0 is now ready. Would be really nice if you could add a link from your `oidc-client` github project's `README.md` to this project. You may also add a `npm install` deprecated warning like:
```
npm WARN deprecated oidc-client@1.11.5: this library is no longer supported. Upgrade to oidc-client-ts.
or
npm WARN deprecated oidc-client@1.11.5: Please see https://github.com/IdentityModel/oidc-client-js#deprecated
```

**Comment by pamapa** [comment]
@brockallen  a friendly ping, have you seen my comment above?

**Comment by brockallen** [comment]
Hi, yes, sorry. What wording might you like on my side?

**Comment by pamapa** [comment]
Something simple in your [README.md](https://github.com/IdentityModel/oidc-client-js/blob/dev/README.md), replacing the chapter "Looking for a new maintainer":
```
## Development stopped

This project halted its development in June 2021. The successor project oidc-client-ts can be found [here](https://github.com/authts/oidc-client-ts).
```

And a `npm install` deprecated warning (see comment above) would be really nice, as not everybody is visiting repository pages of libraries all the time...
