### ISSUE TITLE
Silent Renewel making two calls immediately to token end point

### ISSUE THREAD

**Issue by VijayaSaiRam** [authts/oidc-client-ts#629]
Hi team, 

I am this library for oauth2.0 implementation . It has been observed that, some times it is making two successive calls to token -end point in silent renewal of access_token. 
Though first call is successful, it is making the second call immediately to get the access token and refresh token, 
and next time , 
when the refresh token used in the previous call is used in token rotation, I am getting the error response from server saying, 

**{"error_descirption":"Unknown, invalid or expired refresh token" , "error":"invalid_grant"}**

Could some one please help me to sort out this issue.

**Comment by pamapa** [comment]
Please enable logging or debug to find out the origin of the two calls. Without knowing where it is coming from its nearly impossible to help you...

**Comment by pamapa** [comment]
One call could be coming from `SilentRenewService` if `settings.automaticSilentRenew == true`, which is the default, the other one?

**Comment by VijayaSaiRam** [comment]
I am using only this library for authentication purpose.. This is not happening all the time. Sometimes , it is making two calls one after the other immediately even the first call is success..

**Comment by pamapa** [comment]
Might be relate to https://github.com/authts/oidc-client-ts/issues/430

**Comment by mparsakia** [comment]
I'm having this same issue.

**Comment by shreyalg10** [comment]
Similar issue here. It only happens once when user has logged in for the first time even if I don't have any other tabs/window open.
