### ISSUE TITLE
Access custom claims?

### ISSUE THREAD

**Issue by flindby** [authts/oidc-client-ts#639]
Our identity provider are returning some custom claims ('uid' and 'groups'), with the old library (oidc-client-js) we could access them with "user.profile.uid" and "user.profile.groups". Is this possible now with this library in some fashion?

**Comment by flindby** [comment]
Realized that you can access the claims from User.Profile:

`user.profile['uid'] as string` for instance

**Comment by olivier-voutat** [comment]
Tried to add loadUserInfo: true in our UserManagerSettings but not better @flindby 

https://authts.github.io/oidc-client-ts/interfaces/OidcClientSettings.html#loadUserInfo

**Comment by olivier-voutat** [comment]
Ok, ok, my bad. We have two places where we define settings. Was adding loadUserInfo: true only to one. @flindby
