### ISSUE TITLE
How to use UserManager with HashRouter in React?

### ISSUE THREAD

**Issue by HanCai98** [authts/oidc-client-ts#667]
Hi, I am working on a React project, and need to use auth service. Previously, I used `BrowserRouter`, everything is good. But for some reason, I need to change to use `HashRouter`, but this time, the login page seems get stuck. Does anyone have any idea? Really appreciate it!

<img width="1080" alt="Screen Shot 2022-09-01 at 23 37 25" src="https://user-images.githubusercontent.com/90488412/188054435-70ee2399-4087-40a2-b210-97e708fd49b6.png">
<img width="1028" alt="Screen Shot 2022-09-01 at 23 38 05" src="https://user-images.githubusercontent.com/90488412/188054449-c258d6dc-46c5-4e18-b149-2010bf550fa1.png">
<img width="774" alt="Screen Shot 2022-09-01 at 23 38 15" src="https://user-images.githubusercontent.com/90488412/188054450-a591ce8a-714d-400d-a8c4-cb1a93f5a125.png">

**Comment by pamapa** [comment]
Have you checked in the settings: `response_mode`: "query" vs "fragment"

**Comment by HanCai98** [comment]
Hi, @pamapa, thanks for your advice, I try to change my `userManager` settings (shown as below), but my login page still get stuck, in the browser, I have this error:

```
react_devtools_backend.js:4026 No routes matched location "code=qamaster_1963BE7834DB682D5011CD4D0C8E53CD21C62AE8166C5B0447FDB2AE722C9ED3&scope=openid%20profile&state=f834eb900d464ae2a9b123ef61297e02&session_state=ayY2RUc4OCX-2X4wUVyH2DVmmZ54BD4kmfMonsvXBGI.r-8Lg6TouvpkKhDfLNrhIQ"  
    at Routes (http://localhost:3000/static/js/bundle.js:59491:5)
    at AuthProvider (http://localhost:3000/main.45a79611680d96b316ae.hot-update.js:66:5)
    at Router (http://localhost:3000/static/js/bundle.js:59424:15)
    at HashRouter (http://localhost:3000/static/js/bundle.js:58267:5)
    at App
```

<img width="481" alt="Screen Shot 2022-09-02 at 10 06 02" src="https://user-images.githubusercontent.com/90488412/188166809-15673b27-57e0-4281-927c-c63a6441959a.png">

**Comment by HanCai98** [comment]
Add when I changed the `response_type`, I have a error like `singinPopup` only supports `code`

**Comment by pamapa** [comment]
`No routes matched location` i guess that is  routing problem of your own application. You need to ensure that this can be handled...

**Comment by frontendplace** [comment]
see solution i found and put in https://github.com/authts/oidc-client-ts/issues/734
