### ISSUE TITLE
Method signinRedirectCallback doesn't return state

### ISSUE THREAD

**Issue by weronikasabiniewicz** [authts/oidc-client-ts#668]
Method `this.userManager.signinRedirectCallback(url)` doesn't return user. state (it is always undefined)

In Java Script verion this method returns user state correctly.

**Comment by pamapa** [comment]
Works reliable here. You will need to debug or add full log and find out why it does not work on your side.

**Comment by weronikasabiniewicz** [comment]
Thanks for checking.

I know what a problem was.
Method `this.userManager.signinRedirect({ state: this.createArguments(state) });` now has strongly typed parameters. So, when you want to keep state, it must be in state property.

Now it works thanks.
