### ISSUE TITLE
Get custom claims after migration

### ISSUE THREAD

**Issue by ozergul** [authts/oidc-client-ts#680]
Hi everyone, I migrated our project from oidc-client-js, but we have missing claims here:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/8460954/189620968-5df82a05-1c1d-4061-809d-d279bf7b3bb6.png">
Does anyone know how we can solve this?

**Comment by ozergul** [comment]
Yeah I found this flag, and set it true at config:
loadUserInfo
I wish it is written in migration doc :)
Closing issue.

**Comment by pamapa** [comment]
> I wish it is written in migration doc :)
> Closing issue.

feel free to add a MR, to improv ethe migration doc, will help the next one :-)

**Comment by ozergul** [comment]
I will absolutely do this when I have free time!
