### ISSUE TITLE
The 'responseType' property on 'XMLHttpRequest': The response type cannot be changed for synchronous requests made from a document

### ISSUE THREAD

**Issue by Yaseern** [authts/oidc-client-ts#687]
We experience today oidc client sigingComplete throw below error and it pops for certain time, after that it automatically worked again without doing any changes from our end. This happed in all our environments (local/dev/qa/prod)

`this.userManager.signinRedirectCallback()` throw exception when in catch handle 

`the 'responseType' property on 'XMLHttpRequest': The response type cannot be changed for synchronous requests made from a document. `

Angular - 13.3.11
oidc-client-ts - 2.0.5

I want to know what cause for this issue. Please help me out to find the reason

**Comment by pamapa** [comment]
First find the location of the problem, which code did case that. Second find out which data did trigger this.

BTW: This library uses the modern fetch function and not the legacy XMLHttpRequest. But maybe fetch throws this as well. I guess you are not using any fetch replacement/pollyfil library...

**Comment by Yaseern** [comment]
'this.userManager.signinRedirectCallback()` this is where the error thrown, this issue cause I couldn't be able to login to the app due to this error.
I tried to find the issue but couldn't any place where the code is wrong. I used only the Angular HttpClient but don't know other libraries which might used different library.

**Comment by pamapa** [comment]
`this.userManager.signinRedirectCallback()` is not good enough for others to understand your problem. Where exactly (file+function+line) in the library `oidc-client-ts` comes the error from?
