### ISSUE TITLE
User profile information is lost when refresh token is used.

### ISSUE THREAD

**Issue by PrinceManfred** [authts/oidc-client-ts#688]
Hi!

I've run into an issue where the profile object on my User is empty after the refresh token is used to get a new access token. It looks like useRefreshToken in the client generates an empty SigninResponse and merges in the new access and refresh tokens to that object. That causes an empty profile to get returned when the new User object is created. Should we maybe include the profile in the RefreshState object so it can be merged into the new User? Or am I just doing something incorrectly. Thanks for the help!

**Comment by PrinceManfred** [comment]
Ah I think I understand better what's happening. The old id token isn't attached to the SiginResponse before validateRefreshResponse is called. Could we consider putting the original id token in if we haven't received a new one during renewal?

**Comment by pamapa** [comment]
The id_token is already part of state. See here https://github.com/authts/oidc-client-ts/blob/main/src/ResponseValidator.ts#L85

As id_token is optional, i guess it makes sense to copy over. Does adding something like this work?

```
        // OpenID Connect Core 1.0 says that id_token is optional in refresh response:
        // https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse
        const hasIdToken = response.isOpenId && !!response.id_token;
        if (hasIdToken) {
            this._validateIdTokenAttributes(response, state.id_token);
            logger.debug("ID Token validated");
        }
        else {
            // if there's no id_token on the response, copy over id_token from original request
            response.profile = JwtUtils.decode(state.id_token ?? "") as UserProfile;
        }
```

**Comment by PrinceManfred** [comment]
That works perfect for me.
