### ISSUE TITLE
AzureAD requesting token refresh with all received scopes from signin can be problematic

### ISSUE THREAD

**Issue by zmoore-usgs** [authts/oidc-client-ts#695]
I'm using oidc-client-ts for an application that logs users in using AzureAD. My signin request to Azure uses their special '.default' [scope](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#request-the-permissions-in-the-app-registration-portal) which provides all of the resource-specific scopes for the resource I'm requesting a token for.

One quirk related to using this scope is that when you make a request that uses it, it must be the _only_ scope in the token request, however the token response will list the `.deafult` scope _along with_ all scopes that it inherently provided.

I.E: 

Request:
```json
{
   ...
   scope: '<client_id>/.default'
}
````

Response:
```json
{
   ...
   scope: '<client_id>/.default <client_id>/User.Read <cliet_id>/User.Calendar'
}
````

This behavior itself is not an issue, however when trying to request a new token using the refresh token via oidc-client-ts the scope from the response is included in the refresh token request and this causees the refresh token request to fail from Azure because the request includes '.default' along with the other scopes.

My current workaround is to add an event listener for user load and overwrite the user's scopes with the scopes used in my initial request. I.E:

```javascript
userManager.events.addUserLoaded((user) => {
    user.scope = '<client_id>/.default'
    userManager.storeUser(currentUser)
});
```
This works but feels a bit clunky and feels like something that may be able to be handled better by the library.

I believe this behavior was added to oidc-client-ts [here](https://github.com/authts/oidc-client-ts/pull/365).

Some potential solutions I've pondered:

1. Providing some way to modify that behavior to use scopes from the initial signin request rather than scopes from the token response
2. Providing some way to explicitly define the scopes used for refresh requests

**Comment by pamapa** [comment]
Sorry for the long delay. Yes i agree your current workaround is only a workaround and we should add a proper solution. I would prefer the second solution "Providing some way to explicitly define the scopes used for refresh requests".

We can add a list of allowed scopes for refresh requests (filter list). Could we hard-code that list or must it be configurable? Maybe a list of **not** allowed scopes for refresh requests (filter list) hard-coded is the way to go starting with `[".default"]`

**Comment by timgrohmann** [comment]
We are currently facing the same problem, @zmoore-usgs's workaround works but feels clunky.

I would second @pamapa's suggestion on adding a configurable filter list. Since the `<client-id>` part from the original issue will vary, hard-coding is not possible. I think this is just Microsoft being Microsoft, but maybe other OIDC implementations use another special way in which scopes are modified.

I will try to come up with a PR on this issue.

**Comment by timgrohmann** [comment]
I provided a PR implementing my suggestion. Feel free to comment :)
