### ISSUE TITLE
Disable concurrent signinSilent()

### ISSUE THREAD

**Issue by miroljub1995** [authts/oidc-client-ts#710]
Our Auth server does not allow multiple concurrent requests to refresh access token using the same refresh token. It can happen because we use automatic silent renew and in some cases we call it manually.

If this is something that can be added to this library, here is a my proposal:
- if there is no active signin silent, start new and return promise
- if there is an active signin silent, return a promise of the current one without starting new one

We can not implement this proposal in our app because we do not have a way to wait for the current signin silent that is automated from this lib.

**Comment by pamapa** [comment]
In clients exposed to users (e.g. Web-applications) you should not use a refresh token. Yo can disable the automatic refreshing via settings and handle it by yourself using the events.

**Comment by miroljub1995** [comment]
Are you saying that we should use silent without refresh (using iframe)?

**Comment by pamapa** [comment]
> Are you saying that we should use silent without refresh token, like using iframe?

Yes, i would do that. As otherwise your client secret could be extracted from the exposed code...

**Comment by oylp1988** [comment]
+1
Is there any method to know if a silent signin is needed?

Here is the scenario,
1. user signed in
2. user closed the web page
3. user opened the web page

How can I know if there is an access token, or the refresh token is still valid if access token expires.

**Comment by oylp1988** [comment]
> ou saying that we should use silent without refresh token, like using ifram

@miroljub1995  hi bro, could you please elaborate what silent without refreshing token? you use iframe as the example. Can you provide some details?

**Comment by miroljub1995** [comment]
@pamapa what secret? We are using PKCE and receiving id + access + refresh tokens.

**Comment by miroljub1995** [comment]
@oylp1988 we have setup oauth server for issuing tokens. One client is public using PKCE and looks like there are two types of refreshing the access token.
- Using refresh token, which is fast and simple
- Using iframe without prompt (no need to enter username and password)
