### ISSUE TITLE
addUserLoaded not fired on UserManager.getUser() method

### ISSUE THREAD

**Issue by waldemarennsaed** [authts/oidc-client-ts#712]
## Issue

Apperently, the `addUserLoaded` event is not being fired whenever the `getUser()` method on the `UserManager` is being called.

## Solution

The `addUserLoaded` event should be loaded on every successful `getUser()` method response.

### General structure

Using the following setup:

* Vue 3
* oidc-client-ts (this project)
* Pinia
* Vue-Router 4
* (TypeScript)

### The implementation

Basically, using the following code-structure:

* `/src`
  * `UserManager.ts`
  * `/store`
    * `auth.ts`
    
**oidc.ts**
```typescript
// all imports
const settings: UserManagerSettings = { // ... }

const userManager: UserManager = new UserManager(settings)

// THIS only executes on signInCallback, never on the getUser() method that I use in `/src/store/auth.ts`
userManager.events.addUserLoaded((user: User) => {
  // retrieve some initial API data, or do a bunch of other stuff
})

export { userManager }
```

**auth.ts**
```typescript
import { pinia } from '@/src/store/index.ts'
import { defineStore } from 'pinia'
import { userManager } from '@/src/oidc.ts'

const authStore = defineStore('auth', {
  actions: {
    async checkIfUserIsAuthed () {
      // first check if your current route is any callback-route
      
      // now check if the user is already authed, by checking for a valid getUser() response !== null
      const user: User|null = await userManager.getUser()
    }
  }
})
```

The `checkIfUserIsAuthed` method get's executed by a route-handler, on every route-visit by using a `beforeRouteChange` handler on `vue-router`.

**The issue:** The `getUser()` method in `/src/store/auth.ts` get's executed on every page-reload after once authenticated, but it never triggers the `userLoaded` event anymore. Only after signing in.

## Finally

Am I doing anything wrong? Is there any misconception I have?

My current solution is using a `Proxy` `apply`-trap on `UserManager.getUser()` which checks if the result is `!== null` and then executes my logic. So I am intercepting/extending the `getUser()` functionality - but I guess the event should still be triggered.

Would be happy for an explanation, did I catch an issue here?

**Comment by pamapa** [comment]
The event `userLoaded` is not fired by intention/design of not breaking the behavior of the predecessor library `oidc-client`. It might could produce an endless loop: When you call `getUser` somewhere in your `userLoaded` callback function.

When your application is calling `getUser` you have control to do whatever you need to do. `userLoaded` is called inside the library when you have no direct control. e.g. "end of sign ok" or "refresh ok" or "revoke token".

We could optionally allow this by using `getUser(args: GetUserArgs = {})` where `type GetUserArgs = { raiseEvent? boolean }`. Default would be `false`. Because of the potential endless loop i am not so sure we should allow this...

What do other developers think about this.

**Comment by waldemarennsaed** [comment]
First of all: Thank you for the quick answer.

> It might could produce an endless loop: When you call getUser somewhere in your userLoaded callback function.

I don't see why a developer should use `getUser()` within the `userLoaded` callback, when the `userLoaded` callback _already_ provides the `user: User` result as a parameter to the callback.

> We could optionally allow this by using getUser(args: GetUserArgs = {}) where type GetUserArgs = { raiseEvent? boolean }. Default would be false. Because of the potential endless loop i am not so sure we should allow this...

That would be an option that I would agree on, if my latter thoughts have no weight.

**Comment by tobiaszuercher** [comment]
the user loaded is properly fired after a normal sign-in redirect.

let's assume the user gets stored in session or local storage. if you refresh the page, the event doesn't get fired.

this feels for me inconsistent. so i have now 2 ways to ensure that a logged in user is recognized by the app.

**Comment by alolis** [comment]
> the user loaded is properly fired after a normal sign-in redirect.
> 
> let's assume the user gets stored in session or local storage. if you refresh the page, the event doesn't get fired.
> 
> this feels for me inconsistent. so i have now 2 ways to ensure that a logged in user is recognized by the app.

Has anyone solved this elegantly? I would expect `addUserLoaded` to fire even after the session is loaded from local storage. Why is this not the case?

@tobiaszuercher , how did you approach this?

**Comment by ahoran3** [comment]
Agreed that a solution is needed for the scenario where a user is loaded from local/session storage. Currently the clients of this library are not notified.

In my case, after we have a user, I need to make a few determinations based on the user before proceeding deeper into the application. If a user refreshes the page currently, I am not informed to make this determination. 

My current workaround is to refresh the token a very short time after the base application l loads (refresh or directly after sign-in redirect), so that I can trigger my logic off of the currently available events. This workaround, however, requires redundant refresh calls and network dependencies when they are not needed.

**Comment by waldemarennsaed** [comment]
> > the user loaded is properly fired after a normal sign-in redirect.
> > let's assume the user gets stored in session or local storage. if you refresh the page, the event doesn't get fired.
> > this feels for me inconsistent. so i have now 2 ways to ensure that a logged in user is recognized by the app.
> 
> Has anyone solved this elegantly? I would expect `addUserLoaded` to fire even after the session is loaded from local storage. Why is this not the case?
> 
> [@tobiaszuercher](https://github.com/tobiaszuercher) , how did you approach this?

Hey there, sorry for my late reply. I solved it by creating a new `Proxy()` object which hooks onto the `getUser` event:

```typescript
const userManager: UserManager = new UserManager(settings)

export const getUserProxy = new Proxy(userManager.getUser, {
  apply (target, thisArg, args) {
    const user: Promise<User|null> = Reflect.apply(target, userManager, args)

    user.then((user: User|null) => {
      if (user !== null) {
        onUserLoadedHandler(user)
      }
    })
      
    return user
  }
})
```

But I consider this a workaround, if not even a hack.

> I agree that a solution is needed for the scenario where a user is loaded from local/session storage. Currently the clients of this library are not notified.
> 
> In my case, after we have a user, I need to make a few determinations based on the user before proceeding deeper into the application. If a user refreshes the page currently, I am not informed to make this determination.
> 
> My current workaround is to refresh the token a very short time after the base application l loads (on page refresh or directly after sign-in redirect), so that I can trigger my logic off of the currently available events. This workaround, however, requires a redundant `signinSilent()` call and additional network dependencies in my application logic in the case when a user had just logged in _(which triggers my needed user logic before the added `signinSilent()` call)_. I would not have to invoke the additional network calls and re-trigger my user-determination logic if I had a reliable way to know when this lib successfully finds and loads a user from the userStore.
> 
> _Really appreciate this library: **Thank you!**_

Using the proxy-solution should avoid the network-request and is a bit cleaner IMO, maybe something worth trying in your case?

@pamapa you closed this ticket as completed but neither of your suggestions was implemented as far as I know. Any plans on doing so? Otherwise.

I totally understand that my original suggestion will become a breaking change. IMO it's justified but a non-breaking-change would totally be preferred. Asking for updates 🆙

**Comment by waldemarennsaed** [comment]
I opened a PR for allowing passing a parameter `raisedEvent = false` (set to false by default for backwards-compatibility) to avoid the `Proxy()`:

https://github.com/authts/oidc-client-ts/pull/1817

**Comment by waldemarennsaed** [comment]
@pamapa any chance on re-opening this issue until e.g. #1817 is merged?

**Comment by waldemarennsaed** [comment]
Update: #1817 was merged 🥳 ❤
