### ISSUE TITLE
unable to reach https://demo.identityserver.io/.well-known/openid-configuration

### ISSUE THREAD

**Issue by vineeln** [authts/oidc-client-ts#721]
tried to run the sample in samples/Parcel, looks like its trying to reach https://demo.identityserver.io/.well-known/openid-configuration & it doesn't exist anymore.  Is there an alternate demo server that we should be using?

**Comment by pamapa** [comment]
@brockallen Did the URL (https://demo.identityserver.io) change? Do you still operate a demo server?

**Comment by philjones88** [comment]
what about https://demo.duendesoftware.com/.well-known/openid-configuration is that it?

**Comment by pamapa** [comment]
> what about https://demo.duendesoftware.com/.well-known/openid-configuration is that it?

Thanks for finding out. Could somebody create a merge request to adapt this?

**Comment by brockallen** [comment]
> @brockallen Did the URL (https://demo.identityserver.io/) change? Do you still operate a demo server?

that's gone. demo.duendesoftware.com is the replacement

**Comment by philjones88** [comment]
@pamapa raised a PR to replace with correct URL
