### ISSUE TITLE
using hash router, getting the parameters from the url is incorrect

### ISSUE THREAD

**Issue by frontendplace** [authts/oidc-client-ts#734]
Situation:
When the router is set to hashmode the parameters are not correctly parsed from the url.
and you get the error that the state is not found.

Analysing:
- UrlUtils.readParams expects an unhashed routed url

easiest way yo fix: 
const unHashUrl = url.replace('#/', '');
const response = new SigninResponse(UrlUtils.readParams(unHashUrl, this.settings.response_mode));

and 

const unHashUrl = url.replace('#/', '');
const response = new SignoutResponse(UrlUtils.readParams(unHashUrl, this.settings.response_mode));

**Comment by pamapa** [comment]
When i look at
```
export class UrlUtils {
    public static readParams(url: string, responseMode: "query" | "fragment" = "query"): URLSearchParams {
        if (!url) throw new TypeError("Invalid URL");
        const parsedUrl = new URL(url, window.location.origin);
        const params = parsedUrl[responseMode === "fragment" ? "hash" : "search"];
        return new URLSearchParams(params.slice(1));
    }
}
```
`UrlUtils.readParams` does support `hash`, see optional parameter `responseMode`. What is your `this.settings.response_mode`?

**Comment by frontendplace** [comment]
The response mode is mend to be for the stsservice urls. That is different then the urls for the callbacks (our site uses a hash routing /#/path?a=foo) fragment is used for hash parameters only. Like #a=foo. So for the stsmanager it needs query parameters and for the site too. The function tries to get the state and code parameters from the query part but when using hash routing the query parameters in the location = empty.

**Comment by pamapa** [comment]
@frontendplace thanks for clarification

The js library did this for that case: https://github.com/IdentityModel/oidc-client-js/blob/dev/src/UrlUtility.js#L34-L40

Does something like this work too (untested)?

```
export class UrlUtils {
    public static readParams(url: string, responseMode: "query" | "fragment" = "query"): URLSearchParams {
        if (!url) throw new TypeError("Invalid URL");

        if (responseMode == "query") {
            // if we're doing query, then strip off hash fragment before we parse
            idx = url.indexOf("#");
            if (idx >= 0) {
                url = url.substr(0, idx);
            }
        }

        const parsedUrl = new URL(url, window.location.origin);
        const params = parsedUrl[responseMode === "fragment" ? "hash" : "search"];
        return new URLSearchParams(params.slice(1));
    }
}
```

**Comment by frontendplace** [comment]
You can try it in the unit test. With url http://foo/#/bar?baz=param1

Removing the hash. You get http://foo//bar?baz=param1 
Then the search params are correct. Yes

**Comment by pamapa** [comment]
@frontendplace ok lets use remove `#/`

Please adapt your merge request, as such that the the replacement is done within the `UrlUtils.readParams` with a comment why this is needed and a unit test...

**Comment by frontendplace** [comment]
I will do that

**Comment by frontendplace** [comment]
I have changed it an tested with 

`        if (responseMode == "query") {
            const hashIdx = url.indexOf("#");
            if (hashIdx >= 0) {
                url = url.substr(hashIdx + 1);
            }
        }`

**Comment by longsleep** [comment]
Follow up here for further discussion on my comments on the merge request https://github.com/authts/oidc-client-ts/pull/736#discussion_r1010189305

To sum it up, the described case seems invalid as the URL in the example at https://github.com/authts/oidc-client-ts/issues/734#issuecomment-1295241647 does not have a query parameter and imo it is not the job of this library to fix special client side URLs.

See https://www.rfc-editor.org/rfc/rfc3986#section-4.1 for reference.

**Comment by frontendplace** [comment]
The url with /#/ notation is a regular used url in hash routed angular apps. So the url should be corrected to a kind of url mentioned in your comment prior to getting the parameters. Like it was also dealed with in the previous js version.

**Comment by longsleep** [comment]
Yes - the hash based url routing is common. I am just saying that the URL having ? after the hash # start is client specific and thus needs to be dealt with on the client code which expects to retrieve such and not in a generic library. 

If you receive callback requests from an IdP which appends query mode parameters 'at the end' instead of at the correct place for query parameters before the hash, I suggest you open an issue there too.

I am open to discuss possible solutions which avoid side effects when an URL is correctly generated as imo we should support the correct order first and foremost.

**Comment by frontendplace** [comment]
Maybe I do not understand. Do y mean the fix must be outside the urlUtils. Or outside the oidc-client.ts library as a whole?  The previous version supported (normal) angular syntax with first hash then a route then ? & separated parameters. The oid-clientts library takes care or redirecting with callback urls.

**Comment by longsleep** [comment]
Yes, i mean outside of oidc-client-ts as a whole. To my knowlege oidc-client-ts does not do anything Angular specific. Thus the actual integration into routing is done "outside". There a "fix" can also be made but also that fix is very specific to wrong behavior of the IdP you seem to be using.

To make an example with the URL `http://foo/#/bar?baz=param1` from above.

Let's assume you register/provide `http://foo/#/bar` as callback URL (which is configured via application specific URL routing to trigger the oidc-client-ts authorize callback) to the IdP. 

If the IdP redirects back to `http://foo/#/bar?bar=param1` then the IdP simply has "appended" the query. This is wrong and it means that the IdP does not support hash based URL routing as it generates the redirect URL wrong.

Instead a correct IdP would generate `http://foo/?bar=param1#/bar` which works prefectly fine as the query is now at the correct place and will be processed correctly while before there was just some additional application specific data inside the hash. 

oidc-client-ts has no idea what and how to process this application specific hash data and thus imo nothing should be added for it, even if this behavior might be common. 

Instead i suggest that whatever angular code you are using to trigger the oidc-client-ts callback, there you can modify the URL to the application specific needs.

**Comment by frontendplace** [comment]
Ok sorry to hear y don't want to support the angular way of hash routing like the previous version did and other libraries do. 

http://foo/?bar=param1#/bar you suggest won't be parsed as a correct url for angular routing. 

Is it possible you add to your readme.md that y don't support hash routing urls with parameters anymore? That will prevent a lot of time wasted for other developers that want to change from the previous version to this ts version.

**Comment by longsleep** [comment]
@frontendplace i think we need to know more to find a suitable solution which does not complicate using this library while at the same time does not introduce any specific hacks to the code base.

Regarding the router.implementation, can you share details or a link to some example with angular url routing? I find it hard to believe that the angular has based url routing would not support query parameters. Maybe play around with the location of the slash(es)?

**Comment by longsleep** [comment]
For completeness, i also suggest to investigate if you can use `response_mode` `fragment` (https://authts.github.io/oidc-client-ts/interfaces/OidcClientSettings.html#response_mode) to see if you can avoid the issue altogether and potentially avoid the issue that the IdP generates wrong callback urls in `query` mode.

And last not least, in the oidc-client-ts Angular example application https://github.com/authts/sample-angular-oidc-client-ts/blob/c9b21715c19fd68af0a9b4d4b9fedaa815e52592/src/app/core/components/signin-callback.component.ts#L14 this is the place where you would need "fix up" any invalid/wrong callback URL. The reason why the callback URL might need fixing is a combination of URL routing needs and potentially wrongly generated URLs by the IdP in question (especially when the configured callback URL contains a hash).

**Comment by frontendplace** [comment]
This is part of documentation of angular that explains the routing strategy. https://angular.io/api/common/HashLocationStrategy

A path is placed after the hash. 

The url that we get back from the stsserver is domain/apppath#/signin-callback?code=foo&status=bar.

**Comment by frontendplace** [comment]
This is a presentation

https://codecraft.tv/courses/angular/routing/routing-strategies/

**Comment by longsleep** [comment]
> This is part of documentation of angular that explains the routing strategy. https://angular.io/api/common/HashLocationStrategy

Yes, but that documentation is lacking. It does not say anything about query support or what if someone wants to use an additional set of hash values.



> The url that we get back from the stsserver is domain/apppath#/signin-callback?code=foo&status=bar.

OK, this is wrong. I don't know what stsserver is but it obviously does not expect the callback URL to end with a hash and adds the query parameter at the wrong place.

If you want to support this in your specific application it can work without problem. Simply process the URL before passing it along to `signinCallback`.

**Comment by frontendplace** [comment]
Oh I think there is a solution for us. I see that calling the signinRedirectCallback function I can pass a modified url.
Default the window location href is used and that includes the hash

**Comment by pamapa** [comment]
@longsleep Thanks for your excellent help here!

**Comment by longsleep** [comment]
You are very welcome - closing this.

**Comment by netcore-jroger** [comment]
> Oh I think there is a solution for us. I see that calling the signinRedirectCallback function I can pass a modified url. Default the window location href is used and that includes the hash

thanks! When use Vue.js or React.js's HashMode Use the following code work fine.
```js
mgr.signinRedirectCallback(window.location.href.replace('/#/','/'));
```
