### ISSUE TITLE
How to get more user info from authentication server

### ISSUE THREAD

**Issue by ngong11** [authts/oidc-client-ts#740]
I am migrating our application from oidc-client-js to oidc-client-ts. With the JS version, authentication server can return custom user information via "profile" of User, but with TS version, it can't because profile structure is defined. Could you tell me how to get more user information from server?

**Comment by oylp1988** [comment]
+1.

**Comment by pamapa** [comment]
Have you read this https://github.com/authts/oidc-client-ts/blob/main/docs/migration.md?

Specifically, some settings changed its default. e.g. default of `loadUserInfo` changed from `true` → `false`

**Comment by alex-eliot** [comment]
You need to pass in scopes while creating your UserManager:

```ts
export const manager = new UserManager({
  authority: "<your_authority_url>",
  client_id: "<your_client_id>",
  redirect_uri: "<your_redirect_uri>",
  // Here is where you can define your scopes
  scope: "openid email groups profile roles",
});
```
