### ISSUE TITLE
revokeTokensOnSignout with google cause  Token expired or revoked error 

### ISSUE THREAD

**Issue by xmlking** [authts/oidc-client-ts#753]
with following google OpenID setup, I am getting `Token expired or revoked` error when I enabled `revokeTokensOnSignout`

```
const userManager = new UserManager({
	authority: 'https://accounts.google.com',
	client_id: googlAuthConfig.client_id,
	client_secret: googlAuthConfig.client_secret,
	redirect_uri:  window.location.origin,
	post_logout_redirect_uri: window.location.origin,
	scope: 'profile openid email',
	filterProtocolClaims: true,
	loadUserInfo: true,
	// accessTokenExpiringNotificationTime: 300,
	// silentRequestTimeout: 20000,
	metadataSeed: {
		// end_session_endpoint: 'https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout',
		end_session_endpoint: 'http://localhost:5173'
	},
	extraQueryParams: { access_type: 'offline', prompt: 'consent' },
	revokeTokensOnSignout: true
});
```

<img width="949" alt="image" src="https://user-images.githubusercontent.com/627951/200148107-d514ba69-c3fa-4658-85f5-3834cc38728d.png">

**Comment by pamapa** [comment]
I see access token revoked successfully. Looks like you can not revoke the refresh token, which is not unusual, you can configure this via `revokeTokenTypes`

See https://github.com/authts/oidc-client-ts/blob/ec554af1502f73105c3c39fc46741dc5edd0053c/src/UserManagerSettings.ts#L66-L73

**Comment by xmlking** [comment]
works without error after adding `revokeTokenTypes` 
```
	revokeTokenTypes: ['access_token'],
	revokeTokensOnSignout: true
```
Thanks
