### ISSUE TITLE
signinSilent using refresh token clears profile info

### ISSUE THREAD

**Issue by MathiasFrost** [authts/oidc-client-ts#754]
I have a question.

1. I call signinPopup and log in.
2. User is stored in localStorage with id_token, access_token, refresh_token as well as decoded user info from id_token stored as a profile object.
3. Call signinSilent.
4. oidc-client-ts exchanges the refresh_token for a new access_token and a new refresh_token.
5. localStorage is updated with a new refresh_token and access_token, but the profile object is now empty _(id_token was unchanged)_.

Is that supposed to happen and am I doing something wrong?

Thank you.

**Comment by MathiasFrost** [comment]
Thanks for the answer.   
Yes, I read through the previous issues related to this, which is why I am scratching my head at this.
I am using version 2.1.0 which is a recent release.

My guess from the method you referenced is that in my case we do not get past this if: https://github.com/authts/oidc-client-ts/blob/ec554af1502f73105c3c39fc46741dc5edd0053c/src/ResponseValidator.ts#L85

I'm not familiar with that part of the response. Will do some debugging :)

**Comment by MathiasFrost** [comment]
Okay, so I'm relatively certain of what is happening:
1. The response from identity provider when exchanging refresh_token does not contain id_token at [this](https://github.com/authts/oidc-client-ts/blob/main/src/OidcClient.ts#L174 ) point.
2. [response](https://github.com/authts/oidc-client-ts/blob/main/src/OidcClient.ts#L180) is created with field [profile](https://github.com/authts/oidc-client-ts/blob/ec554af1502f73105c3c39fc46741dc5edd0053c/src/SigninResponse.ts#L47) initialized at ctor as empty object.
3. Scope does not contain openid, which means we do not enter [this if](https://github.com/authts/oidc-client-ts/blob/main/src/ResponseValidator.ts#L85).
4. This results in the profile field containing values is [overridden](https://github.com/authts/oidc-client-ts/blob/main/src/UserManager.ts#L270) by the empty object mentioned in step 2.

So the question if is this is by design or not.
In my case I am using Azure AD and can't ask for openid at the same time as a resource _(secured API)_.

**Comment by pamapa** [comment]
The if `if (response.isOpenId) { ` is there for historically reasons and i never saw a real world use-case to change that. Now i know such a case. I guess we can remove that if together with `...response.isOpenId &&...`

Can you test this first and if all good providing a merge request?

**Comment by MathiasFrost** [comment]
Sure, but I'm not sure I know what you mean by
> ...together with `...response..isOpenId &&...`

Care to elaborate?

**Comment by pamapa** [comment]
@MathiasFrost I have added a merge request, can you please test if that helps you?

**Comment by MathiasFrost** [comment]
> @MathiasFrost I have added a merge request, can you please test if that helps you?

Aye, works perfectly ^^
