### ISSUE TITLE
loadUserInfo not passing token in header

### ISSUE THREAD

**Issue by andymills** [authts/oidc-client-ts#762]
Hi, I'm using this library in a react app and have managed to get it to authenticate and return to the site, but when I have the loadUserInfo: true. I get a fetch failed error. It shows as being related to CORS, but using fiddler to help debug, the response body contains Missing_OAuth_Token and the request doesn't appear to have an authorization header. I'm using Salesforce as the server.

Should the library be putting the authorization header on a userinfo endpoint request. I've turned on logging(debug) but I don't get any entries that help except for [JsonService] getJson: Network Error.

Any ideas what to try or where to look in the code?

Thanks
Andy

**Comment by pamapa** [comment]
The CORS  error, probably mean you need to whitelist your site within your authz server...

**Comment by Sojborg** [comment]
@andymills This have been fixed in the [2.2.0 release](https://github.com/authts/oidc-client-ts/pull/778). Set the fetchRequestCredentials setting to 'include' and you should be good to go. I had the exact same issue.
