### ISSUE TITLE
RFC8707 - Possible Missing Multiple Resources handling for Code Flow Authorization Request

### ISSUE THREAD

**Issue by tebeco** [authts/oidc-client-ts#769]
Hello,

My question might be totally naive, but here I go:
We have an SSO from which we're gettings Access/Refresh/Id token in order to later call 2 Services.
We're trying to add the `resource` information as part of the AuthCode Grant during signing in order to generate dedicated token(s ?) to hit both ApiOne and ApiTwo. (see image above from the RFC)
[RFC 8707 - Resource Indicators for OAuth 2.0](https://www.rfc-editor.org/rfc/rfc8707.html)
![image](https://user-images.githubusercontent.com/2266487/202176864-d9fc43a8-cc7e-483d-a4b0-07b207d22375.png)

(On refresh the same will apply by sending the last valid refresh token + the appropriate resources)

My question being ... how can this be achieved with the library today for both SignIn, Refresh, etc ...
From the `OidcClient.ts` `resource` seems to be a simple string here:
https://github.com/authts/oidc-client-ts/blob/0e6bfc22ba2181bf52934b1666ac61d9a0a92069/src/OidcClient.ts#L37

and it seems to be forwarded
https://github.com/authts/oidc-client-ts/blob/0e6bfc22ba2181bf52934b1666ac61d9a0a92069/src/OidcClient.ts#L111

And I cannot find the could mapping that to the `&resource=`

**Comment by pamapa** [comment]
Correct currently the `resource` can only be `undefined` or `string`. I would accept a patch to also allow `string[]`

**Comment by tebeco** [comment]
few questions:

1) if I change `resource` from `string?` to `string[]?` is will be a breaking change right ?

2) Would it be better to add `resources: string[]` (with an `s`) and make `resource` obsolete?
the code should generate the equivalent of the following pseudo code in the URL:
```ts
const resourceQueryString = resources.map(res => `&resource=${res}`)
```

Scenario:
3.1) Only `resources` is passed => all ok
3.2) if only `resource` is set
  * Should I console.warn ?
    * idea: force consumer to update to get rid of the warn until next major remove `resource` ?
    * Do you plan to always ever have both and thus no warn ?
    * code would basically do `resources = [ resource ]` + mapping above
3.3) Both are passed
  * error ?
  * unavoidable warning + concat of array + string ?
    `const actualResources = [ ...resources, resource ]`
  * unavoidable warning + discard of `resource` and only use `resources ?

**Comment by pamapa** [comment]
Option 3: I thought to extend resource like this: `public readonly resource: string | string[] | undefined;`. Then the library can handle it, by checking the type at runtime...

If option 3 does not workout to  a simple solution, we can discuss the other options...

**Comment by pamapa** [comment]
to be more precise: the runtime check if array or not should probably be done at the "bottom", namely within `SigninRequest`...

**Comment by tebeco** [comment]
so far I've done
```ts
        const resources = (typeof resource === 'string')
            ? [resource] // wrap single string into an array
            : Array.isArray(resource)
                ? resource // use the array as/is if it's alreay one
                : []; // make an empty array for any other possibility

        // https://datatracker.ietf.org/doc/html/rfc8707
        // resource: Indicates the target service or resource to which access is being requested. Its value be an absolute URI, as specified by Section 4.3
        resources
            .filter(res => res?.length ?? 0 > 0)
            .forEach(res => {
                parsedUrl.searchParams.append("resource", res);
            });
```

But I'd like some input on potential existing ... either bug or intentional forwarding:

https://datatracker.ietf.org/doc/html/rfc8707
resource: Indicates the target service or resource to which access is being requested. Its value be an absolute URI, as specified by Section 4.3

current code will not care if `resource` is empty or whitespace an generate a `?resource=`

![image](https://user-images.githubusercontent.com/2266487/202454285-fcdad8ec-f6af-4693-a0d6-c33f0e2139f4.png)


is that intentionnal to forward all value and let the Authority fail and let the developper have the actual Authority feedback on that ?
should I keep or remove that `.filter(res => res?.length ?? 0 > 0)` ?

**Comment by pamapa** [comment]
@tebeco I would say shit in shit out: The resource is coming directly from the developer.

I think its better to just check for `Array.isArray(arr)`:

```js
// https://datatracker.ietf.org/doc/html/rfc8707
const resources = Array.isArray(resource) ? resource : [resource]
resources
  .forEach(r => parsedUrl.searchParams.append("resource", r));
```

**Comment by pamapa** [comment]
@tebeco i have created a merge request with this information, can you please test if it works for you?

**Comment by tebeco** [comment]
> @tebeco i have created a merge request with this information, can you please test if it works for you?

hey thx
sorry i got carried away at work i think i had most of it locally at some point / switched computer 

i'll ping colleagues so we can make a round and try it out

our main focus will probably be able to ensure how we can refresh an access token with all that

**Comment by tebeco** [comment]
thx @pamapa 
the assigned dev here was not able to test the change, I notice that I forgot to ping you back last time

Thx for having merging it in the meanwhile ;)

I'll try to keep you posted anyway later on
