### ISSUE TITLE
Supply dist builds

### ISSUE THREAD

**Issue by mattmshell** [authts/oidc-client-ts#777]
Thanks for taking on and maintaining this essential JavaScript project.

I'm in the midst of monkey patching a compiled JavaScript application that doesn't support OIDC with `oidc-client-ts`. Because the application is pre-packaged, it doesn't have a toolchain and therefore I can't readily integrate this project.

oidc-client-js included [dist copies](https://github.com/IdentityModel/oidc-client-js/tree/dev/dist) builds. Do you have bandwidth to do the same?

**Comment by pamapa** [comment]
Have you tried https://cdnjs.com/libraries/oidc-client-ts/2.1.0?

**Comment by mattmshell** [comment]
That's the build I've embedded. Would be nice to rely on this project as the source rather random CDNs.

**Comment by pamapa** [comment]
dist is something which we generate at release/publish time, we have not intention to add this back to the git repo...

**Comment by Badisi** [comment]
If all you want is to get a dist of that package as a tarball, you can either:

- download it directly (no tools needed): https://registry.npmjs.org/oidc-client-ts/-/oidc-client-ts-2.1.0.tgz
- download it with **npm**: `npm pack oidc-client-ts`

**Comment by mattmshell** [comment]
Thanks!
