### ISSUE TITLE
Extra Params getting ignore on redirect

### ISSUE THREAD

**Issue by jmastiholimath** [authts/oidc-client-ts#781]
Hello,

I am trying to use extra params with

redirect_uri = ‘https://test.com/callback’
usermanager.signinRedirect({extraQueryParams: {app: “test”}})

I see the extra params on the authorization code flow /authorize/connect?https://test.com/callback?app=test&code_challenge=..

but while on response header  location is https://test.com?code=..&state=..&scope.. because of that on actual redirect don’t see the extraParam app=test

How to fix the ignored extra params on actual redirect?

**Comment by pamapa** [comment]
The response is coming from the authz server. You need to read your authz docu if that is even possible. I guess there is not much we can do in this library...

**Comment by Badisi** [comment]
Like @pamapa said, those extra query params are to be consumed by the authz server. It is unlikely that the authz server send them back in the redirect.

Have you tried to include the extra query param directly in the redirect uri ?
> redirect_uri = 'https://test.com/callback?app=test'

**Comment by jmastiholimath** [comment]
Thanks @pamapa @Badisi , I tried adding param to callback redirect uri it says “Invalid redirect_uri”

**Comment by Sojborg** [comment]
@jmastiholimath which functionality are you trying achieve? What do you need the extra params for? 

If you need it to store some state from your web app so you can use it again after the user logged in (for example which path the user was on before logging in/relogging in) you can use the [state property](https://authts.github.io/oidc-client-ts/interfaces/CreateSigninRequestArgs.html#state).

**Comment by jmastiholimath** [comment]
thanks @Sojborg I fixed it by adding callback page in the other app that shares the same domain
