### ISSUE TITLE
Optional PKCE

### ISSUE THREAD

**Issue by liviozanol** [authts/oidc-client-ts#783]
As stated on the migration document (https://github.com/authts/oidc-client-ts/blob/main/docs/migration.md) PKCE should be optional even when using code type.

How to config oidc-client-ts to not send code_challenge, code_challenge_method, etc. to the identity server? 

Tried to set code_verifier to false but it didn't make any difference.

Thanks in advance.

See also: https://github.com/IdentityModel/oidc-client-js/issues/1360

**Comment by pamapa** [comment]
The [Authorization Code Grant](https://oauth.net/2/grant-types/authorization-code/) code path is using PKCE, there is no alternative code path in the library, which can be enabled.


This library focuses on [OAuth 2.1](https://oauth.net/2.1/), which says:
- PKCE is required for all OAuth clients using the authorization code flow

**Comment by liviozanol** [comment]
Ok. got it. So maybe it is a good idea to change the migration.md description?

It clearly says "PKCE remains optional"

**Comment by pamapa** [comment]
would be great if you make a merge request and fix that in the documentation!

**Comment by Moshyfawn** [comment]
Is #789 enough to explain the `code` flow change as per https://github.com/authts/oidc-client-ts/issues/783#issuecomment-1333313793?
