### ISSUE TITLE
AWS Cognito  - got it working

### ISSUE THREAD

**Issue by paulsperanza** [authts/oidc-client-ts#802]
Just in case anyone is running into issues getting this to work with AWS Cognito, I ended up having to add the metdata settings for the UserManager. This works on my laptop for http://localhost:4200 so that is what YOUR_APP_URL would have for me. Make sure in the AWS Cognito console, you set the Allowed callback URLs and Allowed sign-out URLs in the Hosted UI section of you App Client.

Here is what I used:
```
         metadata: {
            authorization_endpoint: `https://YOUR_DOMAIN/oauth2/authorize?response_type=code&client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_APP_URL/signin-callback`,
            end_session_endpoint: `https://YOUR_DOMAIN/logout?client_id=YOUR_CLIENT_ID&logout_uri=YOUR_APP_URL/logout-callback`,
            issuer: `https://cognito-idp.us-east-1.amazonaws.com/YOUR_USER_POOL_ID/`,
            jwks_uri: `https://YOUR_DOMAIN.well-known/jwks.json`,
            token_endpoint: `https://YOUR_DOMAIN/oauth2/token`,
            userinfo_endpoint: `https://YOUR_DOMAIN/oauth2/userInfo`
         },
```

**Comment by pamapa** [comment]
awesome! Would be great if you could improve the documentation, there is already a section for AWS Cognito: https://authts.github.io/oidc-client-ts/#provider-specific-settings

**Comment by Hellrasier** [comment]
Is this more detailed documentation to use with aws cognito? After signinRedirect() my i have userManager.getUser() returned null. While keycloak service returns me a user

**Comment by matthew-mcdermott** [comment]
This helped me out a bunch, however i also had to include a "revocation_endpoint" in the metadata tag:
`revocation_endpoint: `https://YOUR_DOMAIN/oauth2/revoke``
