### ISSUE TITLE
using id_token's expire time instead of access_token's expire time 

### ISSUE THREAD

**Issue by xmlking** [authts/oidc-client-ts#806]
we are passing `id_token`  to our backend as `access_token` generally not a valid JWT token ( e.g., Google IDP) or `access_token` don't have enough claims (PingID and others) 

For my case,  PingID OIDC, `id_token` expire in **30** min vs `access_token` expire in **5** min.

Our server redirect to login page when it receive expired  `id_token`  (after 5 min) , but browser/client think the session is still valid and bypassing login process and setting same  `id_token`  (not expired)  and `access_token` (expired) 

This cause infinite loop 

My ask is to support `oidc-client-ts settings` to use id_token's expire time instead of assess_token's expire time

**Comment by pamapa** [comment]
Please read https://auth0.com/blog/id-token-access-token-what-is-the-difference/. Specifically "What Is an ID Token NOT Suitable For?"...

**Comment by xmlking** [comment]
I am using `id_token` as a session token for a stateless full-stack app (nextJS or Sveltkit) , not using it for calling APIs as the link suggests. 


Kubernetes UI app use uses the `id_token` (not the `access_token`) for calling its backend. 
https://kubernetes.io/docs/reference/access-authn-authz/authentication/
