### ISSUE TITLE
Infinite loop on login error

### ISSUE THREAD

**Issue by franck102** [authts/oidc-client-ts#807]
Using oidc-client in a Vue 3 app I am seeing an infinite loop on login errors. I may well be misusing the library, but I don't see what I am doing wrong.
Basically the redirect_url is called on the iframe used for silent signon, which loads my Vue app in the iframe, which creates a new UserManager and the loop starts:

`Vue App STARTING AT: {"ancestorOrigins":{},
    "href":"http://localhost:8080/bookings/services/16/slots/89/schedules/171?date=2022-12-26","origin":"http://localhost:8080"}

Vue App STARTING AT: {"ancestorOrigins":{"0":"http://localhost:8080"},
   "href":"http://localhost:8080/login-cb?error=login_required&state=f1d0c53145e14ba49709e7092025d547",...}

Vue App STARTING AT: {"ancestorOrigins" {
    "0":"http://localhost:8080",
    "1":"http://localhost:8080"},
  "href":"http://localhost:8080/login-cb?error=login_required&state=d09b62bafc094842b20f624a15018f76",...

Shouldn't the redirect target the top-level window of the app? Here is how I create the UserManager:

```
const userManager = new UserManager({
    userStore: new WebStorageStateStore({store: window.localStorage}),
    authority: "http://localhost:50095/realms/myrealm",
    client_id: "myrealm-public",
    monitorSession: true,
    redirect_uri: "http://localhost:8080/login-cb",
    post_logout_redirect_uri: "http://localhost:8080/logout-cb",
    // popup_redirect_uri: "http://localhost:8080/popup-cb",
    response_type: "code",
    automaticSilentRenew: true,
    // silent_redirect_uri: "http://localhost:8080/silent-cb",
    scope: "openid",
    // loadUserInfo: true
})
```

/login-db is a regular Vue 3 Router route, with a navigation guard:

```
    if (to.path === "/login-cb") {
        return await handleLoginRedirect()
    }
```

... which simply calls signinRedirectCallback:

```
    async function handleLoginRedirect() {
        log.debug("Received login redirect from OIDC")
        try {
            const u = await userManager.signinRedirectCallback()
            log.info("User signed in: " + JSON.stringify(u.profile.preferred_username))
            return u.state
        }
        catch (e) {
            log.error("OIDC client error in callback: " + e)
        }
        return "/"
    }
```

**Comment by pamapa** [comment]
What is happening with the return of `handleLoginRedirect`? Aka `return u.state` looks fishy.

PS: Keep in mind, that the initial login is **not** done via an iframe, The iframe is only used for salient renews.

short summary of the library flow:
- your app -> `signinRedirect` -> authz (passing redirect uri via param)
- authz -> callsback your app -> `signinRedirectCallback` (handles response and gets access token)

**Comment by franck102** [comment]
Hi @pamapa,
I am passing the URL of the secure page that triggered the login in the state, hence the return u.state which will be handled by the router.

I think I now understand my mistake, and maybe the documentation could use some improvement. I had been assuming that the library would install the iframe html itself, and would use some browser API (e.g. postMessage) to come back to my main window and invoke the signing callback in the original app.
It seems that instead the callback will be called directly by Keycloak, and that I am responsible for providing a small HTML callback page myself - one that doesn't reload my entire app?
The flow you mention:
"authz -> calls back your app" won't work for me since "my app" creates a UserManager early in its initialization; so I need to at least detect that callback URL to bypass the normal initialization.
If I understand the flow correctly, who is responsible for eventually closing the iframe, will the library do that as soon as signinRedirectCallback returns?

**Comment by pamapa** [comment]
> If I understand the flow correctly, who is responsible for eventually closing the iframe, will the library do that as soon as signinRedirectCallback returns?

Please note that the iframe is only used in case of a silent re-new (without refresh token case). The library creates the iframe and also removes it after its no longer needed.

**Comment by franck102** [comment]
Ok, i have switched to using refresh tokens and the issue has indeed disappeared.

**Comment by Kingside88** [comment]
Can you share your'e full implementation please? I struggle a lot with keycloak and oidc-client-ts

**Comment by eivanovue** [comment]
Hi, I've been having a similar issue to this. Are you able to provide some more details as to how you were able to overcome it? Thanks!
