### ISSUE TITLE
How to get PKCE data

### ISSUE THREAD

**Issue by vanminhquangtri** [authts/oidc-client-ts#808]
First of all, I would like to send my thanks to this libary.

I am using this libary to implement SSO login for my Nuxtjs App (v2). I already sign in successful to get the authorization code from authorization server.

My problem is: after get the code, I need to send another api to my internal server to get access token, the params for this api must be include PKCE data that is used when sign in into the authorization server (code_verifier, state,...). 
I tried to use data from local storage as I see there's a item named 'oidc._id' created in localstorage. But the response of api to get access_token is always 401. And my back-end team claims that the PCKE data is not correct.

So I would like to know how can I get the PCKE data that is used when I signing in into the authorization server. I really need it to compare with the params of api get acess_token to internal server.

Or can I get the full URL of the authorization_endpoint that is sent by oidc-client-ts, it look likes:
mydomain/auth?client_id=id&redirect_uri=uri...

Thank you so much

**Comment by ximbong91023** [comment]
@vanminhquangtri did you manage to solve this? ran into the same problem
