### ISSUE TITLE
oidc-client issue in ssr(nextjs)

### ISSUE THREAD

**Issue by adibamine** [authts/oidc-client-ts#809]
I have two applications, one using react js(spa) and another one using nextjs(ssr).
i have integrated keycloak successfuly in both apps, however i´ve noticed that in the nextjs app, the user session is lost between tabs, i mean that if i login and then opened a new tab in the same navigator, i won t be connected in the new one. I guess that s caused by the userStore which is localstorage by default, maybe it needs to use cookies instead i ssr case.

Is there a workaround for this?
Thank you

**Comment by Kingside88** [comment]
can you share your'e keycloak implementation please
