### ISSUE TITLE
Improve example

### ISSUE THREAD

**Issue by bastien-m** [authts/oidc-client-ts#816]
The code sample in the repository is still using javascript and IMO miss some basics examples of usage and configuration.

My case was to use the `UserManager` and renew the token and it was not that easy to understand how to do this simple use case. I manage to do this by looking at the code. I guess it should be more obvious how to handle this.

If you lack time I might help and do a PR for this use case.

**Comment by pamapa** [comment]
Have you seen the example of https://github.com/authts/react-oidc-context or in case you use AngularJS https://github.com/authts/sample-angular-oidc-client-ts. IMO the latter one could use some improvements, by using a proper router...

**Comment by bastien-m** [comment]
Yes, we should move to this new package instead of doing it manually. It's a legacy code that was using the js version before this new package appears. I tried to mitigate the migration by just migrating to the typescript version.

We'll plane to migrate to react-oidc-context later

**Comment by pamapa** [comment]
This issue (question) staled, closing it for now.
