### ISSUE TITLE
userManager.signinResourceOwnerCredentials requires extra parameters

### ISSUE THREAD

**Issue by Qwl0223** [authts/oidc-client-ts#820]
Hi,

I realized that you have implemented the resource owner credentials flow recently. 

However, I want to add some extra parameters. I find that there are two parameters in UserManagerSettingsStore: extraQueryParams and extraTokenParams settings. Is that possible to include these two parameter in resource owner credentials flow? 

Thanks

**Comment by pamapa** [comment]
- `extraQueryParams` is used as hint for the web request to the authz server in case of the [Authorization Code Grant](https://oauth.net/2/grant-types/authorization-code/). signinResourceOwnerCredentials is using a completely different mechanisms, by using a json post via fetch.

Regarding `extraTokenParams` I am not 100% what the use same is of that. I can see its added to the temporary state. But i do not see where its read back... Looks like dead code.

**Comment by pamapa** [comment]
> Regarding `extraTokenParams` I am not 100% what the use same is of that. I can see its added to the temporary state. But i do not see where its read back... Looks like dead code.

Looks like that `extraTokenParams` is used in `ResponseValidator._processCode` to pass extra parmeters when doing `tokenClient.exchangeCode`. That code is used for PKCE, which is not used for `signinResourceOwnerCredentials`...

**Comment by pamapa** [comment]
@jsedanoj What do you think?

**Comment by jsedanoj** [comment]
Here is the PR: https://github.com/authts/oidc-client-ts/pull/829
