### ISSUE TITLE
Unused setting clockSkewInSeconds

### ISSUE THREAD

**Issue by nicolo-danzi** [authts/oidc-client-ts#825]
I was searching in the code for usages of the setting clockSkewInSeconds, but I see that it is stored in OidcClientSettingsStore and never used. Is it correct? should the documentation be updated?

**Comment by pamapa** [comment]
its deprecated in the source code:
https://github.com/authts/oidc-client-ts/blob/16dd9d0eda31aaea331988c5362dfd810381fe86/src/OidcClientSettings.ts#L81-L82

**Comment by nicolo-danzi** [comment]
This part https://authts.github.io/oidc-client-ts/classes/OidcClientSettingsStore.html#clockSkewInSeconds
So thete is no clock skew check fot iat or exp parameters of the jwt tokens?

**Comment by pamapa** [comment]
Makes sense, can you make a merge request with deprecating all settings in store, where we have a `@deprecated` in the settings? Maybe you can adapt the migration.md as well...
