### ISSUE TITLE
Actual iframe sandbox configuration has no effect and is strongly discouraged

### ISSUE THREAD

**Issue by Badisi** [authts/oidc-client-ts#827]
I just noticed that `Chrome` is now displaying the following warning:

> An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.

Looking at it further:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
> ...it is strongly discouraged to use both allow-scripts and allow-same-origin, as that lets the embedded document remove the sandbox attribute — making it no more secure than not using the sandbox attribute at all.

So the `sandbox` attribute should be modified here:
https://github.com/authts/oidc-client-ts/blob/12024b48738cde94de48ea37252f02811534f531/src/navigators/IFrameWindow.ts#L45

~~But I'm not sure, yet, what would be the proper solution for that.~~

**Comment by Badisi** [comment]
IMO:
`allow-same-origin` is required to allow the redirect html page to be loaded
`allow-scripts` is required so that the redirect html page could post message to the top frame

So removing one, the other or the two would break.

Leaving only one solution: remove the `sandbox` completely.

What do you think ?

**Comment by pamapa** [comment]
Yes i saw the Chrome warning too. Besides same-origin and scripts the `sandbox` feature does disallow quiet more. When we remove that attribute we will loose them (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox).

Maybe its better to live we the warning for now...

**Comment by Badisi** [comment]
I understand what you mean but that is true as long as the iframe remains secured, which is not the case here.

Even if the sandbox disallow more when set, leaving it as it is now would have no advantages. Because when setting both `same-origin` and `scripts`, any attacker could remove the `sandbox` attribute and make it completely useless. And that is what the warning suggests : using both options is no more secure than not using the `sandbox` attribute at all.

---

What if we only remove the `same-origin` ?

This would results in a CORS issue when trying to load the silent redirect url, but that url could be whitelisted in the IDP settings, like the other redirect urls, no ?

**Comment by pamapa** [comment]
> What if we only remove the `same-origin` ?
> 
> This would results in a CORS issue when trying to load the silent redirect url, but that url could be whitelisted in the IDP settings, like the other redirect urls, no ?

Yes I guess so, somebody would need to test this to be 100% sure. For now i do not want to break the behavior of existing applications. But we could introduce an optional to add `same-origin`. The default value would be True. Once we bump this library to 3.0.0, we have the option to change it to false...

**Comment by Badisi** [comment]
I'll try playing with it in the upcoming days and submit a PR to make `same-origin` optional if needed 😉

**Comment by Badisi** [comment]
So, I've made some tests with Auth0, and here are the results:

#### Test 1
> `allow-scripts` + `allow-same-origin` + `silent redirect url whitelisted in Auth0`

Works, but warning in Chrome:
> "An iframe which has both `allow-scripts` and `allow-same-origin` for its sandbox attribute can remove its sandboxing."

---

#### Test 2
> `allow-scripts` + `allow-same-origin` + `silent redirect url NOT whitelisted in Auth0`

> `no sandbox` + `silent redirect url NOT whitelisted in Auth0`

Error in Chrome:
> "Failed to load resource: the server responded with a status of 403 ()"

=> so `whitelisting` is mandatory

---

#### Test 3
> `allow-same-origin` + `silent redirect url whitelisted in Auth0`

Error in Chrome: 
> Blocked script execution in 'http://localhost:4200/oidc/callback/silent_redirect.html?code=XXX' because the document's frame is sandboxed and the `allow-scripts` permission is not set.

---

#### Test 4
> `allow-scripts` + `silent redirect url whitelisted in Auth0`

Error in Chrome:
> ErrorTimeout: IFrame timed out without a response

=> seems like `allow-same-origin` is also mandatory so that the iFrame and the parent page can communicate together

---

#### Results

In order for this to work, we either need the **sandbox** with `same-origin` and `scripts` or **no sandbox** at all...

**Comment by pamapa** [comment]
Thanks for testing.

When looking at the auth0 implementation (https://github.com/auth0/auth0-spa-js/blob/ab09110da603cf4c979ca9ae7304e43892768f52/src/utils.ts#L32-L84) i see that they also do not set the "sandbox" attribute.

**Comment by Badisi** [comment]
I don't really have a preference over the two solutions, I'm just annoyed by the warning as it is displayed multiple times and it negatively impact the user adoption (ie. we are supposed to bring security and this is wrongly telling we are not doing it well).

Looking at Auth0 and MSAL commits history, it seems that Auth0 never used the sandbox at all (and never had any problem not using it), and MSAL used the sandbox only to prevent a top frame navigation (which is questionable as I don't see why it should happen).

Maybe we could just flip a coin 😅

**Comment by AurumTheEnd** [comment]
Took me a while to track down where the warning is coming from in my app, glad to see it is already a recognized issue here.

Thanks for the fix, when it happens in the future!

**Comment by forefrontmartingrantz** [comment]
Any updates in this isse?

**Comment by pamapa** [comment]
> Looking at Auth0 and MSAL commits history, it seems that Auth0 never used the sandbox at all (and never had any problem not using it), and MSAL used the sandbox only to prevent a top frame navigation (which is questionable as I don't see why it should happen).

Lets do it like Auth0 does, lets remove the obsolete sandbox attribute. I will accept such a merge request...

**Comment by forefrontmartingrantz** [comment]
@pamapa I opened a pullrequest removing the sandbox attribute :)
