### ISSUE TITLE
iframe issue - manual renew or manual clean up and create new tokens

### ISSUE THREAD

**Issue by nickmarkfurness** [authts/oidc-client-ts#845]
Hi,

I have a scenario where the embedded iframe causes issues with something else that is integrated so i am unable to use alot of the automatic features of the oidc client.

I am able to perform a silentLogin and obtain the initial access token and refresh token but from here on in i cannot setup much of the automatic stuff that relies on messaging between inner and outer iframes (this is how the other integration works which i can't change), so i disable it.

I have a problem where the access and refresh token go stale because the user has closed the browser and re-open after expiration.
What is the best way to handle this? How can i clear/tear down everything so i can perform silentLogin again??

I can tell when the token is 'expiring' and 'expired', these events trigger i am just not sure what best to do with these to renew or clear down what i have and perform a silent login again.

Any guidance would be great cheers.

**Comment by pamapa** [comment]
On startup of your application you can get the user (`userManager.getUser()`) and check if the access token is still valid (`isAuthenticated = user ? !user.expired : false;`). For this use case no event will be raised, but you can handle it easily by yourself.

**Comment by nickmarkfurness** [comment]
hi,

thanks for this, i will give it a try today.

So i should be able to call siginSilent again once i detect the user is expired and that will work? I will be giving it a try today anyways :)

thanks

**Comment by nickmarkfurness** [comment]
Hi,

I got this working today using your code example BUT i have to clear the stale state.
However after calling clearStaleState i did notice the store in the browser was not cleared up so i had to do it myself. After this i was able to silently log in again.

Might raise a query around the clear stale state not working tomorrow
