### ISSUE TITLE
Deprecated or missing from previous library?

### ISSUE THREAD

**Issue by Menthro** [authts/oidc-client-ts#858]
Hello, would there happen to be a quick list or reference document that happens to talk about the major changes/deprecation from the original pre-fork library: https://github.com/IdentityModel/oidc-client-js ? I am digging into this project currently to find any myself, but it would be nice to know I won't miss anything major.

**Comment by Badisi** [comment]
You can find documentation about the migration [here](https://github.com/authts/oidc-client-ts/blob/main/docs/migration.md)
