### ISSUE TITLE
user signed in, user sign out, and user session changed events are not raised

### ISSUE THREAD

**Issue by fauziyahilma** [authts/oidc-client-ts#885]
I have an SPA built with Vue 3 and and idp client using identityserver v6. I tried to add callback for **user sigend in, user signed out, and user session changed events**, but **none of them were being called** as i have expected.

Steps to reproduce : 
1. Add callbacks for user sigend in, user signed out, and user session changed events 
```
UserManager.events.addUserSignedIn(() => {
    localStorage.setItem("tes3", "tes");
    alert("user signed-in");
  });

  UserManager.events.addUserSignedOut(() => {
    localStorage.setItem("tes4", "tes");
    alert("user signed-out");
  });

  UserManager.events.addUserSessionChanged(() => {
    console.log("addUserSessionChanged 1");
  });
```

2. Sign In to the app. **Sign in was successful but callback for user signed in event was not called.**
3. Sign out from the app. **Sign out was successful but callback for user signed out and user session changed were not called.**

The only case that user signed out event got raised was when I signed in to the app in 2 different browsers and I got automatically signed out from the app. 

Here's the configuration i have passed when constructing UserManager instance : 
```
{
      userStore: new WebStorageStateStore({ store: window.localStorage }),
      authority: "config.idpUrl",
      client_id: "config.idpClientId",
      redirect_uri: `${config.baseUrl}/oidccallback/`,
      silent_redirect_uri:
         `${config.baseUrl}/oidccallbacksilent/`,
      post_logout_redirect_uri:
         `${config.baseUrl}/internal-test/`,
      scope: "openid",
      silentRequestTimeoutInSeconds: 1200,
      response_type: "code",
      monitorSession: true,
}
```

I would like some help to see what have caused those events not being raised. 
Thank you.

**Comment by pamapa** [comment]
You will need to hold the `UserManager` instance in a global/state variable and reuse it from there. Additionally adding logging gives you some insights (https://authts.github.io/oidc-client-ts/#logging).

**Comment by fauziyahilma** [comment]
Hi @pamapa 
I think the instance was already declared in global scope. However, I tried to change the instantiation a bit and assign the UserManager instance to window.userManager, but still no luck. 
As a matter of fact, I did notice that when I logged out, the iframe (please check below screenshot) element was removed. Could it be the reason why the event user sign out wasn't triggered?  
![image](https://user-images.githubusercontent.com/48611132/218983817-c870e3e7-567d-4dd6-8304-974f3ebc4c6c.png)

**Comment by deanmaster** [comment]
I got almost the same problem with this one but with a different symtom. I always have "unchanged" message from checkSessionIframe. I can see the code 
`this._frame.contentWindow.postMessage(this._client_id + " " + this._session_state, this._frame_origin);` is called but the message return always "unchanged"

1. If I go to my IDP and delete user session. I would expect this._session_state will not matched anymore -> "changed" status should be post back to RP Iframe. But I still received "unchanged"
2. If I try to delete the cookie of my IDP domain -> I got "changed" but this does not help because i'm manual delete cookie information from browser which can't be happen in case I open my IDP in another browser and follow step 1.

**Comment by pamapa** [comment]
@deanmaster You will need to track down the issue. Start with what you receive from the IDP, you can add logging support in this library or add persistent network logging in your browser dev tool

**Comment by pamapa** [comment]
This issue (question) staled, closing it for now.

**Comment by jeevasusej** [comment]
I am facing this issue with the same configuration.
