### ISSUE TITLE
Feature request make pkce optional

### ISSUE THREAD

**Issue by satanshiro** [authts/oidc-client-ts#895]
I stumbled into a problem where I need to disable PKCE validation.
why? 
lets say I have one frontend app that does the login process but I would like to send a redirect url to another app in my organization that will finish the login process and get a code. (considering that this external redirect url is a valid one by the idp).
So I either have to start the login process from the second app or disable pkce.
one might say just duplicate the login component to every app in the organization but I'm not sure that's effective considering maintenance costs and different apps might be different languages/technologies/deployment behavior altogether.
I am specifically using keycloak and in their documentation if the initiating client does not send a code challenge, pkce validation will be disabled but oidc-ts does not give me the option to disable it
refference:
![image](https://user-images.githubusercontent.com/38865738/219323205-cf5ad6e6-2ef6-486f-bf2c-89e5c95f30a1.png)
I have tested locally changing the code and would like to open a pr if people agree.
have a nice day

**Comment by pamapa** [comment]
I would accept such a merge request if the changes are not too invasive. Best would be if you try this in a local copy of the library and propose changes once you have something working...

**Comment by satanshiro** [comment]
yes I tested locally and it works, I can't push a branch because I don't have permissions, but these are the main changes:
![image](https://user-images.githubusercontent.com/38865738/219365458-576ccb4f-4e92-4e59-9245-87e9f3aff926.png)
in oidcclientsettings:
![image](https://user-images.githubusercontent.com/38865738/219365550-014493d3-fbd4-4ee3-adbd-0c51fd038e71.png)
![image](https://user-images.githubusercontent.com/38865738/219365681-2b7dca1c-dc4b-4042-952a-d82b72ff3bc3.png)

**Comment by pamapa** [comment]
please create a merge request. You fork this project and create a branch on the forked project. On this branch you make a commit with your changes. Within this project you create via UI a pull request. Then i can review the changes and give you feedback...

First feedback: in oidcclientsettings: please a a proper type doc comment, which explains that specific feature, such that others understand when and why its useful and it should end with `(default: false)`

**Comment by pamapa** [comment]
It might be better to handle this in `SigninState` if `code_verifier` is not set `code_challenge` is not set and your if above works too. You can pass the new option `disablePKCE` through the code like `extraQueryParams`...

**Comment by satanshiro** [comment]
feature merged waiting for release

**Comment by satanshiro** [comment]
@pamapa i saw that last release was a month ago, is there a plan for release soon?

**Comment by pamapa** [comment]
@satanshiro can make one this or next week
