### ISSUE TITLE
Custom MetadataService

### ISSUE THREAD

**Issue by howlettt** [authts/oidc-client-ts#919]
I'm trying to create a custom `MetadataService` class to cache the metadata in local storage but I can't seem to find a way to do this by extending `OidcClient` & `UserManager` as per the migration docs https://github.com/authts/oidc-client-ts/blob/main/docs/migration.md
```
removed ResponseValidatorCtor and MetadataServiceCtor
if necessary OidcClient / UserManager classes may be extended to alter their behavior
```

The problem I'm running into is the `OidcClient` constructor passes the metadata service into `_validator` & `_tokenClient` and I'm not seeing any way to override this behavior. Creating a custom class extending `OidcClient` I can set a custom `metadataService` but I don't see how I can get the `_validator` & `_tokenClient` to use it. One option would be to recreate `_validator` & `_tokenClient` in the derived constructor, but the `ResponseValidator` & `TokenClient` classes aren't exported from the package.
https://github.com/authts/oidc-client-ts/blob/23bf2958a74d85845bad693935de29c1a88beca4/src/OidcClient.ts
```
    public constructor(settings: OidcClientSettings) {
        this.settings = new OidcClientSettingsStore(settings);

        this.metadataService = new MetadataService(this.settings);
        this._validator = new ResponseValidator(this.settings, this.metadataService);
        this._tokenClient = new TokenClient(this.settings, this.metadataService);
    }
```

What I have so far
```
import {
  MetadataService,
  OidcClient,
  OidcClientSettings,
  OidcClientSettingsStore,
  OidcMetadata,
  UserManager,
  UserManagerSettings,
} from "oidc-client-ts";

class CachedMetadataService extends MetadataService {
  private metadata: Partial<OidcMetadata> | null = null;

  public async getMetadata(): Promise<Partial<OidcMetadata>> {
    if (this.metadata) {
      return this.metadata;
    }

    let metaData = LocalStorageUtil.get();
    if (!metaData) {
      metaData = await super.getMetadata();
      this.metadata = metaData;
      LocalStorageUtil.set(metaData);
    }

    return metaData;
  }
}

class CachedOidcClient extends OidcClient {
  public readonly metadataService: CachedMetadataService;

  public constructor(settings: OidcClientSettings) {
    super(settings);

    this.metadataService = new CachedMetadataService(this.settings);
  }
}

export default class CachedUserManager extends UserManager {
  protected readonly _client: CachedOidcClient;

  public constructor(settings: UserManagerSettings) {
    super(settings);

    this._client = new CachedOidcClient(settings);
  }
}
```

**Comment by pamapa** [comment]
Agree, we could add an additional constructor, where one must pass all members constructed in the main constructor: settings, metadataService, validator, tokenClient.
