### ISSUE TITLE
Pass resource payload to refresh token call

### ISSUE THREAD

**Issue by Annouar** [authts/oidc-client-ts#920]
Hello everyone !
Hope you're doing well !

I am desperately trying to pass a resource param to refresh_token request, but it seems not possible through `mgr.signinSilent `method as `OidcClient.useRefreshToken` method call `exchangeRefreshToken` under the hood with those params : refresh_token, scope and timeoutInSeconds.

So, do you know a way to pass this extra param (resource) to refresh token request ?

If we need to push a MR, should we pass a resource param (or an extraQueryParams containing resource) from `mgr.signinSilent` down to `tokenClient.exchangeRefreshToken` through `useRefreshToken` ?

Thanks a lot !

**Comment by pamapa** [comment]
Yes this is not possible yet, in the OidcClient you can find `CreateSigninRequestArgs.resource?: string | string[];`. This could be added to optional parameters of `UserManager: ExtraSigninRequestArgs`. With this the silent iframe code parts already works, but for your case you will need to pass it down the refresh token code path...

**Comment by pamapa** [comment]
I guess it also makes sense to support the `settings.resource` within the refresh token code path...

**Comment by Annouar** [comment]
Hey @pamapa !

Thanks for the answer, I'll try my best to push a MR asap :)

**Comment by Annouar** [comment]
Hey @pamapa,

I've linked a PR regarding this issue. I've tried to the [RFC 8707 - Resource Indicators](https://www.rfc-editor.org/rfc/rfc8707.html) in order to implement the issue.

Best regards !
