### ISSUE TITLE
logout is called right away after login

### ISSUE THREAD

**Issue by kostia-lev** [authts/oidc-client-ts#938]
I am trying to switch from oidc-client and I see that after login logout is called by oidc-client-ts. I noticed that when I remove from localStorage this item: 
<img width="276" alt="image" src="https://user-images.githubusercontent.com/1144764/227262077-d40f97f2-7b53-4058-8a6a-ce46b92c172b.png">
it starts logging in correctly.
This is oidc-client-ts settings:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/1144764/227262896-7a15483c-60c3-4b6d-bbcc-5b0682061a5a.png">
Where is this item set? 
<img width="784" alt="image" src="https://user-images.githubusercontent.com/1144764/227263192-38724633-6065-4e79-94a3-220fbfa9d125.png">

**Comment by pamapa** [comment]
To find out why its automatically logs out, you can enable logging within this library like described [here](https://authts.github.io/oidc-client-ts/#logging).

**Comment by pamapa** [comment]
This issue (question) staled, closing it for now.
