### ISSUE TITLE
how to achive keycloak.init({ onLoad: check-sso }) in OIDC-client adapter

### ISSUE THREAD

**Issue by rameshreddy89** [authts/oidc-client-ts#940]
How do i achive this using oidc-client adapter . Using keycloak adpater I will get the user is authendicated or not authendicated if the use user is not authendicated I shall bring up my custom page. signinRedirect is directly taking me to the login page. I want to ask some information before the keycloak login page.. 

TIA..

**keycloak.init({ onLoad: check-sso })**

this.UserManager = new UserManager({
            ...IDENTITY_CONFIG,
            userStore: new WebStorageStateStore({ store: window.sessionStorage }),
            stateStore: new WebStorageStateStore({ store: window.sessionStorage })
            
});

I dont want to use localstorage.. if I use session storage it works fine for first time(untile browser have the keycloak cookies). if the user logged in then the session created and user info is stored in session. but I can not retriew the information in another tab. for example if user open one more tab and opens the app the session or empty untile I invoke the keycloak auth request..

**Comment by pamapa** [comment]
> All i need is if I have any method to get the userSession accross all the tab . Keycloak is maintaining separate cookies which we cannot read.

Instead of `sessionStorage`  you can use `localStorage` for the `userStore`. `localStorage` is accessible for the same application across TABs.

**Comment by rameshreddy89** [comment]
> I struggle a lot with the whole think. Can you provide a working keycloak example please? How to setup the configuration?

You want in with oidc adaptor.. 
https://medium.com/@franciscopa91/how-to-implement-oidc-authentication-with-react-context-api-and-react-router-205e13f2d49 .. this link helps me to setup the keycloak with oidc-client-ts adaptor..

**Comment by rameshreddy89** [comment]
> > All i need is if I have any method to get the userSession accross all the tab . Keycloak is maintaining separate cookies which we cannot read.
> 
> Instead of `sessionStorage` you can use `localStorage` for the `userStore`. `localStorage` is accessible for the same application across TABs.

Due to security reason I dont want to use the localStorage..

I tried with signinSilent  but it shows error in new tab, if we add any param in signinRedirect which will return me the flag saying user is authendicated or not authendicate .

Currently signinRedirect shows the login page if the useris not logged In, we dont have a control to decide wheater should we show the login page or not.. It would be good if it send us the promise saying authendicated / not authendicated .

**Comment by rameshreddy89** [comment]
![image](https://github.com/authts/oidc-client-ts/assets/26972768/7373977a-486c-4bdc-9e5c-31610cb6339d)

**Comment by rameshreddy89** [comment]
I have found a solution for this , we need to send a param to signinRedirect method to achieve this, I am using it in this way , on new tab if the session is not available then i will call signinRedirect({ prompt:'none' }) like this , if cookies are present in the browser then the app will auto login , if the cookies not availble then catch block will be triggered in "signinRedirectCallback"  method, I have written code inside signinRedirectCallback catch to navigate my custom login page. 
 
Summary is : call signinRedirect method with ({ prompt:'none' }) to avoid the login screen
