### ISSUE TITLE
Silent Authentication of Existing Authenticated User On Specific Page

### ISSUE THREAD

**Issue by JohnCWakley** [authts/oidc-client-ts#947]
I don't have an issue, this is a question (not sure how to set it to a question).

I have a web app with SSO authentication. Within the app, there is a page that accesses a separate API. The page in itself is a separate react project (technically an SPA in itself) injected into the main web app. The user is already logged in and is required to be in order to access this specific page.

The page is using `oidc-client-ts` to authenticate the existing user.

It does pick up the main web app cookie and authenticates the user to access the API (a separate token is required to access endpoints). The API is a separate project as well, but uses the same identity provider as the main web app.

What we are trying to do is avoid the 3 redirects as it authenticates the existing user to access the API. We have tried a multitude of different theories, including a hidden custom `iframe` that would do the authentication and handle the redirects, then write the token to storage, but the entire page is still redirecting.

We are using ASP.NET to serve the main web app, and the API is also an ASP.NET backend. We are using React on the frontend.

Can anyone suggest anything that may result in zero page redirects while silently authenticating the existing user (we do not need to redirect to a login page, since that was already done to sign into the main web app).

Thank you in advance :)

**Comment by pamapa** [comment]
This issue (question) staled, closing it for now.
