### ISSUE TITLE
Is it possible to opt out of storing data in userStore, ie. sessionStorage/localStorage?

### ISSUE THREAD

**Issue by johann1301s** [authts/oidc-client-ts#953]
According to the docs, there is a way to specify the userStore, ie. a place where user data is stored.

See [this link](https://authts.github.io/oidc-client-ts/interfaces/UserManagerSettings.html#userStore) for reference.

Is it possible to opt out of this?

**Comment by pamapa** [comment]
You can inject your own `userStore` (https://github.com/authts/oidc-client-ts/blob/main/src/UserManagerSettings.ts#L84), where you can do whatever you need to...
