### ISSUE TITLE
renewal event fail in inactive tab

### ISSUE THREAD

**Issue by kyugoa** [authts/oidc-client-ts#954]
most browsers will throttle tab activities to preserve resources and battery life on the user’s device. with that, if a user switch away from the tab, token refresh timer won't work properly. looking at the web, the fix would be using web worker for the timer. should this lib incorporate a fix like that?

**Comment by pamapa** [comment]
This is a known problem. I have the feeling using web worker will make everything even more complex...

**Comment by misl-smlz** [comment]
We ran into this issue, too. Is there any good workaround right now?

**Comment by misl-smlz** [comment]
I'm thinking of a solution via the [Page Visibility API](https://davidwalsh.name/page-visibility).

That could be also integrated in oidc-client-ts: Listen to hidden / visible state of the tab and push a refresh call when the tab get's visible again. @pamapa What do you think?

**Comment by pamapa** [comment]
Maybe worth a try. Would help for cases where you still have a proper IDP session cookie or a vaild refresh token.

**Comment by pamapa** [comment]
This issue (question) staled some time ago, closing it for now.

**Comment by jmewes** [comment]
Here is the stacktrace from this kind of error, written off from a screenshot from a tablet, because it seem like the behavior cannot be reproduced when the Chrome developer tools are attached to the device:

```
TypeError: Failed to fetch
  at Eb.fetchWithTimeout
  at Eb.postForm
  at vP.exchangeRefreshToken
  at async sj.useRefreshToken
  at async MP._useRefreshToken
  at async MP.signinSilent
  at async _tokenExpiring
  at async Bp.raise
```
