### ISSUE TITLE
Support for Pushed Authorization Requests (PAR)? 

### ISSUE THREAD

**Issue by theadell** [authts/oidc-client-ts#956]
Hi there,

I'm interested in using Pushed Authorization Requests (PAR) in my application, but it seems that there is currently no built-in support for PAR in the library, am I correct?

I understand that PAR is not yet widely supported, but I would like to know if there are any plans to add support for PAR in a future version of oidc-client-ts.

Thanks in advance for your help!

**Comment by pamapa** [comment]
If it fits into this library with not much overhead, then yes. But there are no plans to implement them by me, you will need to implement it and provide a merge request...

Some features may already be possible when looking at https://datatracker.ietf.org/doc/html/rfc9126, e.g. `client_assertion_type` and `client_assertion` can be injected via `OidcClientSettings.extraQueryParams`...

**Comment by pamapa** [comment]
This issue (question) staled, closing it for now.
