### ISSUE TITLE
how to specify audience in client settings

### ISSUE THREAD

**Issue by LouLamSan** [authts/oidc-client-ts#963]
hi,may I ask how to specify audience in the client-side? At present, it seems that there is no such attribute available.

**Comment by pamapa** [comment]
I am not aware that this is possible. I am referring to https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest. Can you please provide a link to the RFC describing your requirement? Typically the audience is defined by the authz server. This library supports accessing the audience via user profile aud property.

**Comment by LouLamSan** [comment]
How to disable audience validation on the client?I am using oidc-client.ts and the client has acquired both the ID token and access token, but oidc-client throws an error indicating that the audience is invalid.

**Comment by pamapa** [comment]
There is no audience validation, what we have is this:
https://github.com/authts/oidc-client-ts/blob/499a9e88b1e33626ec12b3a2f94bb2a3b9f08545/src/ResponseValidator.ts#L189-L216

**Comment by LouLamSan** [comment]
Sorry, I am not actually a professional front-end developer. Can you tell me how to configure to achieve the goal of not verifying the audience? I have carefully read the code snippet you provided, but I still don't know how to configure it.

**Comment by pamapa** [comment]
I first need to understand your problem. Which exact exception/log do you receive? I need to be able to match the source code. Maybe its also good for you to enable logging (see https://authts.github.io/oidc-client-ts/#logging). You can then copy/paste the logs here...

**Comment by LouLamSan** [comment]
The issue I encountered is that after retrieving the ID token and access token and returning them to the client, oidc-client threw an error with the following message:

```
Error: Invalid audience in token: emailapi,orderapi
    at Function.e3 [as validateJwtAttributes] (oidc-client.min.js:49:2898)
    at oidc-client.min.js:1:61897
```

So I would like to know how to configure oidc-client to disable audience validation.（Thank you for your answer. Sorry for my delayed response.）

**Comment by pamapa** [comment]
You are using the predecessor library (https://github.com/IdentityModel/oidc-client-js) and not this library!

Your error comes from here:
https://github.com/IdentityModel/oidc-client-js/blob/edec8f59897bdeedcb0b4167586d49626203c2c1/src/JoseUtilImpl.js#L55

That code does not exist in this library...
