### ISSUE TITLE
Support for custom user state

### ISSUE THREAD

**Issue by thibant** [authts/oidc-client-ts#978]
I wanted to customize user state stored in local storage. Currently I'm using below codes:
`    userManager.signinRedirectCallback()
      .then((user) => {

        const allKeys = Object.keys(localStorage);
        const oidcKeys = allKeys.filter(key => key.startsWith("oidc"));
        console.log("oidcKey : " + oidcKeys);

       const filteredUser = new User({
          "profile": {
            "first_name": user.profile.first_name,
            "email": user.profile.email
          },
          "expires_at": 1681619955
        });

        localStorage.setItem(oidcKeys, JSON.stringify(filteredUser));
		
      })
      .catch((error) => {
        console.error('Error during callback:', error);
        userManager.clearStaleState();
        });
      });`
    
 As above, I'm only able to alter local storage after signinRedirectCallback invoked and user state initially saved into local storage. But actually I'm looking for a way to customized user state before the initial user state saved into local storage. How to implement that.

**Comment by pamapa** [comment]
You can inject your own storage class, see https://github.com/authts/oidc-client-ts/blob/39566c7699a22336a9e213a2fe788dc577b20f28/src/UserManagerSettings.ts#L84

**Comment by thibant** [comment]
I code as  `userStore: new WebStorageStateStore({ store: window.localStorage, prefix: "oidc_development:" })`
In this case, I'm using local storage, its working fine.
No, I want filter out all the tokens from user store. And instead only store fields as first_name, email, expires_at
FYI, I'm working with React.js application.

**Comment by pamapa** [comment]
You will need to override get/set, etc function of `WebStorageStateStore` and make your own custom class...

**Comment by thibant** [comment]
I have tried to override set function in WebStorageStateStore, so that my user store only have expires_at field stored in local storage. Code as below:

`import {WebStorageStateStore } from 'oidc-client-ts';

export class CustomWebStorageStateStore extends WebStorageStateStore {
    constructor({ prefix = "oidc.", store = localStorage } = {}) {
        super({ prefix, store });
        this._expirationKey = "oidc.expires_at";
    }

    async set(key, value) {
        if (key === "access_token") {
            const token = JSON.parse(value);
            const expireTime = token.expires_in
                ? Date.now() + token.expires_in * 1000
                : undefined;

            if (expireTime) {
                await this._store.setItem(this._expirationKey, expireTime.toString());
            }
        }

        await super.set(key, value);
    }
}


import { CustomWebStorageStateStore } from './CustomWebStorageStateStore';

export class AuthorizeService {
  userManager;

  constructor() {

    const settings = {
      authority: 'xxxxxxxxxx',
      client_id: 'xxxxxxxxxxxxxx',
      .......................
      userStore: new CustomWebStorageStateStore(),
    };`
    
    
  but still my user store stored as default content. No effect at all

**Comment by pamapa** [comment]
You will need to debug that. Maybe add some logging in your `CustomWebStorageStateStore` and add logging for the oidc-client-ts (https://authts.github.io/oidc-client-ts/#md:logging) too....

**Comment by pamapa** [comment]
This issue (question) staled, closing it for now.
