### ISSUE TITLE
Event when token is refreshed

### ISSUE THREAD

**Issue by wawyed** [authts/oidc-client-ts#987]
Is there an event that tells you when the token has been refreshed? I can't seem to find one in the docs

**Comment by pamapa** [comment]
You could use this:
https://github.com/authts/oidc-client-ts/blob/7c8dc996f36008aa8ca8555576f971db5c1cb0e9/src/UserManagerEvents.ts#L62-L67

You are interested on the "re-established" case...

**Comment by wawyed** [comment]
Thank you for the quick answer! That seems to give me what I needed :)
