### ISSUE TITLE
Optional protocol param "ui_locales" only configurable in constructor?

### ISSUE THREAD

**Issue by ker-nicolaib** [authts/oidc-client-ts#995]
Hello,

is there any chance to change the optional protocol param "ui_locales" after it was passed as part of the UserManagerSettings object in the UserManager constructor?
Currently when i want to change it after the instantiation it is readonly and can't be set.

Thanks for your help.

**Comment by pamapa** [comment]
Please provide a merge request and add it to `ExtraSigninRequestArgs = Pick<CreateSigninRequestArgs, ...`. In the meantime you can pass it as args in `mgr.signinRedirect`, you will just need to ignore the type error...

**Comment by pamapa** [comment]
Like this https://github.com/authts/oidc-client-ts/pull/977
